// Auto-generated by wasmify gen-proto. DO NOT EDIT.
#ifndef SIMPLELIB_PROTO_API_BRIDGE_H_
#define SIMPLELIB_PROTO_API_BRIDGE_H_

#include <cstdint>

extern "C" {

void* wasm_alloc(int32_t size);
void wasm_free(void* ptr);
int64_t wasm_invoke(int32_t service_id, int32_t method_id, void* req, int32_t req_len);
int32_t wasm_init();
void wasm_shutdown();

} // extern "C"

#endif // SIMPLELIB_PROTO_API_BRIDGE_H_
