// Auto-generated by wasmify gen-proto. DO NOT EDIT.
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>

#include "calculator.h"

#define WASM_EXPORT(name) __attribute__((export_name(#name)))
#define WASM_IMPORT(module, name) __attribute__((import_module(#module), import_name(#name)))

extern "C" {

WASM_EXPORT(wasm_alloc)
void* wasm_alloc(int32_t size) { return malloc(size); }

WASM_EXPORT(wasm_free)
void wasm_free(void* ptr) { free(ptr); }

WASM_IMPORT(wasmify, callback_invoke)
int64_t wasmify_callback_invoke(int32_t callback_id, int32_t method_id, void* req, int32_t req_len);

// ======================================
// Proto3 wire format helpers
// ======================================

static int64_t encode_result(void* ptr, int32_t len) {
    return (static_cast<int64_t>(reinterpret_cast<uintptr_t>(ptr)) << 32) | static_cast<uint32_t>(len);
}

class ProtoReader {
public:
    const uint8_t* pos_;
    const uint8_t* end_;
    uint32_t last_field_;
    uint32_t last_wire_;

    ProtoReader(const void* data, int32_t len)
        : pos_(static_cast<const uint8_t*>(data)),
          end_(pos_ + len), last_field_(0), last_wire_(0) {}

    bool has_data() const { return pos_ < end_; }

    bool next() {
        if (pos_ >= end_) return false;
        uint64_t tag;
        if (!read_varint_raw(&tag)) return false;
        last_field_ = static_cast<uint32_t>(tag >> 3);
        last_wire_ = static_cast<uint32_t>(tag & 7);
        return true;
    }

    uint32_t field() const { return last_field_; }
    uint32_t wire() const { return last_wire_; }

    uint64_t read_varint() {
        uint64_t v = 0;
        read_varint_raw(&v);
        return v;
    }

    int32_t read_int32() { return static_cast<int32_t>(read_varint()); }
    int64_t read_int64() { return static_cast<int64_t>(read_varint()); }
    uint32_t read_uint32() { return static_cast<uint32_t>(read_varint()); }
    uint64_t read_uint64() { return read_varint(); }
    bool read_bool() { return read_varint() != 0; }

    float read_float() {
        float v = 0;
        if (pos_ + 4 <= end_) { memcpy(&v, pos_, 4); pos_ += 4; }
        return v;
    }

    double read_double() {
        double v = 0;
        if (pos_ + 8 <= end_) { memcpy(&v, pos_, 8); pos_ += 8; }
        return v;
    }

    std::string read_string() {
        uint64_t len = read_varint();
        if (pos_ + len > end_) { pos_ = end_; return ""; }
        std::string s(reinterpret_cast<const char*>(pos_), static_cast<size_t>(len));
        pos_ += len;
        return s;
    }

    // Returns a sub-reader for an embedded message
    ProtoReader read_submessage() {
        uint64_t len = read_varint();
        if (pos_ + len > end_) { pos_ = end_; return ProtoReader(nullptr, 0); }
        ProtoReader sub(pos_, static_cast<int32_t>(len));
        pos_ += len;
        return sub;
    }

    void skip() {
        switch (last_wire_) {
        case 0: read_varint(); break;
        case 1: pos_ += 8; break;
        case 2: { uint64_t len = read_varint(); pos_ += len; } break;
        case 5: pos_ += 4; break;
        default: pos_ = end_; break;
        }
        if (pos_ > end_) pos_ = end_;
    }

private:
    bool read_varint_raw(uint64_t* val) {
        *val = 0;
        for (int shift = 0; shift < 64 && pos_ < end_; shift += 7) {
            uint8_t byte = *pos_++;
            *val |= static_cast<uint64_t>(byte & 0x7F) << shift;
            if ((byte & 0x80) == 0) return true;
        }
        return false;
    }
};

// ProtoWriter defers its initial heap allocation until the first write.
// Serialising an empty response therefore costs zero malloc/free pairs;
// the previous eager allocation leaked a 128-byte buffer on every call
// that returned no bytes (setters, voids, empty getters), which for a
// single-run parse/analyze loop piled up millions of bytes of wasm heap
// until the module ran out of memory.
class ProtoWriter {
public:
    uint8_t* data_;
    int32_t size_;
    int32_t cap_;

    ProtoWriter() : data_(nullptr), size_(0), cap_(0) {}

    void ensure(int32_t need) {
        if (data_ == nullptr) {
            cap_ = need > 128 ? need : 128;
            data_ = static_cast<uint8_t*>(malloc(cap_));
            return;
        }
        while (size_ + need > cap_) {
            cap_ *= 2;
            data_ = static_cast<uint8_t*>(realloc(data_, cap_));
        }
    }

    void write_raw(const void* src, int32_t len) {
        ensure(len);
        memcpy(data_ + size_, src, len);
        size_ += len;
    }

    void write_varint(uint64_t val) {
        ensure(10);
        while (val > 0x7F) {
            data_[size_++] = static_cast<uint8_t>((val & 0x7F) | 0x80);
            val >>= 7;
        }
        data_[size_++] = static_cast<uint8_t>(val);
    }

    void write_tag(uint32_t field, uint32_t wire) {
        write_varint((static_cast<uint64_t>(field) << 3) | wire);
    }

    void write_int32(uint32_t field, int32_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(static_cast<uint64_t>(static_cast<uint32_t>(val)));
    }

    void write_int64(uint32_t field, int64_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(static_cast<uint64_t>(val));
    }

    void write_uint32(uint32_t field, uint32_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(val);
    }

    void write_uint64(uint32_t field, uint64_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(val);
    }

    void write_bool(uint32_t field, bool val) {
        if (!val) return;
        write_tag(field, 0);
        write_varint(1);
    }

    void write_float(uint32_t field, float val) {
        uint32_t bits;
        memcpy(&bits, &val, 4);
        if (bits == 0) return;
        write_tag(field, 5);
        write_raw(&val, 4);
    }

    void write_double(uint32_t field, double val) {
        uint64_t bits;
        memcpy(&bits, &val, 8);
        if (bits == 0) return;
        write_tag(field, 1);
        write_raw(&val, 8);
    }

    void write_string(uint32_t field, const std::string& s) {
        if (s.empty()) return;
        write_tag(field, 2);
        write_varint(s.size());
        write_raw(s.data(), static_cast<int32_t>(s.size()));
    }

    void write_string(uint32_t field, const char* s, uint32_t len) {
        if (len == 0) return;
        write_tag(field, 2);
        write_varint(len);
        write_raw(s, len);
    }

    void write_submessage(uint32_t field, const ProtoWriter& sub) {
        if (sub.size_ == 0) return;
        write_tag(field, 2);
        write_varint(sub.size_);
        write_raw(sub.data_, sub.size_);
    }

    void write_handle(uint32_t field, uint64_t ptr) {
        if (ptr == 0) return;
        // Handle is a submessage with field 1 = uint64 ptr
        ProtoWriter sub;
        sub.write_uint64(1, ptr);
        write_submessage(field, sub);
        free(sub.data_);
    }

    // ---- Repeated primitive helpers (packed encoding) ----
    // Note: this class lives inside extern "C" {}, so we cannot declare
    // member templates. Each packed variant is written out explicitly.

    void write_repeated_int32(uint32_t field, const std::vector<int32_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (int32_t v : vec) sub.write_varint(static_cast<uint64_t>(static_cast<uint32_t>(v)));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_int64(uint32_t field, const std::vector<int64_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (int64_t v : vec) sub.write_varint(static_cast<uint64_t>(v));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_uint32(uint32_t field, const std::vector<uint32_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (uint32_t v : vec) sub.write_varint(static_cast<uint64_t>(v));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_uint64(uint32_t field, const std::vector<uint64_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (uint64_t v : vec) sub.write_varint(v);
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_bool(uint32_t field, const std::vector<bool>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (bool v : vec) sub.write_varint(v ? 1u : 0u);
        write_submessage(field, sub);
        free(sub.data_);
    }

    void write_repeated_double(uint32_t field, const std::vector<double>& vec) {
        if (vec.empty()) return;
        write_tag(field, 2);
        write_varint(static_cast<uint64_t>(vec.size()) * 8u);
        for (double v : vec) write_raw(&v, 8);
    }
    void write_repeated_float(uint32_t field, const std::vector<float>& vec) {
        if (vec.empty()) return;
        write_tag(field, 2);
        write_varint(static_cast<uint64_t>(vec.size()) * 4u);
        for (float v : vec) write_raw(&v, 4);
    }

    // Repeated string/bytes are NOT packed in proto3; each element emits
    // its own length-delimited tag.
    void write_repeated_string(uint32_t field, const std::vector<std::string>& vec) {
        for (const auto& s : vec) {
            write_tag(field, 2);
            write_varint(s.size());
            write_raw(s.data(), static_cast<int32_t>(s.size()));
        }
    }

    // Repeated handle: each element becomes a length-delimited submessage
    // with field 1 = uint64 ptr. Null pointers are skipped. Two overloads
    // cover the common vector<T*> and vector<const T*> cases; note that we
    // cannot use a member template here (extern "C" block).
    void write_repeated_handle(uint32_t field, const std::vector<void*>& vec) {
        for (void* p : vec) {
            if (p == nullptr) continue;
            write_handle(field, reinterpret_cast<uint64_t>(p));
        }
    }

    void write_error(const char* msg) {
        write_string(15, msg, static_cast<uint32_t>(strlen(msg)));
    }

    void write_error(const std::string& msg) {
        write_string(15, msg);
    }

    int64_t finish() {
        // Empty response: the host short-circuits on length and never
        // calls wasm_free, so any lazy-allocated buffer would leak.
        // Free it here and return nullptr so the host skips cleanly.
        if (size_ == 0) {
            if (data_ != nullptr) {
                free(data_);
                data_ = nullptr;
                cap_ = 0;
            }
            return encode_result(nullptr, 0);
        }
        return encode_result(data_, size_);
    }
};

// Read handle ptr from a submessage (field 1 = uint64)
static uint64_t read_handle_ptr(ProtoReader& reader) {
    ProtoReader sub = reader.read_submessage();
    uint64_t ptr = 0;
    while (sub.has_data() && sub.next()) {
        if (sub.field() == 1) ptr = sub.read_uint64();
        else sub.skip();
    }
    return ptr;
}

// Read handle ptr from top-level message (field 1 = uint64)
static uint64_t read_handle_direct(const void* req, int32_t req_len) {
    ProtoReader reader(req, req_len);
    uint64_t ptr = 0;
    while (reader.has_data() && reader.next()) {
        if (reader.field() == 1) ptr = reader.read_uint64();
        else reader.skip();
    }
    return ptr;
}

// ======================================
// Service and method IDs
// ======================================

static const int32_t SERVICE_SIMPLELIB_PROTO = 0;
static const int32_t METHOD_SIMPLELIB_PROTO_ADD = 0;
static const int32_t METHOD_SIMPLELIB_PROTO_AGGREGATE_RESULTS = 1;
static const int32_t METHOD_SIMPLELIB_PROTO_FORMAT_RESULT = 2;
static const int32_t METHOD_SIMPLELIB_PROTO_RUN_WITH_LOGGER = 3;
static const int32_t METHOD_SIMPLELIB_PROTO_VERSION = 4;

static const int32_t SERVICE_ANIMAL = 1;
static const int32_t METHOD_ANIMAL_SET_SPECIES = 0;
static const int32_t METHOD_ANIMAL_SPECIES = 1;
static const int32_t METHOD_ANIMAL_RELEASE_HANDLE = 2;

static const int32_t SERVICE_CALCULATOR = 2;
static const int32_t METHOD_CALCULATOR_NEW = 0;
static const int32_t METHOD_CALCULATOR_ADD_TO_HISTORY = 1;
static const int32_t METHOD_CALCULATOR_CLEAR_HISTORY = 2;
static const int32_t METHOD_CALCULATOR_COMPUTE = 3;
static const int32_t METHOD_CALCULATOR_COMPUTE_SAFE = 4;
static const int32_t METHOD_CALCULATOR_GET_HISTORY = 5;
static const int32_t METHOD_CALCULATOR_NAME = 6;
static const int32_t METHOD_CALCULATOR_SET_NAME = 7;
static const int32_t METHOD_CALCULATOR_RELEASE_HANDLE = 8;

static const int32_t SERVICE_CANINE = 3;
static const int32_t METHOD_CANINE_BREED = 0;
static const int32_t METHOD_CANINE_SET_BREED = 1;
static const int32_t METHOD_CANINE_RELEASE_HANDLE = 2;

static const int32_t SERVICE_CIRCLE = 4;
static const int32_t METHOD_CIRCLE_NEW = 0;
static const int32_t METHOD_CIRCLE_AREA = 1;
static const int32_t METHOD_CIRCLE_RADIUS = 2;
static const int32_t METHOD_CIRCLE_RELEASE_HANDLE = 3;

static const int32_t SERVICE_DOG = 5;
static const int32_t METHOD_DOG_NEW = 0;
static const int32_t METHOD_DOG_BARK_VOLUME = 1;
static const int32_t METHOD_DOG_SET_BARK_VOLUME = 2;
static const int32_t METHOD_DOG_RELEASE_HANDLE = 3;

static const int32_t SERVICE_HEADING_NODE = 6;
static const int32_t METHOD_HEADING_NODE_NEW = 0;
static const int32_t METHOD_HEADING_NODE_RENDER = 1;
static const int32_t METHOD_HEADING_NODE_RELEASE_HANDLE = 2;

static const int32_t SERVICE_LOGGER = 7;
static const int32_t METHOD_LOGGER_LEVEL = 0;
static const int32_t METHOD_LOGGER_LOG = 1;
static const int32_t METHOD_LOGGER_FROM_CALLBACK = 2;
static const int32_t METHOD_LOGGER_RELEASE_HANDLE = 3;

static const int32_t SERVICE_MAMMAL = 8;
static const int32_t METHOD_MAMMAL_LEGS = 0;
static const int32_t METHOD_MAMMAL_SET_LEGS = 1;
static const int32_t METHOD_MAMMAL_RELEASE_HANDLE = 2;

static const int32_t SERVICE_MANAGED_FACTORY = 9;
static const int32_t METHOD_MANAGED_FACTORY_NEW = 0;
static const int32_t METHOD_MANAGED_FACTORY_MAKE = 1;
static const int32_t METHOD_MANAGED_FACTORY_RELEASE_HANDLE = 2;

static const int32_t SERVICE_MANAGED_VALUE = 10;
static const int32_t METHOD_MANAGED_VALUE_KIND = 0;
static const int32_t METHOD_MANAGED_VALUE_TAG = 1;

static const int32_t SERVICE_NAMED = 11;
static const int32_t METHOD_NAMED_NAMED_NAME = 0;
static const int32_t METHOD_NAMED_SET_NAMED_NAME = 1;
static const int32_t METHOD_NAMED_RELEASE_HANDLE = 2;

static const int32_t SERVICE_PRICED = 12;
static const int32_t METHOD_PRICED_PRICED_PRICE = 0;
static const int32_t METHOD_PRICED_SET_PRICED_PRICE = 1;
static const int32_t METHOD_PRICED_RELEASE_HANDLE = 2;

static const int32_t SERVICE_PRODUCT = 13;
static const int32_t METHOD_PRODUCT_NEW = 0;
static const int32_t METHOD_PRODUCT_SET_STOCK = 1;
static const int32_t METHOD_PRODUCT_STOCK = 2;
static const int32_t METHOD_PRODUCT_RELEASE_HANDLE = 3;

static const int32_t SERVICE_SCIENTIFIC_CALCULATOR = 14;
static const int32_t METHOD_SCIENTIFIC_CALCULATOR_POWER = 0;
static const int32_t METHOD_SCIENTIFIC_CALCULATOR_SQRT = 1;
static const int32_t METHOD_SCIENTIFIC_CALCULATOR_RELEASE_HANDLE = 2;

static const int32_t SERVICE_SHAPE = 15;
static const int32_t METHOD_SHAPE_AREA = 0;
static const int32_t METHOD_SHAPE_FROM_CALLBACK = 1;
static const int32_t METHOD_SHAPE_RELEASE_HANDLE = 2;

static const int32_t SERVICE_SHAPE_BOX = 16;
static const int32_t METHOD_SHAPE_BOX_NEW = 0;
static const int32_t METHOD_SHAPE_BOX_ADD = 1;
static const int32_t METHOD_SHAPE_BOX_GET = 2;
static const int32_t METHOD_SHAPE_BOX_SIZE = 3;
static const int32_t METHOD_SHAPE_BOX_RELEASE_HANDLE = 4;

static const int32_t SERVICE_SQUARE = 17;
static const int32_t METHOD_SQUARE_NEW = 0;
static const int32_t METHOD_SQUARE_AREA = 1;
static const int32_t METHOD_SQUARE_SIDE = 2;
static const int32_t METHOD_SQUARE_RELEASE_HANDLE = 3;

static const int32_t SERVICE_STATEFUL_COUNTER = 18;
static const int32_t METHOD_STATEFUL_COUNTER_NEW = 0;
static const int32_t METHOD_STATEFUL_COUNTER_NEW2 = 1;
static const int32_t METHOD_STATEFUL_COUNTER_ADD = 2;
static const int32_t METHOD_STATEFUL_COUNTER_CALL_COUNT = 3;
static const int32_t METHOD_STATEFUL_COUNTER_ID = 4;
static const int32_t METHOD_STATEFUL_COUNTER_RESET = 5;
static const int32_t METHOD_STATEFUL_COUNTER_SET_LABEL = 6;
static const int32_t METHOD_STATEFUL_COUNTER_TOTAL = 7;
static const int32_t METHOD_STATEFUL_COUNTER_GET_LABEL = 8;
static const int32_t METHOD_STATEFUL_COUNTER_RELEASE_HANDLE = 9;

static const int32_t SERVICE_TEXT_NODE = 19;
static const int32_t METHOD_TEXT_NODE_RENDER = 0;
static const int32_t METHOD_TEXT_NODE_FROM_CALLBACK = 1;
static const int32_t METHOD_TEXT_NODE_RELEASE_HANDLE = 2;

// ======================================
// Callback trampolines (C++ -> Go virtual dispatch)
// ======================================

class LoggerTrampoline : public calc::Logger {
public:
    explicit LoggerTrampoline(int32_t callback_id) : _callback_id(callback_id) {}
    ~LoggerTrampoline() override = default;
    int32_t level() const override {
        ProtoWriter _pw;
        int64_t _rc = wasmify_callback_invoke(_callback_id, 0, _pw.data_, _pw.size_);
        uintptr_t _resp_ptr = static_cast<uintptr_t>(static_cast<uint64_t>(_rc) >> 32);
        int32_t _resp_len = static_cast<int32_t>(_rc & 0xFFFFFFFFu);
        int32_t _result = {};
        if (_resp_ptr != 0) {
            ProtoReader _pr(reinterpret_cast<const void*>(_resp_ptr), _resp_len);
            while (_pr.next()) {
                if (_pr.field() == 1) {
                    _result = _pr.read_int32();
                } else {
                    _pr.skip();
                }
            }
            wasm_free(reinterpret_cast<void*>(_resp_ptr));
        }
        return _result;
    }
    void log(const std::string& message) override {
        ProtoWriter _pw;
        _pw.write_string(1, message);
        int64_t _rc = wasmify_callback_invoke(_callback_id, 1, _pw.data_, _pw.size_);
        uintptr_t _resp_ptr = static_cast<uintptr_t>(static_cast<uint64_t>(_rc) >> 32);
        int32_t _resp_len = static_cast<int32_t>(_rc & 0xFFFFFFFFu);
        if (_resp_ptr != 0) wasm_free(reinterpret_cast<void*>(_resp_ptr));
    }
private:
    int32_t _callback_id;
};

class ShapeTrampoline : public calc::Shape {
public:
    explicit ShapeTrampoline(int32_t callback_id) : _callback_id(callback_id) {}
    ~ShapeTrampoline() override = default;
    double area() const override {
        ProtoWriter _pw;
        int64_t _rc = wasmify_callback_invoke(_callback_id, 0, _pw.data_, _pw.size_);
        uintptr_t _resp_ptr = static_cast<uintptr_t>(static_cast<uint64_t>(_rc) >> 32);
        int32_t _resp_len = static_cast<int32_t>(_rc & 0xFFFFFFFFu);
        double _result = {};
        if (_resp_ptr != 0) {
            ProtoReader _pr(reinterpret_cast<const void*>(_resp_ptr), _resp_len);
            while (_pr.next()) {
                if (_pr.field() == 1) {
                    _result = _pr.read_double();
                } else {
                    _pr.skip();
                }
            }
            wasm_free(reinterpret_cast<void*>(_resp_ptr));
        }
        return _result;
    }
private:
    int32_t _callback_id;
};

class TextNodeTrampoline : public calc::TextNode {
public:
    explicit TextNodeTrampoline(int32_t callback_id) : _callback_id(callback_id) {}
    ~TextNodeTrampoline() override = default;
    std::string render() const override {
        ProtoWriter _pw;
        int64_t _rc = wasmify_callback_invoke(_callback_id, 0, _pw.data_, _pw.size_);
        uintptr_t _resp_ptr = static_cast<uintptr_t>(static_cast<uint64_t>(_rc) >> 32);
        int32_t _resp_len = static_cast<int32_t>(_rc & 0xFFFFFFFFu);
        std::string _result;
        if (_resp_ptr != 0) {
            ProtoReader _pr(reinterpret_cast<const void*>(_resp_ptr), _resp_len);
            while (_pr.next()) {
                if (_pr.field() == 1) _result = _pr.read_string();
                else _pr.skip();
            }
            wasm_free(reinterpret_cast<void*>(_resp_ptr));
        }
        return _result;
    }
private:
    int32_t _callback_id;
};

// Forward declarations of value-type submessage parsers.
static void parse_calc__Result(ProtoReader reader, calc::Result& out);

// Dispatch: simplelib_proto service (free functions)
static int64_t dispatch_simplelib_proto(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // add
        double a{};
        double b{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: a = reader.read_double(); break;
            case 2: b = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        double _result = calc::add(a, b);
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 1: { // aggregate_results
        std::vector<double> values{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: values.push_back(reader.read_double()); break;
            default: reader.skip(); break;
            }
        }
        auto _result = calc::aggregate_results(values);
        ProtoWriter _pw;
        for (const auto& _elem : _result) {
    ProtoWriter _subw;
    _subw.write_string(1, std::string(_elem.error_message)); _subw.write_bool(2, _elem.ok); _subw.write_double(3, _elem.value); 
    _pw.write_submessage(1, _subw);
    free(_subw.data_);
}
        return _pw.finish();
    }
    case 2: { // format_result
        calc::Result r{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: { ProtoReader _sub = reader.read_submessage(); parse_calc__Result(_sub, r); } break;
            default: reader.skip(); break;
            }
        }
        auto _result = calc::format_result(r);
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 3: { // run_with_logger
        uint64_t logger{};
        std::string message{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: logger = read_handle_ptr(reader); break;
            case 2: message = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        int32_t _result = calc::run_with_logger(reinterpret_cast<calc::Logger*>(logger), message);
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 4: { // version
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        int32_t _result = calc::version();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    default: return -1;
    }
}

// Dispatch: AnimalService
static int64_t dispatch_animal(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // set_species
        uint64_t _handle_ptr = 0;
        std::string s{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: s = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Animal*>(_handle_ptr);
        _self->set_species(s);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 1: { // species
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Animal*>(_handle_ptr);
        const auto& _result = _self->species();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Animal*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: CalculatorService
static int64_t dispatch_calculator(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (Calculator)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::Calculator();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // add_to_history
        uint64_t _handle_ptr = 0;
        double value{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: value = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Calculator*>(_handle_ptr);
        _self->add_to_history(value);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // clear_history
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Calculator*>(_handle_ptr);
        _self->clear_history();
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 3: { // compute
        uint64_t _handle_ptr = 0;
        calc::Operation op{};
        double a{};
        double b{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: /* value type Operation: submessage parser missing */ reader.skip(); break;
            case 3: a = reader.read_double(); break;
            case 4: b = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Calculator*>(_handle_ptr);
        double _result = _self->compute(op, a, b);
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 4: { // compute_safe
        uint64_t _handle_ptr = 0;
        calc::Operation op{};
        double a{};
        double b{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: /* value type Operation: submessage parser missing */ reader.skip(); break;
            case 3: a = reader.read_double(); break;
            case 4: b = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Calculator*>(_handle_ptr);
        auto _result = _self->compute_safe(op, a, b);
        ProtoWriter _pw;
        {
    ProtoWriter _subw;
    _subw.write_string(1, std::string(_result.error_message));
    _subw.write_bool(2, _result.ok);
    _subw.write_double(3, _result.value);
    _pw.write_submessage(1, _subw);
    free(_subw.data_);
}
        return _pw.finish();
    }
    case 5: { // get_history
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Calculator*>(_handle_ptr);
        auto _result = _self->get_history();
        ProtoWriter _pw;
        _pw.write_repeated_double(1, _result);
        return _pw.finish();
    }
    case 6: { // name
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Calculator*>(_handle_ptr);
        const auto& _result = _self->name();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 7: { // set_name
        uint64_t _handle_ptr = 0;
        std::string name{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: name = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Calculator*>(_handle_ptr);
        _self->set_name(name);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 8: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Calculator*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: CanineService
static int64_t dispatch_canine(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // breed
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Canine*>(_handle_ptr);
        const auto& _result = _self->breed();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 1: { // set_breed
        uint64_t _handle_ptr = 0;
        std::string b{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: b = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Canine*>(_handle_ptr);
        _self->set_breed(b);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Canine*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: CircleService
static int64_t dispatch_circle(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (Circle)
        double r{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: r = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::Circle(r);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // area
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Circle*>(_handle_ptr);
        double _result = _self->area();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 2: { // radius
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Circle*>(_handle_ptr);
        double _result = _self->radius();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 3: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Circle*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: DogService
static int64_t dispatch_dog(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (Dog)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::Dog();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // bark_volume
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Dog*>(_handle_ptr);
        int32_t _result = _self->bark_volume();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 2: { // set_bark_volume
        uint64_t _handle_ptr = 0;
        int32_t v{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: v = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Dog*>(_handle_ptr);
        _self->set_bark_volume(v);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 3: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Dog*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: HeadingNodeService
static int64_t dispatch_heading_node(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (HeadingNode)
        int32_t level{};
        std::string text{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: level = reader.read_int32(); break;
            case 2: text = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::HeadingNode(level, text);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // render
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::HeadingNode*>(_handle_ptr);
        auto _result = _self->render();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::HeadingNode*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: LoggerService
static int64_t dispatch_logger(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // level
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Logger*>(_handle_ptr);
        int32_t _result = _self->level();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 1: { // log
        uint64_t _handle_ptr = 0;
        std::string message{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: message = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Logger*>(_handle_ptr);
        _self->log(message);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // FromCallback
        ProtoReader _pr(req, req_len);
        int32_t _callback_id = 0;
        while (_pr.next()) {
            if (_pr.field() == 1) _callback_id = _pr.read_int32();
            else _pr.skip();
        }
        auto* _t = new LoggerTrampoline(_callback_id);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_t));
        return _pw.finish();
    }
    case 3: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Logger*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: MammalService
static int64_t dispatch_mammal(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // legs
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Mammal*>(_handle_ptr);
        int32_t _result = _self->legs();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 1: { // set_legs
        uint64_t _handle_ptr = 0;
        int32_t n{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: n = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Mammal*>(_handle_ptr);
        _self->set_legs(n);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Mammal*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ManagedFactoryService
static int64_t dispatch_managed_factory(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (ManagedFactory)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::ManagedFactory();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // make
        uint64_t _handle_ptr = 0;
        int32_t kind{};
        std::string tag{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: kind = reader.read_int32(); break;
            case 3: tag = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::ManagedFactory*>(_handle_ptr);
        auto _result = _self->make(kind, tag);
        ProtoWriter _pw;
        _pw.write_handle(1, reinterpret_cast<uint64_t>(_result));
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::ManagedFactory*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ManagedValueService
static int64_t dispatch_managed_value(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // kind
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ManagedValue*>(_handle_ptr);
        int32_t _result = _self->kind();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 1: { // tag
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ManagedValue*>(_handle_ptr);
        const auto& _result = _self->tag();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    default: return -1;
    }
}

// Dispatch: NamedService
static int64_t dispatch_named(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // named_name
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Named*>(_handle_ptr);
        const auto& _result = _self->named_name();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 1: { // set_named_name
        uint64_t _handle_ptr = 0;
        std::string n{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: n = reader.read_string(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Named*>(_handle_ptr);
        _self->set_named_name(n);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Named*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: PricedService
static int64_t dispatch_priced(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // priced_price
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Priced*>(_handle_ptr);
        double _result = _self->priced_price();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 1: { // set_priced_price
        uint64_t _handle_ptr = 0;
        double p{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: p = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Priced*>(_handle_ptr);
        _self->set_priced_price(p);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Priced*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ProductService
static int64_t dispatch_product(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (Product)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::Product();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // set_stock
        uint64_t _handle_ptr = 0;
        int32_t s{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: s = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::Product*>(_handle_ptr);
        _self->set_stock(s);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // stock
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Product*>(_handle_ptr);
        int32_t _result = _self->stock();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 3: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Product*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ScientificCalculatorService
static int64_t dispatch_scientific_calculator(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // power
        uint64_t _handle_ptr = 0;
        double base{};
        double exp{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: base = reader.read_double(); break;
            case 3: exp = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ScientificCalculator*>(_handle_ptr);
        double _result = _self->power(base, exp);
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 1: { // sqrt
        uint64_t _handle_ptr = 0;
        double value{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: value = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ScientificCalculator*>(_handle_ptr);
        double _result = _self->sqrt(value);
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::ScientificCalculator*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ShapeService
static int64_t dispatch_shape(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // area
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Shape*>(_handle_ptr);
        double _result = _self->area();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 1: { // FromCallback
        ProtoReader _pr(req, req_len);
        int32_t _callback_id = 0;
        while (_pr.next()) {
            if (_pr.field() == 1) _callback_id = _pr.read_int32();
            else _pr.skip();
        }
        auto* _t = new ShapeTrampoline(_callback_id);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_t));
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Shape*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: ShapeBoxService
static int64_t dispatch_shape_box(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (ShapeBox)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::ShapeBox();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // add
        uint64_t _handle_ptr = 0;
        uint64_t s{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: s = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::ShapeBox*>(_handle_ptr);
        _self->add(reinterpret_cast<calc::Shape*>(s));
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 2: { // get
        uint64_t _handle_ptr = 0;
        int32_t i{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: i = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ShapeBox*>(_handle_ptr);
        auto _result = _self->get(i);
        ProtoWriter _pw;
        _pw.write_handle(1, reinterpret_cast<uint64_t>(_result));
        return _pw.finish();
    }
    case 3: { // size
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::ShapeBox*>(_handle_ptr);
        int32_t _result = _self->size();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 4: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::ShapeBox*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: SquareService
static int64_t dispatch_square(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (Square)
        double s{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: s = reader.read_double(); break;
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::Square(s);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // area
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Square*>(_handle_ptr);
        double _result = _self->area();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 2: { // side
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::Square*>(_handle_ptr);
        double _result = _self->side();
        ProtoWriter _pw;
        _pw.write_double(1, _result);
        return _pw.finish();
    }
    case 3: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::Square*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: StatefulCounterService
static int64_t dispatch_stateful_counter(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // New (StatefulCounter)
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::StatefulCounter();
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 1: { // New2 (StatefulCounter2)
        int32_t initial_id{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: initial_id = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        auto* _obj = new calc::StatefulCounter(initial_id);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_obj));
        return _pw.finish();
    }
    case 2: { // add
        uint64_t _handle_ptr = 0;
        int32_t delta{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: delta = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::StatefulCounter*>(_handle_ptr);
        _self->add(delta);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 3: { // call_count
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::StatefulCounter*>(_handle_ptr);
        int32_t _result = _self->call_count();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 4: { // id
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::StatefulCounter*>(_handle_ptr);
        int32_t _result = _self->id();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 5: { // reset
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::StatefulCounter*>(_handle_ptr);
        _self->reset();
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 6: { // set_label
        uint64_t _handle_ptr = 0;
        int32_t new_label{};
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            case 2: new_label = reader.read_int32(); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<calc::StatefulCounter*>(_handle_ptr);
        _self->set_label(new_label);
        ProtoWriter _pw;
        return _pw.finish();
    }
    case 7: { // total
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::StatefulCounter*>(_handle_ptr);
        int32_t _result = _self->total();
        ProtoWriter _pw;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 8: { // GetLabel
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::StatefulCounter*>(_handle_ptr);
        ProtoWriter _pw;
        auto _result = _self->label;
        _pw.write_int32(1, _result);
        return _pw.finish();
    }
    case 9: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::StatefulCounter*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// Dispatch: TextNodeService
static int64_t dispatch_text_node(int32_t method_id, void* req, int32_t req_len) {
    switch (method_id) {
    case 0: { // render
        uint64_t _handle_ptr = 0;
        ProtoReader reader(req, req_len);
        while (reader.has_data() && reader.next()) {
            switch (reader.field()) {
            case 1: _handle_ptr = read_handle_ptr(reader); break;
            default: reader.skip(); break;
            }
        }
        if (_handle_ptr == 0) {
            ProtoWriter _pw;
            _pw.write_error("null handle");
            return _pw.finish();
        }
        auto* _self = reinterpret_cast<const calc::TextNode*>(_handle_ptr);
        auto _result = _self->render();
        ProtoWriter _pw;
        _pw.write_string(1, std::string(_result));
        return _pw.finish();
    }
    case 1: { // FromCallback
        ProtoReader _pr(req, req_len);
        int32_t _callback_id = 0;
        while (_pr.next()) {
            if (_pr.field() == 1) _callback_id = _pr.read_int32();
            else _pr.skip();
        }
        auto* _t = new TextNodeTrampoline(_callback_id);
        ProtoWriter _pw;
        _pw.write_uint64(1, reinterpret_cast<uint64_t>(_t));
        return _pw.finish();
    }
    case 2: { // Free
        uint64_t _handle_ptr = read_handle_direct(req, req_len);
        if (_handle_ptr != 0) {
            delete reinterpret_cast<const calc::TextNode*>(_handle_ptr);
        }
        return encode_result(nullptr, 0);
    }
    default: return -1;
    }
}

// ======================================
// Value-type submessage parsers
// ======================================

static void parse_calc__Result(ProtoReader reader, calc::Result& out) {
    while (reader.has_data() && reader.next()) {
        switch (reader.field()) {
        case 1: {
            out.error_message = reader.read_string();
            break;
        }
        case 2: {
            out.ok = reader.read_bool();
            break;
        }
        case 3: {
            out.value = reader.read_double();
            break;
        }
        default: reader.skip(); break;
        }
    }
}

// ======================================
// Main dispatcher
// ======================================

#include <typeinfo>
#include <cxxabi.h>

static int64_t _wasmify_get_type_name(void* req, int32_t req_len) {
    ProtoReader reader(req, req_len);
    uint64_t ptr = 0;
    while (reader.has_data() && reader.next()) {
        if (reader.field() == 1) ptr = reader.read_uint64();
        else reader.skip();
    }
    if (ptr == 0) { ProtoWriter pw; pw.write_error("null handle"); return pw.finish(); }
    // Use the first abstract base pointer to get runtime type info.
    // We cast to void* and use a helper that tries known base classes.
    if (auto* p = reinterpret_cast<calc::Logger*>(ptr)) {
        int status = 0;
        const char* mangled = typeid(*p).name();
        char* demangled = abi::__cxa_demangle(mangled, nullptr, nullptr, &status);
        ProtoWriter pw;
        if (status == 0 && demangled) {
            pw.write_string(1, std::string(demangled));
            free(demangled);
        } else {
            pw.write_string(1, std::string(mangled));
        }
        return pw.finish();
    } else if (auto* p = reinterpret_cast<calc::Shape*>(ptr)) {
        int status = 0;
        const char* mangled = typeid(*p).name();
        char* demangled = abi::__cxa_demangle(mangled, nullptr, nullptr, &status);
        ProtoWriter pw;
        if (status == 0 && demangled) {
            pw.write_string(1, std::string(demangled));
            free(demangled);
        } else {
            pw.write_string(1, std::string(mangled));
        }
        return pw.finish();
    } else if (auto* p = reinterpret_cast<calc::TextNode*>(ptr)) {
        int status = 0;
        const char* mangled = typeid(*p).name();
        char* demangled = abi::__cxa_demangle(mangled, nullptr, nullptr, &status);
        ProtoWriter pw;
        if (status == 0 && demangled) {
            pw.write_string(1, std::string(demangled));
            free(demangled);
        } else {
            pw.write_string(1, std::string(mangled));
        }
        return pw.finish();
    }
    ProtoWriter pw;
    pw.write_error("unknown type");
    return pw.finish();
}

typedef int64_t (*dispatch_fn_t)(int32_t method_id, void* req, int32_t req_len);

static const dispatch_fn_t _wasmify_dispatch_fns[20] = {
    /* 0 */ dispatch_simplelib_proto,
    /* 1 */ dispatch_animal,
    /* 2 */ dispatch_calculator,
    /* 3 */ dispatch_canine,
    /* 4 */ dispatch_circle,
    /* 5 */ dispatch_dog,
    /* 6 */ dispatch_heading_node,
    /* 7 */ dispatch_logger,
    /* 8 */ dispatch_mammal,
    /* 9 */ dispatch_managed_factory,
    /* 10 */ dispatch_managed_value,
    /* 11 */ dispatch_named,
    /* 12 */ dispatch_priced,
    /* 13 */ dispatch_product,
    /* 14 */ dispatch_scientific_calculator,
    /* 15 */ dispatch_shape,
    /* 16 */ dispatch_shape_box,
    /* 17 */ dispatch_square,
    /* 18 */ dispatch_stateful_counter,
    /* 19 */ dispatch_text_node,
};

WASM_EXPORT(wasm_invoke)
int64_t wasm_invoke(int32_t service_id, int32_t method_id, void* req, int32_t req_len) {
    // service_id == -1: get runtime type name for abstract dispatch
    if (service_id == -1) return _wasmify_get_type_name(req, req_len);
    if (service_id < 0 || service_id >= 20) return -1;
    return _wasmify_dispatch_fns[service_id](method_id, req, req_len);
}

WASM_EXPORT(wasm_init)
int32_t wasm_init() { return 0; }

WASM_EXPORT(wasm_shutdown)
void wasm_shutdown() { }

} // extern "C"
