package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/goccy/wasmify/internal/apispec"
	"github.com/goccy/wasmify/internal/apispec/clangast"
	"github.com/goccy/wasmify/internal/arch"
	"github.com/goccy/wasmify/internal/bazelcapture"
	"github.com/goccy/wasmify/internal/binaryen"
	"github.com/goccy/wasmify/internal/buildjson"
	"github.com/goccy/wasmify/internal/cache"
	"github.com/goccy/wasmify/internal/protogen"
	"github.com/goccy/wasmify/internal/scaffold"
	"github.com/goccy/wasmify/internal/skill"
	"github.com/goccy/wasmify/internal/state"
	"github.com/goccy/wasmify/internal/tools"
	"github.com/goccy/wasmify/internal/wasmbuild"
	"github.com/goccy/wasmify/internal/wrapper"
)

func main() {
	// Handle wrapper mode: if invoked as a compiler symlink, act as wrapper
	if wrapper.IsWrapperInvocation() {
		if err := wrapper.RunAsWrapper(); err != nil {
			fmt.Fprintf(os.Stderr, "wasmify wrapper error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	code := dispatch(os.Args[1:])
	if code != 0 {
		os.Exit(code)
	}
}

// dispatch routes subcommand arguments to the appropriate handler. Returns
// the process exit code (0 on success).
func dispatch(argv []string) int {
	// --non-interactive is global. Strip it up front so every
	// subcommand gets the clean argv but the rest of the process knows
	// to fail-fast on any prompt path.
	argv = stripNonInteractiveFlag(argv)

	if len(argv) < 1 {
		printUsage()
		return 1
	}

	subcmd := argv[0]
	args := argv[1:]

	var err error
	switch subcmd {
	case "init":
		err = cmdInit(args)
	case "status":
		err = cmdStatus(args)
	case "save-arch":
		err = cmdSaveArch(args)
	case "classify":
		err = cmdClassify(args)
	case "build":
		err = cmdBuild(args)
	case "generate-build":
		err = cmdGenerateBuild(args)
	case "validate-build":
		err = cmdValidateBuild(args)
	case "install-sdk":
		err = cmdInstallSDK(args)
	case "ensure-tools":
		err = cmdEnsureTools(args)
	case "wasm-build":
		err = cmdWasmBuild(args)
	case "parse-headers":
		err = cmdParseHeaders(args)
	case "gen-proto":
		err = cmdGenProto(args)
	case "optimize":
		err = cmdOptimize(args)
	case "update":
		err = cmdUpdate(args)
	case "help", "-h", "--help":
		printUsage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", subcmd)
		printUsage()
		return 1
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	return 0
}

func printUsage() {
	fmt.Fprintf(os.Stderr, `Usage: wasmify [--non-interactive] <command> [arguments]

Only 'init' takes a project path. Every other command discovers the
project by reading wasmify.json in the current working directory — cd into
the output dir first, then run the command.

Global flags:
  --non-interactive   Fail fast on any prompt path. Equivalent to setting
                      WASMIFY_NON_INTERACTIVE=1. Skip / stub-header
                      decisions must be declared in wasmify.json's skip
                      section under this mode.

Commands:
  init <project-path> [--output-dir <dir>]
                                   Initialize wasmify.json + scaffold
  status                           Show current analysis status and cache state
  save-arch                        Save analyzer output into wasmify.json (reads JSON from stdin)
  classify [--target <name>]       Select build target (interactively or via flag)
  build [-- <cmd>]                 Capture build commands (optional explicit cmd)
  generate-build                   Generate build.json from captured build log
  validate-build                   Replay build.json to validate
  ensure-tools [--skip-wasi-sdk]   Install tools listed in arch.json (CI-friendly)
  install-sdk [<dir>|--path <dir>] Install wasi-sdk (standalone, no config needed)
  wasm-build [--wasi-sdk <p>] [--dry-run] [--output <dir>] [--no-cache]
             [--optimize]
                                   Transform + execute build for wasm32-wasi.
                                   Requires gen-proto to have produced the
                                   bridge sources; fails otherwise.
                                   --optimize chains 'wasmify optimize' right
                                   after the link succeeds.
  parse-headers [--header <f>] [--clang <bin>]
                                   Parse public headers → api-spec.json
  gen-proto [--package <name>] [--bridge-config <file>]
                                   Generate .proto and C++ bridge.
                                   Go bindings are generated by invoking
                                   protoc-gen-wasmify-go via buf.
  optimize [--input <wasm>] [--output <wasm>] [--verbose]
                                   Shrink the project's wasm via Binaryen
                                   wasm-opt -Oz + strip passes. Auto-installs
                                   Binaryen on first use; rewrites the
                                   artefact in-place by default.
  update                           Detect upstream changes + re-run affected phases
  help                             Show this help message
`)
}

// resolveProject resolves the project path and returns (absPath, dataDir).
// It is a thin wrapper over resolveOutputDir with no --output-dir, so the
// current working directory becomes the output dir and dataDir is
// <cwd>/.wasmify.
func resolveProject(projectPath string) (string, string, error) {
	absPath, dataDir, _, err := resolveOutputDir(projectPath, "")
	return absPath, dataDir, err
}

// loadProjectFromConfig discovers the upstream project from wasmify.json in
// the current working directory. Every subcommand except `init` uses this
// instead of taking a `<project-path>` argument — users `cd` into the
// output dir (the one that holds wasmify.json / arch.json / build.json)
// and then run commands without repeating the path.
//
// Returns (absProjectPath, dataDir, outDir, error). outDir is cwd; dataDir
// is <cwd>/.wasmify.
func loadProjectFromConfig() (string, string, string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", "", "", fmt.Errorf("failed to get cwd: %w", err)
	}
	s, err := state.Load(cwd)
	if err != nil {
		return "", "", "", fmt.Errorf("failed to read wasmify.json: %w", err)
	}
	if s == nil {
		return "", "", "", fmt.Errorf("wasmify.json not found in %s. Run 'wasmify init <project-path>' here first", cwd)
	}
	absPath := s.UpstreamAbs(cwd)
	info, err := os.Stat(absPath)
	if err != nil || !info.IsDir() {
		return "", "", "", fmt.Errorf("upstream project path %q resolved to %q, which is not a directory", s.Upstream.Path, absPath)
	}
	dataDir := filepath.Join(cwd, ".wasmify")
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return "", "", "", fmt.Errorf("failed to create .wasmify dir: %w", err)
	}
	return absPath, dataDir, cwd, nil
}

// upstreamPathFor returns the value to record in wasmify.json's upstream.path
// field. Prefers a relative path when the project lives under outDir (common
// submodule layout) so the committed wasmify.json stays portable; falls back
// to the absolute path otherwise.
func upstreamPathFor(absProject, outDir string) string {
	rel, err := filepath.Rel(outDir, absProject)
	if err != nil {
		return absProject
	}
	// Reject rel paths that escape outDir ("..") — those signal the
	// project is elsewhere on disk and an absolute path is clearer.
	if rel == "." || rel == "" {
		return "."
	}
	if len(rel) >= 2 && rel[:2] == ".." {
		return absProject
	}
	if filepath.IsAbs(rel) {
		return absProject
	}
	return "./" + rel
}

// resolveOutputDir resolves the project path, data directory, and output
// directory for a command invocation.
//
// Layout (single mode since XDG per-project dirs were retired):
//   - outDir = --output-dir flag value, or the current working directory
//     when the flag is absent. Holds arch.json, build.json, proto/, bridge/,
//     and anything else meant to be committed to git.
//   - dataDir = <outDir>/.wasmify. Holds per-project build artefacts: the
//     .o/.a cache, cache.json, wasm-build intermediate state. Listed in
//     .gitignore by the init scaffold.
//   - wasi-sdk stays at the shared XDG path (~/.config/wasmify/bin/wasi-sdk)
//     so projects do not re-download the ~500MB tarball each.
//
// Returns (absProjectPath, dataDir, outDir, error).
func resolveOutputDir(projectPath, outputDir string) (string, string, string, error) {
	absPath, err := filepath.Abs(projectPath)
	if err != nil {
		return "", "", "", fmt.Errorf("failed to resolve path: %w", err)
	}
	info, err := os.Stat(absPath)
	if err != nil || !info.IsDir() {
		return "", "", "", fmt.Errorf("not a valid directory: %s", absPath)
	}
	if outputDir == "" {
		cwd, cerr := os.Getwd()
		if cerr != nil {
			return "", "", "", fmt.Errorf("failed to get cwd: %w", cerr)
		}
		outputDir = cwd
	}
	absOut, err := filepath.Abs(outputDir)
	if err != nil {
		return "", "", "", fmt.Errorf("failed to resolve output-dir: %w", err)
	}
	if err := os.MkdirAll(absOut, 0o755); err != nil {
		return "", "", "", fmt.Errorf("failed to create output-dir: %w", err)
	}
	dataDir := filepath.Join(absOut, ".wasmify")
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return "", "", "", fmt.Errorf("failed to create .wasmify dir: %w", err)
	}
	return absPath, dataDir, absOut, nil
}

// parseOutputDirFlag extracts --output-dir from args, returning the value and remaining args.
func parseOutputDirFlag(args []string) (outputDir string, rest []string) {
	for i := 0; i < len(args); i++ {
		if args[i] == "--output-dir" && i+1 < len(args) {
			outputDir = args[i+1]
			i++ // skip value
			continue
		}
		rest = append(rest, args[i])
	}
	return
}

// deriveBuildCommand constructs a build command from arch.json's selection and build_commands.
// For Bazel: uses the selected target's build_target with the build command template.
// For other build systems: uses the build command as-is.
func deriveBuildCommand(projectPath, outputDir string) (string, error) {
	_, dataDir, outDir, err := resolveOutputDir(projectPath, outputDir)
	if err != nil {
		return "", err
	}
	a, err := arch.Load(outDir)
	if err != nil {
		return "", err
	}
	if a == nil {
		if a, err = arch.Load(dataDir); err != nil {
			return "", err
		}
	}
	if a == nil {
		return "", fmt.Errorf("project metadata not found in wasmify.json. Run 'wasmify save-arch' first")
	}
	if a.Selection == nil {
		return "", fmt.Errorf("no target selected. Run 'wasmify classify' first")
	}
	if a.Commands.Build == "" {
		return "", fmt.Errorf("no build command in arch.json")
	}

	// Collect every selected target's build_target so multi-select
	// (analyzer + sql_formatter) hits one bazel build invocation.
	wanted := map[string]bool{}
	for _, n := range a.Selection.Names() {
		wanted[n] = true
	}
	var buildTargets []string
	for _, t := range a.Targets {
		if wanted[t.Name] && t.BuildTarget != "" {
			buildTargets = append(buildTargets, t.BuildTarget)
		}
	}

	cmd := a.Commands.Build
	if len(buildTargets) > 0 {
		// Common pattern: "bazel build" → "bazel build //pkg:t1 //pkg:t2".
		cmd = cmd + " " + strings.Join(buildTargets, " ")
	}

	return cmd, nil
}

func cmdInit(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: wasmify init <project-path> [--output-dir <dir>] [--force]")
	}

	projectPath := args[0]
	outputDir := ""
	force := false
	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "--output-dir":
			if i+1 < len(args) {
				i++
				outputDir = args[i]
			}
		case "--force":
			force = true
		}
	}

	absPath, dataDir, outDir, err := resolveOutputDir(projectPath, outputDir)
	if err != nil {
		return err
	}
	result := map[string]string{
		"project_path": absPath,
		"data_dir":     dataDir,
		"output_dir":   outDir,
	}
	// Initialize wasmify.json in the output dir. Store the upstream path
	// relative to outDir when possible, so the committed file stays portable
	// (a cloned repo on CI resolves it without developer-machine path leak).
	s := state.New(upstreamPathFor(absPath, outDir))
	commit, _ := gitHeadCommit(absPath)
	branch, _ := gitCurrentBranch(absPath)
	s.UpdateUpstream(commit, branch)
	if err := state.Save(outDir, s); err != nil {
		return fmt.Errorf("failed to save wasmify.json: %w", err)
	}
	if err := scaffold.Generate(outDir, absPath); err != nil {
		return fmt.Errorf("failed to generate scaffold: %w", err)
	}
	fmt.Fprintf(os.Stderr, "[init] Generated scaffold in %s\n", outDir)

	// Install the SKILL.md alongside the scaffold.
	skillPath, err := skill.Install(outDir, force)
	if err != nil {
		return err
	}
	result["skill_path"] = skillPath
	fmt.Fprintf(os.Stderr, "[init] Skill installed at %s\n", skillPath)

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

func cmdStatus(args []string) error {
	_ = args
	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	c, err := cache.Load(dataDir)
	if err != nil {
		return err
	}

	// arch.json and build.json may live in outDir (external mode) or dataDir.
	a, err := arch.Load(outDir)
	if err != nil {
		return err
	}
	if a == nil {
		if a, err = arch.Load(dataDir); err != nil {
			return err
		}
	}

	b, err := buildjson.Load(outDir)
	if err != nil {
		return err
	}
	if b == nil {
		if b, err = buildjson.Load(dataDir); err != nil {
			return err
		}
	}

	status := map[string]any{
		"data_dir": dataDir,
	}
	if c != nil {
		status["cache"] = c
	} else {
		status["cache"] = nil
	}
	if a != nil {
		status["arch"] = a
	} else {
		status["arch"] = nil
	}
	if b != nil {
		status["build_json"] = map[string]any{
			"steps_count": len(b.Steps),
			"captured_at": b.CapturedAt,
		}
	} else {
		status["build_json"] = nil
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(status)
}

func cmdSaveArch(args []string) error {
	_ = args
	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("failed to read stdin: %w", err)
	}

	var a arch.Arch
	if err := json.Unmarshal(data, &a); err != nil {
		return fmt.Errorf("invalid JSON: %w", err)
	}

	// Reject absolute paths. arch.json always lives in the output dir and is
	// committed to git, so baked-in developer paths would leak $HOME and
	// break on CI.
	if filepath.IsAbs(a.Project.RootDir) {
		return fmt.Errorf("project.root_dir must be a relative path (got %q). arch.json is committed to git, so paths must be portable", a.Project.RootDir)
	}
	for _, t := range a.Targets {
		for _, d := range t.SourceDirs {
			if filepath.IsAbs(d) {
				return fmt.Errorf("targets[].source_dirs must be relative paths (got %q)", d)
			}
		}
		for _, h := range t.PublicHeaders {
			if filepath.IsAbs(h) {
				return fmt.Errorf("targets[].public_headers must be relative paths (got %q)", h)
			}
		}
	}
	for _, f := range a.BuildSystem.Files {
		if filepath.IsAbs(f) {
			return fmt.Errorf("build_system.files must be relative paths (got %q)", f)
		}
	}

	// Validate required fields
	var missing []string
	if a.Project.Name == "" {
		missing = append(missing, "project.name")
	}
	if a.Project.RootDir == "" {
		missing = append(missing, "project.root_dir")
	}
	if a.Project.Language == "" {
		missing = append(missing, "project.language")
	}
	if a.BuildSystem.Type == "" {
		missing = append(missing, "build_system.type")
	}
	if len(a.BuildSystem.Files) == 0 {
		missing = append(missing, "build_system.files")
	}
	if len(a.Targets) == 0 {
		missing = append(missing, "targets")
	}
	if a.Commands.Build == "" {
		missing = append(missing, "build_commands.build")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required fields: %s", strings.Join(missing, ", "))
	}

	a.Version = "1.0"
	if a.AnalyzedAt == "" {
		a.AnalyzedAt = time.Now().UTC().Format(time.RFC3339)
	}

	// Persist analyzer-output sections into wasmify.json. (The historical
	// arch.json was retired in favor of a unified wasmify.json that
	// holds project metadata + bridge config + skip rules in one file.)
	if err := arch.Save(outDir, &a); err != nil {
		return err
	}

	// Cache state is always kept in the XDG data dir — it is not meant to be
	// checked into git.
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseAnalyze)
	_ = c.Save(dataDir)

	fmt.Printf("project metadata saved to %s\n", filepath.Join(outDir, state.Filename()))
	return nil
}

func cmdClassify(args []string) error {
	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	a, err := arch.Load(outDir)
	if err != nil {
		return err
	}
	if a == nil {
		if a, err = arch.Load(dataDir); err != nil {
			return err
		}
	}
	if a == nil {
		return fmt.Errorf("project metadata not found in wasmify.json. Run 'wasmify save-arch' first")
	}
	if len(a.Targets) == 0 {
		return fmt.Errorf("no targets found in arch.json")
	}

	// Check for --target flag (non-interactive mode). The flag may
	// repeat to select multiple targets, or accept a comma-separated
	// list inline (`--target analyzer,sql_formatter`). Both forms
	// merge into one wasm; downstream phases see the union of the
	// targets' compile units.
	var targetNames []string
	for i := 0; i < len(args); i++ {
		if args[i] == "--target" && i+1 < len(args) {
			i++
			for _, name := range strings.Split(args[i], ",") {
				name = strings.TrimSpace(name)
				if name != "" {
					targetNames = append(targetNames, name)
				}
			}
		}
	}

	if len(targetNames) == 0 {
		if globalNonInteractive {
			return fmt.Errorf("non-interactive mode: pass --target <name>[,<name>...] to classify")
		}
		// Interactive mode: show targets and prompt. Accepts a single
		// index or a comma-separated list of indices (e.g. "1,4") so
		// the user can co-select multiple libraries that share one
		// wasm artefact.
		fmt.Fprintf(os.Stderr, "Available targets:\n\n")
		for i, t := range a.Targets {
			fmt.Fprintf(os.Stderr, "  [%d] %s (%s)\n", i+1, t.Name, t.Type)
			if t.Description != "" {
				fmt.Fprintf(os.Stderr, "      %s\n", t.Description)
			}
			if t.BuildTarget != "" {
				fmt.Fprintf(os.Stderr, "      build target: %s\n", t.BuildTarget)
			}
			if len(t.SourceDirs) > 0 {
				fmt.Fprintf(os.Stderr, "      source dirs: %s\n", strings.Join(t.SourceDirs, ", "))
			}
		}
		fmt.Fprintf(os.Stderr, "\nSelect target(s) [1-%d, comma-separated for multiple]: ", len(a.Targets))

		var raw string
		if _, err := fmt.Scan(&raw); err != nil {
			return fmt.Errorf("failed to read input: %w", err)
		}
		for _, tok := range strings.Split(raw, ",") {
			tok = strings.TrimSpace(tok)
			if tok == "" {
				continue
			}
			var choice int
			if _, err := fmt.Sscanf(tok, "%d", &choice); err != nil {
				return fmt.Errorf("invalid choice %q: %w", tok, err)
			}
			if choice < 1 || choice > len(a.Targets) {
				return fmt.Errorf("invalid choice: %d", choice)
			}
			targetNames = append(targetNames, a.Targets[choice-1].Name)
		}
		if len(targetNames) == 0 {
			return fmt.Errorf("no target selected")
		}
	}

	// Resolve every name to its arch.Target entry, refusing unknown
	// names up front. All selected targets must share a build_type
	// so the downstream link step (LinkLibrary vs. an executable
	// driver) is unambiguous.
	selected := make([]*arch.Target, 0, len(targetNames))
	seen := map[string]bool{}
	var buildType string
	for _, name := range targetNames {
		if seen[name] {
			continue
		}
		seen[name] = true
		var t *arch.Target
		for i := range a.Targets {
			if a.Targets[i].Name == name {
				t = &a.Targets[i]
				break
			}
		}
		if t == nil {
			return fmt.Errorf("target %q not found in arch.json", name)
		}
		if buildType == "" {
			buildType = t.Type
		} else if buildType != t.Type {
			return fmt.Errorf("cannot mix build_types: %q is %q but a previously selected target is %q", t.Name, t.Type, buildType)
		}
		selected = append(selected, t)
	}

	names := make([]string, len(selected))
	for i, t := range selected {
		names[i] = t.Name
	}

	// Save selection. Writes back to the same directory wasmify.json was
	// loaded from: outDir in external-output-dir mode, dataDir (XDG)
	// otherwise.
	a.Selection = &arch.Selection{
		TargetNames: names,
		BuildType:   buildType,
	}
	saveDir := outDir
	if _, statErr := os.Stat(filepath.Join(outDir, state.Filename())); statErr != nil {
		saveDir = dataDir
	}
	if err := arch.Save(saveDir, a); err != nil {
		return err
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseClassify)
	_ = c.Save(dataDir)

	fmt.Fprintf(os.Stderr, "Selected target(s): %s (%s)\n", strings.Join(names, ", "), buildType)
	return nil
}

func cmdBuild(args []string) error {
	// Split args at "--" so everything after it is the verbatim build command.
	var buildCmd []string
	for i, a := range args {
		if a == "--" {
			buildCmd = args[i+1:]
			break
		}
	}

	absPath, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	// If no explicit build command, derive from arch.json selection
	if len(buildCmd) == 0 {
		cmd, err := deriveBuildCommand(absPath, outDir)
		if err != nil {
			return fmt.Errorf("no build command specified and cannot derive from arch.json: %w\nusage: wasmify build [-- <build-command...>]", err)
		}
		buildCmd = []string{cmd}
	}

	// Bazel hermetic C++ toolchains ignore CC/CXX env vars, so PATH-based
	// compiler wrappers never get invoked. For Bazel projects we run the real
	// build (to produce generated files) and then extract the action graph
	// via `bazel aquery`, which is equivalent to what the wrappers would have
	// captured.
	if isBazelProject(outDir, dataDir) {
		return runBazelBuild(absPath, outDir, dataDir, buildCmd)
	}

	// Setup wrappers
	wrapperDir, logFile, cleanup, err := wrapper.Setup()
	if err != nil {
		return fmt.Errorf("failed to setup wrappers: %w", err)
	}
	defer cleanup()

	env, err := wrapper.EnvForBuild(wrapperDir, logFile, os.Environ())
	if err != nil {
		return fmt.Errorf("failed to prepare build environment: %w", err)
	}

	// Prepend wrapper directory to PATH
	for i, e := range env {
		if strings.HasPrefix(e, "PATH=") {
			env[i] = fmt.Sprintf("PATH=%s:%s", wrapperDir, strings.TrimPrefix(e, "PATH="))
			break
		}
	}

	// Run build command
	cmdStr := strings.Join(buildCmd, " ")
	fmt.Fprintf(os.Stderr, "[wasmify] Building in %s\n", absPath)
	fmt.Fprintf(os.Stderr, "[wasmify] Command: %s\n", cmdStr)

	cmd := exec.Command("sh", "-c", cmdStr)
	cmd.Dir = absPath
	cmd.Env = env
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}

	// Copy log file to data directory
	logData, err := os.ReadFile(logFile)
	if err != nil {
		return fmt.Errorf("failed to read build log: %w", err)
	}
	logDst := filepath.Join(dataDir, "build.log")
	if err := os.WriteFile(logDst, logData, 0o644); err != nil {
		return fmt.Errorf("failed to save build log: %w", err)
	}

	// Count captured entries
	entries, _ := wrapper.ParseLog(logFile)

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	if !c.IsCompleted(cache.PhasePrepare) {
		c.CompletePhase(cache.PhasePrepare)
	}
	c.CompletePhase(cache.PhaseBuild)
	_ = c.Save(dataDir)

	fmt.Printf("Build completed. Captured %d tool invocations.\n", len(entries))
	return nil
}

// isBazelProject returns true when the project's arch.json records a Bazel
// build system. Checks outDir first (external mode) then dataDir (XDG).
func isBazelProject(outDir, dataDir string) bool {
	a, _ := arch.Load(outDir)
	if a == nil {
		a, _ = arch.Load(dataDir)
	}
	return a != nil && a.BuildSystem.Type == "bazel"
}

// runBazelBuild executes `bazel build <target>` to produce generated files,
// then extracts the action graph via `bazel aquery` and writes build.log in
// the same JSON Lines format as the compiler-wrapper path. The user's build
// command is parsed to split "bazel [flags]" from "<target>".
//
// If the bazel build fails, its stderr has already streamed to the user via
// the child process, and the non-zero exit is returned verbatim so the Agent
// can act on it.
func runBazelBuild(absPath, outDir, dataDir string, buildCmd []string) error {
	flags, targets := splitBazelBuildCommand(buildCmd)
	if len(targets) == 0 {
		return fmt.Errorf("cannot determine bazel target from build command: %v", buildCmd)
	}
	fmt.Fprintf(os.Stderr, "[wasmify] Bazel project detected — running real build, then aquery.\n")
	fmt.Fprintf(os.Stderr, "[wasmify] workdir: %s\n", absPath)
	fmt.Fprintf(os.Stderr, "[wasmify] targets: %v\n", targets)
	if len(flags) > 0 {
		fmt.Fprintf(os.Stderr, "[wasmify] flags:   %v\n", flags)
	}

	entries, err := bazelcapture.Capture(absPath, outDir, targets, flags)
	if err != nil {
		return err
	}

	// Write build.log in the same JSON Lines format the wrapper produces so
	// downstream generate-build / wasm-build treat it identically.
	logDst := filepath.Join(dataDir, "build.log")
	f, err := os.Create(logDst)
	if err != nil {
		return fmt.Errorf("failed to create build.log: %w", err)
	}
	defer func() { _ = f.Close() }()
	enc := json.NewEncoder(f)
	for _, e := range entries {
		if err := enc.Encode(e); err != nil {
			return fmt.Errorf("failed to write build.log: %w", err)
		}
	}

	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	if !c.IsCompleted(cache.PhasePrepare) {
		c.CompletePhase(cache.PhasePrepare)
	}
	c.CompletePhase(cache.PhaseBuild)
	_ = c.Save(dataDir)

	fmt.Printf("Build completed. Captured %d tool invocations (via bazel aquery).\n", len(entries))
	return nil
}

// splitBazelBuildCommand separates bazel flags (like `-c opt`) from
// the Bazel label targets. Multiple targets are supported and the
// downstream aquery merges their dependency graphs into one
// build.log. Accepts the build command as either a single shell
// string or already-split argv.
//
// Example: ["bazel build -c opt //googlesql/public:analyzer //googlesql/public:sql_formatter"]
//   → flags=["-c", "opt"], targets=["//googlesql/public:analyzer", "//googlesql/public:sql_formatter"]
func splitBazelBuildCommand(buildCmd []string) (flags []string, targets []string) {
	var tokens []string
	if len(buildCmd) == 1 {
		tokens = strings.Fields(buildCmd[0])
	} else {
		tokens = buildCmd
	}
	// Drop leading "bazel" and "build".
	for i, t := range tokens {
		if t == "bazel" || t == "bazelisk" {
			continue
		}
		if t == "build" {
			tokens = tokens[i+1:]
			break
		}
	}
	// Walk through tokens; treat anything starting with `//` or `@`
	// as a label target, everything else as a flag. This keeps
	// `bazel build -c opt //a //b` parsing correctly even when a
	// flag accidentally follows the first target.
	for _, t := range tokens {
		if strings.HasPrefix(t, "//") || strings.HasPrefix(t, "@") {
			targets = append(targets, t)
			continue
		}
		flags = append(flags, t)
	}
	if len(targets) > 0 {
		return
	}
	// No `//` / `@` label found: fall back to the last non-flag
	// token (matches the legacy single-target behaviour).
	for i := len(tokens) - 1; i >= 0; i-- {
		if !strings.HasPrefix(tokens[i], "-") {
			targets = []string{tokens[i]}
			flags = nil
			flags = append(flags, tokens[:i]...)
			return
		}
	}
	return tokens, nil
}

// carryOverWasmSkip propagates wasm_skip / wasm_skip_reason from a previous
// build.json onto freshly generated steps. Matching is by output file
// basename (e.g. "symbolize_debugging_debugging.o") because aquery may
// renumber step IDs between runs but the object-file name stays stable.
func carryOverWasmSkip(prev, next []buildjson.BuildStep) {
	prior := make(map[string]buildjson.BuildStep, len(prev))
	for _, s := range prev {
		if s.WasmSkip && s.OutputFile != "" {
			prior[filepath.Base(s.OutputFile)] = s
		}
	}
	if len(prior) == 0 {
		return
	}
	carried := 0
	for i := range next {
		if next[i].OutputFile == "" {
			continue
		}
		if p, ok := prior[filepath.Base(next[i].OutputFile)]; ok {
			next[i].WasmSkip = true
			next[i].WasmSkipReason = p.WasmSkipReason
			carried++
		}
	}
	if carried > 0 {
		fmt.Fprintf(os.Stderr, "[generate-build] carried over %d wasm_skip decisions from previous build.json\n", carried)
	}
}

func cmdGenerateBuild(args []string) error {
	_ = args
	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	logFile := filepath.Join(dataDir, "build.log")
	entries, err := wrapper.ParseLog(logFile)
	if err != nil {
		return fmt.Errorf("failed to parse build log: %w", err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("no build commands captured. Run 'wasmify build' first")
	}

	steps := buildjson.Normalize(entries)

	// Carry over wasm_skip decisions from the existing build.json (if any).
	// Without this, a re-run of generate-build would discard every developer
	// skip choice, and CI would hit the same compile errors again.
	if prev, _ := buildjson.Load(outDir); prev != nil {
		carryOverWasmSkip(prev.Steps, steps)
	} else if prev, _ := buildjson.Load(dataDir); prev != nil {
		carryOverWasmSkip(prev.Steps, steps)
	}

	// Load arch.json (outDir in external mode, dataDir in XDG mode)
	a, _ := arch.Load(outDir)
	if a == nil {
		a, _ = arch.Load(dataDir)
	}
	var projectInfo buildjson.ProjectInfo
	if a != nil {
		projectInfo = buildjson.ProjectInfo{
			Name:        a.Project.Name,
			RootDir:     a.Project.RootDir,
			BuildSystem: a.BuildSystem.Type,
		}
		if a.Selection != nil {
			projectInfo.BuildType = a.Selection.BuildType
		}
	}

	b := &buildjson.BuildJSON{
		Version:    "1.0",
		Project:    projectInfo,
		Steps:      steps,
		CapturedAt: time.Now().UTC().Format(time.RFC3339),
	}

	// build.json goes to outDir (git-managed) in external mode; otherwise
	// to the XDG dataDir.
	buildSaveDir := outDir
	if outDir == dataDir {
		buildSaveDir = dataDir
	}
	if err := buildjson.Save(buildSaveDir, b); err != nil {
		return err
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseOutput)
	_ = c.Save(dataDir)

	compile, link, archive, other := 0, 0, 0, 0
	for _, s := range steps {
		switch s.Type {
		case buildjson.StepCompile:
			compile++
		case buildjson.StepLink:
			link++
		case buildjson.StepArchive:
			archive++
		default:
			other++
		}
	}

	fmt.Printf("build.json generated: %d steps (%d compile, %d link, %d archive, %d other)\n",
		len(steps), compile, link, archive, other)
	return nil
}

func cmdValidateBuild(args []string) error {
	_ = args
	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	b, err := buildjson.Load(outDir)
	if err != nil {
		return err
	}
	if b == nil {
		if b, err = buildjson.Load(dataDir); err != nil {
			return err
		}
	}
	if b == nil {
		return fmt.Errorf("build.json not found. Run 'wasmify build' and 'wasmify generate-build' first")
	}

	fmt.Fprintf(os.Stderr, "[validate-build] Executing %d build steps from build.json\n", len(b.Steps))

	result, err := buildjson.Execute(b)
	if err != nil {
		return err
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseValidateBuild)
	_ = c.Save(dataDir)

	fmt.Fprintf(os.Stderr, "[validate-build] Done: %d built, %d cached (total %d steps)\n",
		result.Succeeded, result.Cached, result.Total)
	return nil
}

func cmdInstallSDK(args []string) error {
	installDir := ""
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--path":
			if i+1 < len(args) {
				i++
				installDir = args[i]
			}
		default:
			if !strings.HasPrefix(args[i], "-") {
				installDir = args[i]
			}
		}
	}

	sdkPath, err := wasmbuild.InstallWasiSDK(installDir)
	if err != nil {
		// "already installed" is not a fatal error
		if strings.Contains(err.Error(), "already installed") {
			fmt.Fprintf(os.Stderr, "%v\n", err)
			fmt.Fprintf(os.Stderr, "[install-sdk] Version: %s\n", wasmbuild.WasiSDKVersion(sdkPath))
			return nil
		}
		return err
	}

	fmt.Fprintf(os.Stderr, "[install-sdk] Version: %s\n", wasmbuild.WasiSDKVersion(sdkPath))
	return nil
}

func cmdEnsureTools(args []string) error {
	skipWasi := false
	for _, a := range args {
		if a == "--skip-wasi-sdk" {
			skipWasi = true
		}
	}

	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}
	archInfo, err := arch.Load(outDir)
	if err != nil {
		return err
	}
	if archInfo == nil {
		return fmt.Errorf("project metadata not found in %s/wasmify.json; run 'wasmify save-arch' first", outDir)
	}

	osID := tools.CurrentOS()
	if osID == "" {
		return fmt.Errorf("unsupported OS; ensure-tools supports darwin and debian/ubuntu")
	}
	fmt.Fprintf(os.Stderr, "[ensure-tools] OS: %s\n", osID)

	catalog := tools.Catalog()
	var failures []string
	for _, t := range archInfo.Tools {
		tool := toToolsTool(t, catalog)
		if err := tools.Ensure(tool); err != nil {
			fmt.Fprintf(os.Stderr, "[ensure-tools] %s: %v\n", t.Name, err)
			failures = append(failures, t.Name)
		}
	}

	if !skipWasi {
		if err := tools.EnsureWasiSDK(); err != nil {
			fmt.Fprintf(os.Stderr, "[ensure-tools] wasi-sdk: %v\n", err)
			failures = append(failures, "wasi-sdk")
		}
	}
	_ = dataDir

	if len(failures) > 0 {
		return fmt.Errorf("failed to install: %s", strings.Join(failures, ", "))
	}
	fmt.Fprintf(os.Stderr, "[ensure-tools] All tools ready.\n")
	return nil
}

// toToolsTool converts an arch.Tool entry into the tools.Tool used by the
// installer. If the arch entry has no install recipe, fall back to the
// catalog so common tools still work even if the agent forgot to fill in
// install commands.
func toToolsTool(t arch.Tool, catalog map[string]tools.Tool) tools.Tool {
	out := tools.Tool{
		Name:      t.Name,
		DetectCmd: t.DetectCmd,
		Version:   t.Version,
	}
	if len(t.Install) > 0 {
		out.Install = make(map[tools.OS]tools.InstallSpec, len(t.Install))
		for k, v := range t.Install {
			out.Install[tools.OS(k)] = tools.InstallSpec{Commands: v.Commands}
		}
		return out
	}
	if c, ok := catalog[t.Name]; ok {
		out.Install = c.Install
		if out.DetectCmd == "" {
			out.DetectCmd = c.DetectCmd
		}
	}
	return out
}

func cmdWasmBuild(args []string) error {
	cfg := wasmbuild.DefaultConfig()
	var explicitSDK string
	var runOptimize bool

	// Parse flags
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--wasi-sdk":
			if i+1 < len(args) {
				i++
				explicitSDK = args[i]
			}
		case "--dry-run":
			cfg.DryRun = true
		case "--output":
			if i+1 < len(args) {
				i++
				cfg.BuildDir = args[i]
			}
		case "--no-cache":
			cfg.NoCache = true
		case "--optimize":
			// Convenience: chain `wasmify optimize` after a
			// successful link so users don't have to run two
			// commands when shipping a release artefact.
			runOptimize = true
		}
	}

	_, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	// Detect wasi-sdk at the shared XDG install location. Unlike per-project
	// build artefacts (under .wasmify/), the SDK is a toolchain installed
	// once per machine and reused across every project wasmify builds.
	sdkPath, err := wasmbuild.DetectOrInstallWasiSDK(explicitSDK)
	if err != nil {
		if !cfg.DryRun {
			return err
		}
		sdkPath = "<wasi-sdk>"
		fmt.Fprintf(os.Stderr, "[wasm-build] wasi-sdk not found (dry-run mode, using placeholder)\n")
	} else {
		fmt.Fprintf(os.Stderr, "[wasm-build] Using wasi-sdk: %s\n", sdkPath)
		fmt.Fprintf(os.Stderr, "[wasm-build] SDK version: %s\n", wasmbuild.WasiSDKVersion(sdkPath))
	}
	cfg.WasiSDKPath = sdkPath

	// Set default build dir
	if cfg.BuildDir == "" {
		cfg.BuildDir = filepath.Join(dataDir, "wasm-build")
	}

	// Load build.json from outDir (the committed root).
	buildJSONDir := outDir
	b, err := buildjson.Load(outDir)
	if err != nil {
		return err
	}
	if b == nil {
		return fmt.Errorf("build.json not found in %s. Run 'wasmify generate-build' first", outDir)
	}

	// Deploy POSIX compatibility headers
	compatDir, err := wasmbuild.DeployPosixCompat(cfg.BuildDir)
	if err != nil {
		return fmt.Errorf("failed to deploy POSIX compat headers: %w", err)
	}
	cfg.PosixCompatDir = compatDir
	fmt.Fprintf(os.Stderr, "[wasm-build] POSIX compat headers: %s\n", compatDir)

	// Transform steps
	wasmSteps := wasmbuild.TransformSteps(b.Steps, cfg)

	// wasm-build always injects the Protobuf bridge because a wasm binary
	// without its service dispatcher is not callable from host code — the
	// whole point of the wasm output is the bridge. Fail fast if gen-proto
	// has not run yet.
	bridgeDir := filepath.Join(dataDir, "wasm-build", "src")
	if _, err := os.Stat(filepath.Join(bridgeDir, "api_bridge.cc")); err != nil {
		return fmt.Errorf("bridge source not found at %s. Run 'wasmify gen-proto --package <name> --bridge-config <file>' before wasm-build", bridgeDir)
	}
	wasmSteps = wasmbuild.InjectBridgeSteps(wasmSteps, cfg, bridgeDir)
	fmt.Fprintf(os.Stderr, "[wasm-build] Bridge injected from %s\n", bridgeDir)

	// Skip decisions live in build.json (wasm_skip/wasm_skip_reason) and
	// are transferred onto the transformed steps by TransformSteps.

	// Save wasm-build.json (with skip decisions already applied)
	if err := wasmbuild.SaveWasmBuildJSON(dataDir, wasmSteps, cfg); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[wasm-build] wasm-build.json saved\n")

	if cfg.DryRun {
		fmt.Println("Dry run complete. wasm-build.json generated.")
		return nil
	}

	// Pre-load wasmify.json once so every handler invocation can
	// consult declarative skip rules without re-reading the file.
	stateForSkip, _ := state.Load(outDir)

	// Build error recovery. Two recovery paths exist (missing header,
	// compile error). Each consults wasmify.json's `skip` section first
	// for a declarative rule; absent that, it prompts the user — unless
	// --non-interactive is on, in which case it returns false (no skip)
	// and the build surfaces the underlying compile error.
	handlers := wasmbuild.ExecuteHandlers{
		OnMissingHeader: func(header, description string) bool {
			if shouldDeployStubHeader(stateForSkip, header) {
				fmt.Fprintf(os.Stderr, "[wasm-build] Auto-deploying stub for <%s> (declared in wasmify.json skip.deploy_stub_headers)\n", header)
				return true
			}
			if globalNonInteractive {
				fmt.Fprintf(os.Stderr, "[wasm-build] Missing header <%s>; declare it in wasmify.json skip.deploy_stub_headers to auto-deploy a stub, or run interactively\n", header)
				return false
			}
			fmt.Fprintf(os.Stderr, "\n[wasm-build] Missing header: <%s>\n\n", header)
			for _, line := range strings.Split(description, "\n") {
				fmt.Fprintf(os.Stderr, "  %s\n", line)
			}
			fmt.Fprintf(os.Stderr, "\n")
			fmt.Fprintf(os.Stderr, "  wasmify can deploy a stub header that provides type definitions and\n")
			fmt.Fprintf(os.Stderr, "  function declarations only. Actual implementations will become wasm\n")
			fmt.Fprintf(os.Stderr, "  imports resolved by the host runtime.\n\n")
			fmt.Fprintf(os.Stderr, "  Deploy stub header? [y/N]: ")

			var response string
			_, _ = fmt.Scanln(&response)
			return strings.ToLower(strings.TrimSpace(response)) == "y"
		},
		OnCompileError: func(step wasmbuild.WasmBuildStep, stderrOutput string, impact wasmbuild.SkipImpact) bool {
			// Show the source file path — distinct basenames map to distinct
			// sources but not vice versa (e.g. absl/log/globals.cc vs
			// absl/log/internal/globals.cc both produce globals.o). The full
			// path lets the user disambiguate same-basename prompts.
			src := strings.Join(step.InputFiles, " ")
			if src == "" {
				src = step.OutputFile
			}
			if shouldSkipFile(stateForSkip, src) {
				fmt.Fprintf(os.Stderr, "[wasm-build] Skipping %s (declared in wasmify.json skip.files)\n", src)
				return true
			}
			if globalNonInteractive {
				fmt.Fprintf(os.Stderr, "[wasm-build] Compile error in %s; declare it in wasmify.json skip.files to skip this source, or run interactively\n", src)
				return false
			}
			fmt.Fprintf(os.Stderr, "\n[wasm-build] Compile error:\n")
			fmt.Fprintf(os.Stderr, "  source: %s\n", src)
			fmt.Fprintf(os.Stderr, "  output: %s\n\n", step.OutputFile)
			errCount := 0
			for _, line := range strings.Split(stderrOutput, "\n") {
				if strings.Contains(line, "error:") || strings.Contains(line, "note:") {
					fmt.Fprintf(os.Stderr, "  %s\n", line)
					errCount++
					if errCount >= 10 {
						fmt.Fprintf(os.Stderr, "  ... (additional errors omitted)\n")
						break
					}
				}
			}
			fmt.Fprintf(os.Stderr, "\n  Impact of skipping:\n")
			if len(impact.AffectedArchives) > 0 {
				fmt.Fprintf(os.Stderr, "    Archives: %s (will exclude %s)\n",
					strings.Join(impact.AffectedArchives, ", "), impact.SkippedFile)
			} else {
				fmt.Fprintf(os.Stderr, "    No archive steps directly reference this file.\n")
			}
			if len(impact.AffectedLinks) > 0 {
				fmt.Fprintf(os.Stderr, "    Link outputs: %s (may have missing symbols at runtime)\n",
					strings.Join(impact.AffectedLinks, ", "))
			}
			fmt.Fprintf(os.Stderr, "\n  Skip this file and continue? [y/N]: ")

			var response string
			_, _ = fmt.Scanln(&response)
			return strings.ToLower(strings.TrimSpace(response)) == "y"
		},
		OnSkipPersist: func(originalID int, reason string) error {
			// Update wasm_skip on the matching step in build.json and save
			// immediately so even if the build crashes later, the decision
			// survives. The extra write is small compared to a 10+ minute
			// compile run.
			for i := range b.Steps {
				if b.Steps[i].ID == originalID {
					b.Steps[i].WasmSkip = true
					b.Steps[i].WasmSkipReason = reason
					break
				}
			}
			return buildjson.Save(buildJSONDir, b)
		},
	}

	// Execute build
	wasmSteps, err = wasmbuild.Execute(wasmSteps, cfg, handlers)
	if err != nil {
		return err
	}

	// For library targets, create a combined .wasm from all built archives.
	// arch.json lives at <outDir>/arch.json (committed), not in dataDir.
	a, _ := arch.Load(outDir)
	if a != nil && a.Selection != nil && a.Selection.BuildType == "library" {
		// The wasm artefact name is derived from the project name
		// (arch.json's project.name) rather than the build target.
		// One project ↔ one wasm ↔ one Go package, so the produced
		// `<project>.wasm` drops directly into the matching
		// protoc-gen-wasmify-go //go:embed slot. Multi-target
		// selections (analyzer + sql_formatter) all merge into the
		// same artefact.
		artefactName := a.Project.Name
		if artefactName == "" {
			// Fall back to whichever target was selected. Single-target
			// projects without a project name still produce `<target>.wasm`.
			if names := a.Selection.Names(); len(names) > 0 {
				artefactName = names[0]
			}
		}
		// Bridge objects feed into the final library link so host callers
		// can reach the wasm target through the per-method `w_<svc>_<mid>`
		// exports plus `wasm_alloc` / `wasm_free` for buffer management.
		var extraObjects []string
		for _, name := range []string{"api_bridge.o", "custom_bridge.o"} {
			obj := filepath.Join(cfg.BuildDir, "obj", name)
			if _, err := os.Stat(obj); err == nil {
				extraObjects = append(extraObjects, obj)
			}
		}
		wasmPath, linkErr := wasmbuild.LinkLibrary(artefactName, cfg, extraObjects)
		if linkErr != nil {
			return fmt.Errorf("library link failed: %w", linkErr)
		}
		fmt.Fprintf(os.Stderr, "[wasm-build] Library wasm: %s\n", wasmPath)

		if runOptimize {
			// Inline post-link size pass — same code path as the
			// standalone `wasmify optimize` subcommand. Auto-installs
			// Binaryen on first use; failure here is fatal because
			// the user explicitly asked for the optimised artefact.
			res, err := binaryen.Optimize(wasmPath, wasmPath, binaryen.OptimizeOptions{})
			if err != nil {
				return fmt.Errorf("--optimize failed: %w", err)
			}
			fmt.Fprintf(os.Stderr, "[wasm-build] optimize: %d → %d bytes (%.1f%% saved)\n",
				res.BeforeSize, res.AfterSize, res.SavedFraction()*100)
		}
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseWasmBuild)
	_ = c.Save(dataDir)

	// Summary
	compile, link, archive, skipped, cached := 0, 0, 0, 0, 0
	for _, s := range wasmSteps {
		if s.Skipped {
			skipped++
			continue
		}
		if s.Cached {
			cached++
		}
		switch s.Type {
		case buildjson.StepCompile:
			compile++
		case buildjson.StepLink:
			link++
		case buildjson.StepArchive:
			archive++
		}
	}
	fmt.Printf("Wasm build complete: %d steps (%d compile, %d archive, %d link, %d skipped, %d cached)\n",
		len(wasmSteps), compile, archive, link, skipped, cached)
	return nil
}

func cmdParseHeaders(args []string) error {
	var headerFiles []string
	clangPath := "clang"

	// Parse flags
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--header":
			if i+1 < len(args) {
				i++
				headerFiles = append(headerFiles, args[i])
			}
		case "--clang":
			if i+1 < len(args) {
				i++
				clangPath = args[i]
			}
		}
	}

	absPath, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	// Load build.json (committed at outDir root).
	b, err := buildjson.Load(outDir)
	if err != nil {
		return err
	}

	// If no explicit headers, discover from build.json dependency files.
	// This uses the .d files generated by -MD -MF during compilation,
	// ensuring we only analyze headers that were actually used in the build.
	//
	// headerGroups tracks which headers co-appear in the same .d file
	// (compilation unit). Headers within the same group are guaranteed
	// compatible; headers across groups may conflict (e.g., different
	// typedef for the same name). We use these groups to build safe
	// umbrella headers.
	var headerGroups [][]string
	if len(headerFiles) == 0 {
		if b == nil {
			return fmt.Errorf("no --header specified and build.json not found. Run 'wasmify generate-build' first or specify --header")
		}
		projectHeaders := scanProjectHeaders(absPath)
		headerFiles, headerGroups = discoverProjectHeadersFromBuild(absPath, b, projectHeaders)
		if len(headerFiles) == 0 {
			return fmt.Errorf("no project headers found in build dependency files. Run 'wasmify validate-build' to ensure build artifacts exist")
		}
	}

	// Collect compile flags from build.json
	var compileFlags []string
	if b != nil {
		compileFlags = collectCompileFlagsFromBuild(b)
	}

	fmt.Fprintf(os.Stderr, "[parse-headers] Using clang: %s\n", clangPath)
	fmt.Fprintf(os.Stderr, "[parse-headers] Headers: %d files (from %d compilation units)\n", len(headerFiles), len(headerGroups))
	fmt.Fprintf(os.Stderr, "[parse-headers] Compile flags: %d flags\n", len(compileFlags))

	var merged *apispec.APISpec

	if len(headerFiles) == 1 {
		// Single header: direct processing
		fmt.Fprintf(os.Stderr, "[parse-headers] Parsing: %s\n", headerFiles[0])
		reader, cleanup, err := clangast.DumpASTStream(clangPath, headerFiles[0], compileFlags)
		if err != nil {
			return fmt.Errorf("failed to start clang: %w", err)
		}
		merged, err = clangast.ParseStream(reader, headerFiles[0])
		if waitErr := cleanup(); waitErr != nil && err == nil {
			err = waitErr
		}
		if err != nil {
			return fmt.Errorf("failed to parse header: %w", err)
		}
	} else {
		// Multiple headers: group into safe umbrella batches.
		// Headers from the same .d file are guaranteed compatible
		// (they coexisted in one compilation unit). We merge groups
		// greedily, validating each merge with clang -fsyntax-only.
		// This avoids combining headers that conflict (e.g., two
		// different typedefs for the same name from different units).
		batches := mergeCompatibleGroups(clangPath, headerGroups, compileFlags)
		fmt.Fprintf(os.Stderr, "[parse-headers] Merged into %d umbrella batches\n", len(batches))

		merged = &apispec.APISpec{}
		dedup := newDeduplicator()
		for i, batch := range batches {
			if len(batch) == 0 {
				continue
			}
			fmt.Fprintf(os.Stderr, "[parse-headers] Batch %d/%d: %d headers\n", i+1, len(batches), len(batch))

			umbrellaFile, err := generateUmbrellaHeader(batch)
			if err != nil {
				return fmt.Errorf("failed to create umbrella header: %w", err)
			}

			reader, cleanup, err := clangast.DumpASTStream(clangPath, umbrellaFile, compileFlags)
			if err != nil {
				_ = os.Remove(umbrellaFile)
				return fmt.Errorf("failed to start clang: %w", err)
			}
			spec, err := clangast.ParseStreamMulti(reader, batch)
			if waitErr := cleanup(); waitErr != nil && err == nil {
				err = waitErr
			}
			_ = os.Remove(umbrellaFile)
			if err != nil {
				return fmt.Errorf("failed to parse headers (batch %d): %w", i+1, err)
			}
			dedup.mergeAPISpec(merged, spec)
		}
		// Re-run enum reclassification on the merged spec so that enum
		// definitions living in one batch can be matched to TypeRefs from
		// another batch (per-batch postProcessEnumTypes can't see the full
		// enum universe). See the comment on PostProcessEnumTypes for why
		// this is load-bearing for multi-batch parses.
		clangast.PostProcessEnumTypes(merged)
		// Same reasoning for handle-class promotion: a class definition
		// might live in one batch while its by-value TypeRefs appear in
		// another. Re-run after the full merge so cross-batch references
		// are promoted to TypeHandle.
		clangast.PostProcessHandleClasses(merged)
	}

	if len(merged.Functions) == 0 && len(merged.Classes) == 0 && len(merged.Enums) == 0 {
		return fmt.Errorf("no API declarations found in headers")
	}

	// Save api-spec.json (to outDir, which is dataDir when --output-dir is not specified)
	if err := apispec.Save(outDir, merged); err != nil {
		return err
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseParseHeaders)
	_ = c.Save(dataDir)

	// Update wasmify.json state if using output-dir
	if outDir != dataDir {
		updateState(outDir, absPath, "parse-headers", []string{"api-spec.json"})
	}

	fmt.Printf("api-spec.json generated: %d functions, %d classes, %d enums\n",
		len(merged.Functions), len(merged.Classes), len(merged.Enums))
	return nil
}

// scanProjectHeaders recursively walks the project directory and collects all
// .h/.hpp/.hxx header files. Symlinks are followed (needed for bazel-out
// generated headers like resolved_ast.h), but symlinks under "external/"
// directories are not followed to avoid pulling in third-party headers.
// All paths are resolved to their real (absolute) path via EvalSymlinks.
func scanProjectHeaders(projectRoot string) map[string]bool {
	headers := make(map[string]bool)

	// Resolve the project root to a real path for comparison
	resolvedRoot := projectRoot
	if real, err := filepath.EvalSymlinks(projectRoot); err == nil {
		resolvedRoot = real
	}

	// outsideProject tracks whether we've followed a symlink that leads
	// outside the project root (e.g., bazel-out → /tmp/_bazel/.../execroot/).
	// When outside the project, we skip "external/" directories because
	// Bazel always places third-party dependencies at <execroot>/external/.
	var walkDir func(dir string, outsideProject bool)
	walkDir = func(dir string, outsideProject bool) {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return
		}
		for _, e := range entries {
			name := e.Name()
			fullPath := filepath.Join(dir, name)

			// Skip hidden directories
			if strings.HasPrefix(name, ".") {
				continue
			}

			if e.IsDir() {
				// When outside the project root (via symlink), skip external/
				// directories. In Bazel, <execroot>/external/ always contains
				// third-party repository code.
				if outsideProject && name == "external" {
					continue
				}
				walkDir(fullPath, outsideProject)
				continue
			}

			// Handle symlinks
			if e.Type()&os.ModeSymlink != 0 {
				info, err := os.Stat(fullPath)
				if err != nil {
					continue
				}
				if info.IsDir() {
					// Determine if following this symlink takes us outside the project
					realPath, err := filepath.EvalSymlinks(fullPath)
					if err != nil {
						continue
					}
					isOutside := outsideProject || !strings.HasPrefix(realPath, resolvedRoot+"/")
					// When outside the project, skip external/ (Bazel third-party)
					if isOutside && name == "external" {
						continue
					}
					walkDir(fullPath, isOutside)
					continue
				}
				// Symlink to file — fall through to header check
			}

			if isHeaderFile(name) {
				if real, err := filepath.EvalSymlinks(fullPath); err == nil {
					headers[real] = true
				} else {
					headers[fullPath] = true
				}
			}
		}
	}

	walkDir(projectRoot, false)
	return headers
}

// discoverProjectHeadersFromBuild extracts project header files from build.json
// dependency files (.d files generated by -MD -MF during compilation).
// Only headers that exist in the pre-scanned projectHeaders set are included.
// Returns:
//   - allHeaders: deduplicated list of all discovered project headers
//   - groups: headers grouped by .d file (compilation unit); headers within
//     a group are guaranteed compatible (they coexisted in one translation unit)
func discoverProjectHeadersFromBuild(projectRoot string, b *buildjson.BuildJSON, projectHeaders map[string]bool) ([]string, [][]string) {
	seen := make(map[string]bool)
	var allHeaders []string
	var groups [][]string

	for _, step := range b.Steps {
		if step.Type != buildjson.StepCompile {
			continue
		}

		// Find the .d dependency file from -MF flag
		depFile := findDepFile(&step)
		if depFile == "" {
			continue
		}
		if !filepath.IsAbs(depFile) {
			depFile = filepath.Join(step.WorkDir, depFile)
		}

		// Parse the .d file to collect all included headers
		deps := parseDependencyFile(depFile)
		var group []string
		for _, dep := range deps {
			if !isHeaderFile(dep) {
				continue
			}
			// Resolve to absolute path
			absDep := dep
			if !filepath.IsAbs(absDep) {
				absDep = filepath.Join(step.WorkDir, absDep)
			}
			// Resolve symlinks to get the real path
			if real, err := filepath.EvalSymlinks(absDep); err == nil {
				absDep = real
			}
			// Only include headers that are part of the project
			if !projectHeaders[absDep] {
				continue
			}
			group = append(group, absDep)
			if !seen[absDep] {
				seen[absDep] = true
				allHeaders = append(allHeaders, absDep)
			}
		}
		if len(group) > 0 {
			groups = append(groups, group)
		}
	}
	return allHeaders, groups
}

// findDepFile extracts the dependency file path from -MF flag in compile step args.
func findDepFile(step *buildjson.BuildStep) string {
	for i, arg := range step.Args {
		if arg == "-MF" && i+1 < len(step.Args) {
			return step.Args[i+1]
		}
	}
	return ""
}

// parseDependencyFile reads a Makefile-format .d file and returns all dependency paths.
// Format: "target: dep1 dep2 \\\n  dep3 dep4 ..."
func parseDependencyFile(path string) []string {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer func() { _ = f.Close() }()

	var deps []string
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 256*1024), 256*1024)
	pastTarget := false

	for scanner.Scan() {
		line := scanner.Text()
		line = strings.TrimSuffix(line, "\\")
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		if !pastTarget {
			// First line has "target: dep1 dep2 ..."
			colonIdx := strings.Index(line, ":")
			if colonIdx >= 0 {
				line = strings.TrimSpace(line[colonIdx+1:])
				pastTarget = true
			}
		}

		// Split by whitespace to get individual paths
		deps = append(deps, strings.Fields(line)...)
	}
	return deps
}

func isHeaderFile(path string) bool {
	ext := strings.ToLower(filepath.Ext(path))
	return ext == ".h" || ext == ".hpp" || ext == ".hxx"
}

// generateUmbrellaHeader creates a temporary .h file that #includes all target headers.
// This allows running clang once to parse all public headers in a single compilation.
// mergeCompatibleGroups merges .d-file header groups into the minimum number
// of umbrella batches that compile without errors. Each .d group is safe
// internally (same compilation unit); we greedily try to combine all groups
// into one umbrella, and only split when clang reports errors.
//
// Algorithm:
//  1. Deduplicate: build one large set of all unique headers across groups
//  2. Try compiling them all as one umbrella
//  3. If it succeeds, return as a single batch
//  4. If it fails, split into two halves and recurse
//
// This is much faster than running clang per-.d-file (which could be 2000+
// invocations) while correctly handling conflicts.
func mergeCompatibleGroups(clangPath string, groups [][]string, compileFlags []string) [][]string {
	// Collect all unique headers preserving the order they first appeared
	seen := make(map[string]bool)
	var all []string
	for _, g := range groups {
		for _, h := range g {
			if !seen[h] {
				seen[h] = true
				all = append(all, h)
			}
		}
	}

	if len(all) == 0 {
		return nil
	}

	// Try the entire set as one batch
	if checkUmbrellaCompiles(clangPath, all, compileFlags) {
		return [][]string{all}
	}

	// Binary split and recurse
	return splitAndMerge(clangPath, all, compileFlags)
}

// splitAndMerge recursively splits a header list into compilable batches.
func splitAndMerge(clangPath string, headers []string, compileFlags []string) [][]string {
	if len(headers) <= 1 {
		// A single header should always compile; if not, skip it
		if len(headers) == 1 && checkUmbrellaCompiles(clangPath, headers, compileFlags) {
			return [][]string{headers}
		}
		return nil
	}

	mid := len(headers) / 2
	left := headers[:mid]
	right := headers[mid:]

	var batches [][]string

	if checkUmbrellaCompiles(clangPath, left, compileFlags) {
		batches = append(batches, left)
	} else {
		batches = append(batches, splitAndMerge(clangPath, left, compileFlags)...)
	}

	if checkUmbrellaCompiles(clangPath, right, compileFlags) {
		batches = append(batches, right)
	} else {
		batches = append(batches, splitAndMerge(clangPath, right, compileFlags)...)
	}

	return batches
}

// checkUmbrellaCompiles generates an umbrella header for the given headers
// and runs clang -fsyntax-only to check if they compile together.
func checkUmbrellaCompiles(clangPath string, headers []string, compileFlags []string) bool {
	if len(headers) == 0 {
		return true
	}
	umbrellaFile, err := generateUmbrellaHeader(headers)
	if err != nil {
		return false
	}
	defer func() { _ = os.Remove(umbrellaFile) }()

	args := clangast.BuildSyntaxCheckArgs(umbrellaFile, compileFlags)
	cmd := exec.Command(clangPath, args...)
	cmd.Stdout = nil
	cmd.Stderr = nil
	return cmd.Run() == nil
}

func generateUmbrellaHeader(headerFiles []string) (string, error) {
	f, err := os.CreateTemp("", "wasmify-umbrella-*.h")
	if err != nil {
		return "", err
	}

	_, _ = fmt.Fprintf(f, "// Auto-generated umbrella header for wasmify parse-headers\n")
	_, _ = fmt.Fprintf(f, "// DO NOT EDIT\n\n")
	for _, h := range headerFiles {
		_, _ = fmt.Fprintf(f, "#include \"%s\"\n", h)
	}

	if err := f.Close(); err != nil {
		_ = os.Remove(f.Name())
		return "", err
	}
	return f.Name(), nil
}

// collectCompileFlagsFromBuild extracts unique compile flags from all compile steps.
// Relative include paths are resolved against the step's work_dir.
func collectCompileFlagsFromBuild(b *buildjson.BuildJSON) []string {
	seen := make(map[string]bool)
	var flags []string

	for _, step := range b.Steps {
		if step.Type != buildjson.StepCompile {
			continue
		}
		stepFlags := clangast.CollectCompileFlags(step.Args)
		for i := 0; i < len(stepFlags); i++ {
			f := stepFlags[i]
			// Resolve relative paths in include-type flags
			f = resolveIncludeFlag(f, step.WorkDir)
			// For separate-argument flags (-I <path>), also resolve the next arg
			if (f == "-I" || f == "-isystem" || f == "-iquote") && i+1 < len(stepFlags) {
				i++
				resolved := resolveIncludePath(stepFlags[i], step.WorkDir)
				key := f + " " + resolved
				if !seen[key] {
					seen[key] = true
					flags = append(flags, f, resolved)
				}
				continue
			}
			if !seen[f] {
				seen[f] = true
				flags = append(flags, f)
			}
		}
	}
	return flags
}

// resolveIncludeFlag resolves a joined include flag like -I<path> or -isystem<path>.
func resolveIncludeFlag(flag, workDir string) string {
	for _, prefix := range []string{"-I", "-isystem", "-iquote"} {
		if strings.HasPrefix(flag, prefix) && len(flag) > len(prefix) {
			path := flag[len(prefix):]
			resolved := resolveIncludePath(path, workDir)
			return prefix + resolved
		}
	}
	return flag
}

// resolveIncludePath resolves a path relative to workDir if it's not absolute.
func resolveIncludePath(path, workDir string) string {
	if filepath.IsAbs(path) || workDir == "" {
		return path
	}
	abs := filepath.Join(workDir, path)
	// Only use absolute path if the directory actually exists
	if info, err := os.Stat(abs); err == nil && info.IsDir() {
		return abs
	}
	return path
}

// deduplicator tracks seen qualified names across multiple mergeAPISpec calls.
type deduplicator struct {
	seenFunctions map[string]bool
	seenClasses   map[string]bool
	seenEnums     map[string]bool
}

func newDeduplicator() *deduplicator {
	return &deduplicator{
		seenFunctions: make(map[string]bool),
		seenClasses:   make(map[string]bool),
		seenEnums:     make(map[string]bool),
	}
}

// mergeAPISpec merges src into dst, deduplicating by qualified name.
// When the same class/function/enum appears in multiple batches (due to
// shared headers across compilation units), only the first occurrence is kept.
func (d *deduplicator) mergeAPISpec(dst, src *apispec.APISpec) {
	if src.Namespace != "" && dst.Namespace == "" {
		dst.Namespace = src.Namespace
	}

	for _, f := range src.Functions {
		if !d.seenFunctions[f.QualName] {
			d.seenFunctions[f.QualName] = true
			dst.Functions = append(dst.Functions, f)
		}
	}
	for _, c := range src.Classes {
		if !d.seenClasses[c.QualName] {
			d.seenClasses[c.QualName] = true
			dst.Classes = append(dst.Classes, c)
		}
	}
	for _, e := range src.Enums {
		if !d.seenEnums[e.QualName] {
			d.seenEnums[e.QualName] = true
			dst.Enums = append(dst.Enums, e)
		}
	}
}

func cmdGenProto(args []string) error {
	packageName := ""
	bridgeConfigFile := ""

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--package":
			if i+1 < len(args) {
				i++
				packageName = args[i]
			}
		case "--bridge-config":
			if i+1 < len(args) {
				i++
				bridgeConfigFile = args[i]
			}
		}
	}

	absPath, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	// Load api-spec.json (outDir root).
	spec, err := apispec.Load(outDir)
	if err != nil {
		return err
	}
	if spec == nil {
		return fmt.Errorf("api-spec.json not found in %s. Run 'wasmify parse-headers' first", outDir)
	}

	// Load arch metadata. The committed wasmify.json lives in outDir;
	// fall back to dataDir for legacy layouts where the analyzer wrote
	// to the XDG cache.
	archInfo, _ := arch.Load(outDir)
	if archInfo == nil {
		archInfo, _ = arch.Load(dataDir)
	}
	_ = absPath

	// Derive package name from arch.json if not specified
	if packageName == "" {
		if archInfo != nil && archInfo.Project.Name != "" {
			packageName = strings.ToLower(strings.ReplaceAll(archInfo.Project.Name, "-", "_"))
		} else {
			packageName = "api"
		}
	}

	// Load bridge config (shared between proto and C++ bridge generation).
	// Priority: --bridge-config flag > wasmify.json `bridge` section >
	// defaults. The flag is retained for one-shot overrides; under normal
	// use the bridge config lives inside wasmify.json so the project commits
	// a single config file.
	bridgeCfg := protogen.DefaultBridgeConfig()
	persistBridgeToState := false
	if bridgeConfigFile != "" {
		cfgData, err := os.ReadFile(bridgeConfigFile)
		if err != nil {
			return fmt.Errorf("failed to read bridge config: %w", err)
		}
		if err := json.Unmarshal(cfgData, &bridgeCfg); err != nil {
			return fmt.Errorf("failed to parse bridge config: %w", err)
		}
	} else if s, _ := state.Load(outDir); s != nil && s.Bridge != nil {
		bridgeCfg = *s.Bridge
		persistBridgeToState = true
	}

	// Auto-discover dependent libraries and persist back to state if we
	// loaded from there. We don't write back to a stand-alone bridge-
	// config.json file when --bridge-config was given — that mode is for
	// one-shot inspection.
	if bridgeCfg.ExportDependentLibraries == nil {
		bridgeCfg.ExportDependentLibraries = protogen.DiscoverLibraries(spec)
		if persistBridgeToState {
			if updateErr := state.Update(outDir, func(st *state.State) error {
				updated := bridgeCfg
				st.Bridge = &updated
				return nil
			}); updateErr != nil {
				fmt.Fprintf(os.Stderr, "[gen-proto] Warning: failed to update wasmify.json: %v\n", updateErr)
			} else {
				fmt.Fprintf(os.Stderr, "[gen-proto] Updated wasmify.json bridge.ExportDependentLibraries\n")
			}
		}
	}

	// Apply export filter if specified
	filteredSpec := protogen.ApplyExportFilter(spec, bridgeCfg)

	// Generate .proto (uses bridgeCfg to ensure service IDs match C++ bridge)
	protoContent := protogen.GenerateProtoWithConfig(filteredSpec, packageName, bridgeCfg)
	protoFilename := packageName + ".proto"

	// Validate proto with protocompile before saving
	if err := protogen.ValidateProto(protoContent, packageName); err != nil {
		// Dump the in-memory proto for post-mortem inspection. The
		// on-disk file may still be stale from a prior successful run,
		// so dumping here lets callers look at exactly what failed.
		_ = os.WriteFile("/tmp/wasmify-invalid.proto", []byte(protoContent), 0o644)
		return fmt.Errorf("generated proto is invalid: %w (dumped to /tmp/wasmify-invalid.proto)", err)
	}
	fmt.Fprintf(os.Stderr, "[gen-proto] Proto validation passed\n")

	if err := protogen.SaveProto(outDir, protoContent, protoFilename); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[gen-proto] Generated proto/%s\n", protoFilename)

	// Save options.proto
	if err := protogen.SaveOptionsProto(outDir); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[gen-proto] Generated proto/wasmify/options.proto\n")

	// Generate C++ bridge
	projectRoot := ""
	if archInfo != nil {
		projectRoot = archInfo.Project.RootDir
	}
	bridgeCC := protogen.GenerateBridgeWithConfig(filteredSpec, packageName, projectRoot, bridgeCfg)
	bridgeH := protogen.GenerateBridgeHeader(filteredSpec, packageName)

	// Always save bridge to dataDir for wasm-build
	if err := protogen.SaveBridge(dataDir, bridgeCC, bridgeH); err != nil {
		return err
	}
	if outDir != dataDir {
		// Also save to outDir/bridge/ for git-managed output
		bridgeDir := filepath.Join(outDir, "bridge")
		if err := os.MkdirAll(bridgeDir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(bridgeDir, "api_bridge.cc"), []byte(bridgeCC), 0o644); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(bridgeDir, "api_bridge.h"), []byte(bridgeH), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "[gen-proto] Generated bridge/api_bridge.cc\n")
		fmt.Fprintf(os.Stderr, "[gen-proto] Generated bridge/api_bridge.h\n")
	} else {
		fmt.Fprintf(os.Stderr, "[gen-proto] Generated wasm-build/src/api_bridge.cc\n")
		fmt.Fprintf(os.Stderr, "[gen-proto] Generated wasm-build/src/api_bridge.h\n")
	}

	// Update cache
	c, _ := cache.Load(dataDir)
	if c == nil {
		c = cache.New()
	}
	c.CompletePhase(cache.PhaseGenProto)
	_ = c.Save(dataDir)

	// Update wasmify.json state and generate scaffold if using output-dir
	if outDir != dataDir {
		outputFiles := []string{
			"proto/" + protoFilename,
			"proto/wasmify/options.proto",
			"bridge/api_bridge.cc",
			"bridge/api_bridge.h",
		}
		updateState(outDir, absPath, "gen-proto", outputFiles)

		// Generate scaffold (Makefile, release.yml) if not already present
		if err := scaffold.Generate(outDir, absPath); err != nil {
			fmt.Fprintf(os.Stderr, "[gen-proto] Warning: scaffold generation failed: %v\n", err)
		}
	}

	// Summary
	handleCount := 0
	for _, cls := range filteredSpec.Classes {
		if cls.IsHandle {
			handleCount++
		}
	}
	fmt.Printf("Proto bridge generated: %d functions, %d classes (%d handle types), %d enums\n",
		len(filteredSpec.Functions), len(filteredSpec.Classes), handleCount, len(filteredSpec.Enums))
	return nil
}

// updateState loads or creates wasmify.json in the given directory and records
// a phase completion. This is used when --output-dir is specified.
func updateState(outDir, projectPath, phaseName string, outputFiles []string) {
	s, _ := state.Load(outDir)
	if s == nil {
		s = state.New(upstreamPathFor(projectPath, outDir))
	}
	commit, _ := gitHeadCommit(projectPath)
	branch, _ := gitCurrentBranch(projectPath)
	s.UpdateUpstream(commit, branch)
	s.CompletePhase(phaseName, commit, outputFiles)
	if err := state.Save(outDir, s); err != nil {
		fmt.Fprintf(os.Stderr, "[wasmify] warning: failed to save wasmify.json: %v\n", err)
	}
}

// gitHeadCommit returns the HEAD commit hash of the given git repository.
func gitHeadCommit(repoPath string) (string, error) {
	cmd := exec.Command("git", "-C", repoPath, "rev-parse", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git rev-parse HEAD failed: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// gitCurrentBranch returns the current branch name.
func gitCurrentBranch(repoPath string) (string, error) {
	cmd := exec.Command("git", "-C", repoPath, "rev-parse", "--abbrev-ref", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git rev-parse --abbrev-ref HEAD failed: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// gitDiffFiles returns the list of changed files between two commits.
func gitDiffFiles(repoPath, oldCommit, newCommit string) ([]string, error) {
	cmd := exec.Command("git", "-C", repoPath, "diff", "--name-only", oldCommit+".."+newCommit)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git diff --name-only failed: %w", err)
	}
	var files []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			files = append(files, line)
		}
	}
	return files, nil
}

// classifyChanges determines which phases need to be re-run based on changed files.
// Returns a set of phase names that need re-execution.
func classifyChanges(changedFiles []string) map[string]bool {
	phases := make(map[string]bool)
	for _, f := range changedFiles {
		ext := strings.ToLower(filepath.Ext(f))
		base := filepath.Base(f)
		switch {
		case ext == ".h" || ext == ".hpp" || ext == ".hxx":
			phases["parse-headers"] = true
			phases["gen-proto"] = true
			phases["wasm-build"] = true
		case ext == ".cc" || ext == ".cpp" || ext == ".cxx" || ext == ".c":
			phases["wasm-build"] = true
		case strings.HasPrefix(base, "BUILD") || strings.HasPrefix(base, "MODULE.bazel") || base == ".bazelrc":
			phases["build"] = true
			phases["generate-build"] = true
			phases["parse-headers"] = true
			phases["gen-proto"] = true
			phases["wasm-build"] = true
		case base == "wasmify.json":
			// wasmify.json carries the bridge config (and other
			// committed decisions). Any change there can affect proto
			// + bridge generation, so re-run gen-proto + wasm-build.
			phases["gen-proto"] = true
			phases["wasm-build"] = true
		}
	}
	return phases
}

// cmdOptimize runs the Binaryen wasm-opt pipeline against the
// project's built wasm to drive size down further. By default it
// rewrites the artefact in place (matching the "the wasm you build
// is the wasm you ship" model); --input / --output override that
// for one-off use. Binaryen is auto-installed under
// ~/.config/wasmify/bin/binaryen on first invocation, the same way
// `wasmify install-sdk` provisions wasi-sdk.
func cmdOptimize(args []string) error {
	var (
		inputPath  string
		outputPath string
		verbose    bool
	)
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--input":
			if i+1 < len(args) {
				i++
				inputPath = args[i]
			}
		case "--output":
			if i+1 < len(args) {
				i++
				outputPath = args[i]
			}
		case "--verbose":
			verbose = true
		}
	}

	if inputPath == "" {
		// Derive the project's wasm artefact path from
		// arch.json (project.name) + data dir conventions.
		absPath, dataDir, outDir, err := loadProjectFromConfig()
		_ = absPath
		_ = outDir
		if err != nil {
			return fmt.Errorf("--input not given and could not load project: %w", err)
		}
		a, _ := arch.Load(outDir)
		if a == nil {
			a, _ = arch.Load(dataDir)
		}
		if a == nil || a.Project.Name == "" {
			return fmt.Errorf("--input not given and arch.json/project.name unavailable; pass --input <path/to/foo.wasm>")
		}
		inputPath = filepath.Join(dataDir, "wasm-build", "output", a.Project.Name+".wasm")
	}
	if _, err := os.Stat(inputPath); err != nil {
		return fmt.Errorf("input wasm not found at %s: %w", inputPath, err)
	}
	if outputPath == "" {
		outputPath = inputPath
	}

	res, err := binaryen.Optimize(inputPath, outputPath, binaryen.OptimizeOptions{Verbose: verbose})
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[optimize] %s\n", inputPath)
	fmt.Fprintf(os.Stderr, "[optimize]   before: %d bytes (%.2f MB)\n", res.BeforeSize, float64(res.BeforeSize)/(1024*1024))
	fmt.Fprintf(os.Stderr, "[optimize]   after:  %d bytes (%.2f MB)\n", res.AfterSize, float64(res.AfterSize)/(1024*1024))
	fmt.Fprintf(os.Stderr, "[optimize]   saved:  %d bytes (%.1f%%)\n", res.SavedBytes(), res.SavedFraction()*100)
	if outputPath != inputPath {
		fmt.Fprintf(os.Stderr, "[optimize] wrote %s\n", outputPath)
	}
	return nil
}

func cmdUpdate(args []string) error {
	_ = args
	absPath, dataDir, outDir, err := loadProjectFromConfig()
	if err != nil {
		return err
	}

	// Load wasmify.json
	s, err := state.Load(outDir)
	if err != nil {
		return err
	}
	if s == nil {
		// First run: initialize state
		s = state.New(upstreamPathFor(absPath, outDir))
	}

	// Get current HEAD
	currentCommit, err := gitHeadCommit(absPath)
	if err != nil {
		return fmt.Errorf("failed to get git HEAD: %w", err)
	}
	currentBranch, _ := gitCurrentBranch(absPath)

	// Check if upstream has changed
	if s.Upstream.Commit == currentCommit {
		fmt.Fprintf(os.Stderr, "[update] Upstream is up to date (commit: %s)\n", currentCommit[:12])
		return nil
	}

	// Determine which phases need re-running
	var neededPhases map[string]bool
	if s.Upstream.Commit == "" {
		// First run: all phases needed
		fmt.Fprintf(os.Stderr, "[update] First run, will execute all phases\n")
		neededPhases = map[string]bool{
			"parse-headers": true,
			"gen-proto":     true,
		}
	} else {
		changedFiles, err := gitDiffFiles(absPath, s.Upstream.Commit, currentCommit)
		if err != nil {
			return fmt.Errorf("failed to get changed files: %w", err)
		}
		fmt.Fprintf(os.Stderr, "[update] %d files changed between %s..%s\n",
			len(changedFiles), s.Upstream.Commit[:12], currentCommit[:12])
		neededPhases = classifyChanges(changedFiles)
	}

	if len(neededPhases) == 0 {
		fmt.Fprintf(os.Stderr, "[update] No relevant changes detected\n")
		s.UpdateUpstream(currentCommit, currentBranch)
		return state.Save(outDir, s)
	}

	// Execute needed phases in order
	phaseOrder := []string{"build", "generate-build", "parse-headers", "gen-proto", "wasm-build"}
	for _, phase := range phaseOrder {
		if !neededPhases[phase] {
			continue
		}
		fmt.Fprintf(os.Stderr, "[update] Running phase: %s\n", phase)

		// All subcommands now read wasmify.json from cwd; no args needed.
		var phaseErr error
		switch phase {
		case "build":
			phaseErr = cmdBuild(nil)
		case "generate-build":
			phaseErr = cmdGenerateBuild(nil)
		case "parse-headers":
			phaseErr = cmdParseHeaders(nil)
		case "gen-proto":
			phaseErr = cmdGenProto(nil)
		case "wasm-build":
			phaseErr = cmdWasmBuild(nil)
		}

		if phaseErr != nil {
			return fmt.Errorf("phase %s failed: %w", phase, phaseErr)
		}
	}

	// Update state
	s.UpdateUpstream(currentCommit, currentBranch)
	if err := state.Save(outDir, s); err != nil {
		return fmt.Errorf("failed to save wasmify.json: %w", err)
	}

	// Generate scaffold on first output-dir usage
	if outDir != dataDir {
		if err := scaffold.Generate(outDir, absPath); err != nil {
			fmt.Fprintf(os.Stderr, "[update] warning: scaffold generation failed: %v\n", err)
		}
	}

	fmt.Fprintf(os.Stderr, "[update] Updated to commit %s\n", currentCommit[:12])
	return nil
}
