// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wasmify/options.proto

package wasmify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_wasmify_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "wasmify.wasm_handle",
		Tag:           "varint,50000,opt,name=wasm_handle",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "wasmify.wasm_parent",
		Tag:           "bytes,50002,opt,name=wasm_parent",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50012,
		Name:          "wasmify.wasm_parents",
		Tag:           "bytes,50012,rep,name=wasm_parents",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "wasmify.wasm_list_type",
		Tag:           "varint,50005,opt,name=wasm_list_type",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50006,
		Name:          "wasmify.wasm_map_type",
		Tag:           "varint,50006,opt,name=wasm_map_type",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50007,
		Name:          "wasmify.wasm_source_file",
		Tag:           "bytes,50007,opt,name=wasm_source_file",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50009,
		Name:          "wasmify.wasm_abstract",
		Tag:           "varint,50009,opt,name=wasm_abstract",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50014,
		Name:          "wasmify.wasm_message_comment",
		Tag:           "bytes,50014,opt,name=wasm_message_comment",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50015,
		Name:          "wasmify.wasm_field_comment",
		Tag:           "bytes,50015,opt,name=wasm_field_comment",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50019,
		Name:          "wasmify.wasm_take_ownership",
		Tag:           "varint,50019,opt,name=wasm_take_ownership",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "wasmify.wasm_callback",
		Tag:           "varint,50001,opt,name=wasm_callback",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50008,
		Name:          "wasmify.wasm_service_source_file",
		Tag:           "bytes,50008,opt,name=wasm_service_source_file",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50010,
		Name:          "wasmify.wasm_service_id",
		Tag:           "varint,50010,opt,name=wasm_service_id",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "wasmify.wasm_method_type",
		Tag:           "bytes,50003,opt,name=wasm_method_type",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "wasmify.wasm_original_name",
		Tag:           "bytes,50004,opt,name=wasm_original_name",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50011,
		Name:          "wasmify.wasm_method_id",
		Tag:           "varint,50011,opt,name=wasm_method_id",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50016,
		Name:          "wasmify.wasm_method_comment",
		Tag:           "bytes,50016,opt,name=wasm_method_comment",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50017,
		Name:          "wasmify.wasm_enum_comment",
		Tag:           "bytes,50017,opt,name=wasm_enum_comment",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50018,
		Name:          "wasmify.wasm_enum_value_comment",
		Tag:           "bytes,50018,opt,name=wasm_enum_value_comment",
		Filename:      "wasmify/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50013,
		Name:          "wasmify.wasm_cpp_namespace",
		Tag:           "bytes,50013,opt,name=wasm_cpp_namespace",
		Filename:      "wasmify/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool wasm_handle = 50000;
	E_WasmHandle = &file_wasmify_options_proto_extTypes[0]
	// Immediate (primary) C++ base class. For single inheritance this
	// is the only parent.
	//
	// optional string wasm_parent = 50002;
	E_WasmParent = &file_wasmify_options_proto_extTypes[1]
	// Secondary parents for C++ multiple inheritance. When the C++
	// class extends two or more bases, `wasm_parent` names the first
	// and this repeated option lists the remaining bases (already
	// resolved to proto message names).
	//
	// repeated string wasm_parents = 50012;
	E_WasmParents = &file_wasmify_options_proto_extTypes[2]
	// optional bool wasm_list_type = 50005;
	E_WasmListType = &file_wasmify_options_proto_extTypes[3]
	// optional bool wasm_map_type = 50006;
	E_WasmMapType = &file_wasmify_options_proto_extTypes[4]
	// optional string wasm_source_file = 50007;
	E_WasmSourceFile = &file_wasmify_options_proto_extTypes[5]
	// optional bool wasm_abstract = 50009;
	E_WasmAbstract = &file_wasmify_options_proto_extTypes[6]
	// Doc comment lifted from the C++ class declaration. Emitted as a
	// Go doc comment on the generated handle struct / interface.
	//
	// optional string wasm_message_comment = 50014;
	E_WasmMessageComment = &file_wasmify_options_proto_extTypes[7]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Doc comment lifted from the C++ field declaration.
	//
	// optional string wasm_field_comment = 50015;
	E_WasmFieldComment = &file_wasmify_options_proto_extTypes[8]
	// Marks a method-input handle field whose C++ counterpart takes
	// ownership of the wrapped pointer (e.g. `unique_ptr<T>` by value
	// or by rvalue-ref). When true, the Go-side wrapper must clear
	// the argument's `ptr` AFTER the invoke so the per-instance Go
	// finalizer does not call free() on memory the C++ side has
	// already deleted. Without this clear, the Go GC double-frees:
	// the parent's destructor runs the unique_ptr deleter, then the
	// child's still-attached finalizer issues a second Free RPC.
	// Typical symptom is a panic on the next handle accessed through
	// the parent (vtable read against freed memory).
	//
	// optional bool wasm_take_ownership = 50019;
	E_WasmTakeOwnership = &file_wasmify_options_proto_extTypes[9]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional bool wasm_callback = 50001;
	E_WasmCallback = &file_wasmify_options_proto_extTypes[10]
	// optional string wasm_service_source_file = 50008;
	E_WasmServiceSourceFile = &file_wasmify_options_proto_extTypes[11]
	// optional int32 wasm_service_id = 50010;
	E_WasmServiceId = &file_wasmify_options_proto_extTypes[12]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string wasm_method_type = 50003;
	E_WasmMethodType = &file_wasmify_options_proto_extTypes[13]
	// optional string wasm_original_name = 50004;
	E_WasmOriginalName = &file_wasmify_options_proto_extTypes[14]
	// optional int32 wasm_method_id = 50011;
	E_WasmMethodId = &file_wasmify_options_proto_extTypes[15]
	// Doc comment lifted from the C++ method declaration.
	//
	// optional string wasm_method_comment = 50016;
	E_WasmMethodComment = &file_wasmify_options_proto_extTypes[16]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// Doc comment lifted from the C++ enum declaration.
	//
	// optional string wasm_enum_comment = 50017;
	E_WasmEnumComment = &file_wasmify_options_proto_extTypes[17]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Doc comment lifted from the C++ enumerator declaration.
	//
	// optional string wasm_enum_value_comment = 50018;
	E_WasmEnumValueComment = &file_wasmify_options_proto_extTypes[18]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// Actual C++ namespace of the source library (e.g. "googlesql").
	// Used by resolveAbstractHandle to map runtime C++ typeid strings
	// back to Go concrete factories. Without it, the plugin would have
	// to guess based on the proto package, which is arbitrary.
	//
	// optional string wasm_cpp_namespace = 50013;
	E_WasmCppNamespace = &file_wasmify_options_proto_extTypes[19]
)

var File_wasmify_options_proto protoreflect.FileDescriptor

const file_wasmify_options_proto_rawDesc = "" +
	"\n" +
	"\x15wasmify/options.proto\x12\awasmify\x1a google/protobuf/descriptor.proto:B\n" +
	"\vwasm_handle\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\bR\n" +
	"wasmHandle:B\n" +
	"\vwasm_parent\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\tR\n" +
	"wasmParent:D\n" +
	"\fwasm_parents\x12\x1f.google.protobuf.MessageOptions\x18܆\x03 \x03(\tR\vwasmParents:G\n" +
	"\x0ewasm_list_type\x12\x1f.google.protobuf.MessageOptions\x18Ն\x03 \x01(\bR\fwasmListType:E\n" +
	"\rwasm_map_type\x12\x1f.google.protobuf.MessageOptions\x18ֆ\x03 \x01(\bR\vwasmMapType:K\n" +
	"\x10wasm_source_file\x12\x1f.google.protobuf.MessageOptions\x18׆\x03 \x01(\tR\x0ewasmSourceFile:F\n" +
	"\rwasm_abstract\x12\x1f.google.protobuf.MessageOptions\x18ن\x03 \x01(\bR\fwasmAbstract:S\n" +
	"\x14wasm_message_comment\x12\x1f.google.protobuf.MessageOptions\x18ކ\x03 \x01(\tR\x12wasmMessageComment:M\n" +
	"\x12wasm_field_comment\x12\x1d.google.protobuf.FieldOptions\x18߆\x03 \x01(\tR\x10wasmFieldComment:O\n" +
	"\x13wasm_take_ownership\x12\x1d.google.protobuf.FieldOptions\x18\xe3\x86\x03 \x01(\bR\x11wasmTakeOwnership:F\n" +
	"\rwasm_callback\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\bR\fwasmCallback:Z\n" +
	"\x18wasm_service_source_file\x12\x1f.google.protobuf.ServiceOptions\x18؆\x03 \x01(\tR\x15wasmServiceSourceFile:I\n" +
	"\x0fwasm_service_id\x12\x1f.google.protobuf.ServiceOptions\x18چ\x03 \x01(\x05R\rwasmServiceId:J\n" +
	"\x10wasm_method_type\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\tR\x0ewasmMethodType:N\n" +
	"\x12wasm_original_name\x12\x1e.google.protobuf.MethodOptions\x18Ԇ\x03 \x01(\tR\x10wasmOriginalName:F\n" +
	"\x0ewasm_method_id\x12\x1e.google.protobuf.MethodOptions\x18ۆ\x03 \x01(\x05R\fwasmMethodId:P\n" +
	"\x13wasm_method_comment\x12\x1e.google.protobuf.MethodOptions\x18\xe0\x86\x03 \x01(\tR\x11wasmMethodComment:J\n" +
	"\x11wasm_enum_comment\x12\x1c.google.protobuf.EnumOptions\x18\xe1\x86\x03 \x01(\tR\x0fwasmEnumComment:Z\n" +
	"\x17wasm_enum_value_comment\x12!.google.protobuf.EnumValueOptions\x18\xe2\x86\x03 \x01(\tR\x14wasmEnumValueComment:L\n" +
	"\x12wasm_cpp_namespace\x12\x1c.google.protobuf.FileOptions\x18݆\x03 \x01(\tR\x10wasmCppNamespaceB(Z&github.com/goccy/wasmify/proto/wasmifyb\x06proto3"

var file_wasmify_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil),   // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 1: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil),   // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 3: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 4: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 5: google.protobuf.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 6: google.protobuf.FileOptions
}
var file_wasmify_options_proto_depIdxs = []int32{
	0,  // 0: wasmify.wasm_handle:extendee -> google.protobuf.MessageOptions
	0,  // 1: wasmify.wasm_parent:extendee -> google.protobuf.MessageOptions
	0,  // 2: wasmify.wasm_parents:extendee -> google.protobuf.MessageOptions
	0,  // 3: wasmify.wasm_list_type:extendee -> google.protobuf.MessageOptions
	0,  // 4: wasmify.wasm_map_type:extendee -> google.protobuf.MessageOptions
	0,  // 5: wasmify.wasm_source_file:extendee -> google.protobuf.MessageOptions
	0,  // 6: wasmify.wasm_abstract:extendee -> google.protobuf.MessageOptions
	0,  // 7: wasmify.wasm_message_comment:extendee -> google.protobuf.MessageOptions
	1,  // 8: wasmify.wasm_field_comment:extendee -> google.protobuf.FieldOptions
	1,  // 9: wasmify.wasm_take_ownership:extendee -> google.protobuf.FieldOptions
	2,  // 10: wasmify.wasm_callback:extendee -> google.protobuf.ServiceOptions
	2,  // 11: wasmify.wasm_service_source_file:extendee -> google.protobuf.ServiceOptions
	2,  // 12: wasmify.wasm_service_id:extendee -> google.protobuf.ServiceOptions
	3,  // 13: wasmify.wasm_method_type:extendee -> google.protobuf.MethodOptions
	3,  // 14: wasmify.wasm_original_name:extendee -> google.protobuf.MethodOptions
	3,  // 15: wasmify.wasm_method_id:extendee -> google.protobuf.MethodOptions
	3,  // 16: wasmify.wasm_method_comment:extendee -> google.protobuf.MethodOptions
	4,  // 17: wasmify.wasm_enum_comment:extendee -> google.protobuf.EnumOptions
	5,  // 18: wasmify.wasm_enum_value_comment:extendee -> google.protobuf.EnumValueOptions
	6,  // 19: wasmify.wasm_cpp_namespace:extendee -> google.protobuf.FileOptions
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	0,  // [0:20] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_wasmify_options_proto_init() }
func file_wasmify_options_proto_init() {
	if File_wasmify_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wasmify_options_proto_rawDesc), len(file_wasmify_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 20,
			NumServices:   0,
		},
		GoTypes:           file_wasmify_options_proto_goTypes,
		DependencyIndexes: file_wasmify_options_proto_depIdxs,
		ExtensionInfos:    file_wasmify_options_proto_extTypes,
	}.Build()
	File_wasmify_options_proto = out.File
	file_wasmify_options_proto_goTypes = nil
	file_wasmify_options_proto_depIdxs = nil
}
