package protogen

import (
	"strings"
	"testing"

	"github.com/goccy/wasmify/internal/apispec"
)

func TestGenerateBridge(t *testing.T) {
	spec := testAPISpec()
	output := GenerateBridge(spec, "test", "")

	checks := []struct {
		name string
		want string
	}{
		// Header includes
		{"auto-generated comment", "Auto-generated by wasmify gen-proto. DO NOT EDIT."},
		{"include cstdlib", "#include <cstdlib>"},
		{"include cstring", "#include <cstring>"},
		{"include cstdint", "#include <cstdint>"},

		// Wasm exports
		{"wasm_alloc export", "WASM_EXPORT(wasm_alloc)"},
		{"wasm_alloc func", "void* wasm_alloc(int32_t size)"},
		{"wasm_free export", "WASM_EXPORT(wasm_free)"},
		{"wasm_free func", "void wasm_free(void* ptr)"},
		// The bridge no longer routes calls through a single
		// `wasm_invoke` dispatcher. Each (service, method) pair is
		// its own export so the host can dispatch directly. The
		// `wasmify_get_type_name` export covers the runtime-typeid
		// path that used to be `service_id == -1`.
		{"type name export", "WASM_EXPORT(wasmify_get_type_name)"},

		// Callback import
		{"callback import", "WASM_IMPORT(wasmify, callback_invoke)"},
		{"callback func", "int64_t wasmify_callback_invoke(int32_t callback_id, int32_t method_id, void* req, int32_t req_len)"},

		// Service/method ID constants for free functions
		{"free func service id", "SERVICE_TEST = 0"},
		{"free func method id", "METHOD_TEST_ADD = 0"},

		// Service/method ID constants for Calculator. Downcast
		// METHOD_X_TO_Y is intentionally absent — Go type assertion
		// replaces the RPC, so Free follows Compute/GetName directly.
		{"calculator service id", "SERVICE_CALCULATOR = 1"},
		{"calculator compute method id", "METHOD_CALCULATOR_COMPUTE = 0"},
		{"calculator get name method id", "METHOD_CALCULATOR_GET_NAME = 1"},
		{"calculator free method id", "METHOD_CALCULATOR_RELEASE_HANDLE = 2"},

		// Service/method ID constants for ScientificCalculator
		{"sci calc service id", "SERVICE_SCIENTIFIC_CALCULATOR = 2"},
		{"sci calc power method id", "METHOD_SCIENTIFIC_CALCULATOR_POWER = 0"},
		{"sci calc free method id", "METHOD_SCIENTIFIC_CALCULATOR_RELEASE_HANDLE = 1"},

		// Per-method exports replace the old per-service switch
		// dispatchers. Service 0 is the free-function group ("test"
		// here), service 1 is the first handle class (Calculator),
		// service 2 is ScientificCalculator. Method IDs follow
		// proto.go's ordering (constructors → static factories →
		// methods → getters → FromCallback → Free).
		{"free func 0 export", "WASM_EXPORT(w_0_0)"}, // Add
		{"calculator 0 export", "WASM_EXPORT(w_1_0)"}, // first method/ctor
		{"sci calc 0 export", "WASM_EXPORT(w_2_0)"}, // first method

		// Init and shutdown
		{"wasm_init export", "WASM_EXPORT(wasm_init)"},
		{"wasm_shutdown export", "WASM_EXPORT(wasm_shutdown)"},

		// extern C
		{"extern C open", "extern \"C\" {"},
		{"extern C close", "} // extern \"C\""},

		// encode_result helper
		{"encode_result", "static int64_t encode_result(void* ptr, int32_t len)"},
	}

	for _, tc := range checks {
		t.Run(tc.name, func(t *testing.T) {
			if !strings.Contains(output, tc.want) {
				t.Errorf("output missing %q\nGot:\n%s", tc.want, output)
			}
		})
	}

	// Verify wasmify_get_type_name is exported as its own dedicated
	// wasm export for abstract type resolution. The host calls it via
	// `mod.ExportedFunction("wasmify_get_type_name")` instead of going
	// through the old `wasm_invoke(service_id == -1)` sentinel path.
	t.Run("typeid export", func(t *testing.T) {
		if !strings.Contains(output, "WASM_EXPORT(wasmify_get_type_name)") {
			t.Error("bridge should expose wasmify_get_type_name as its own export")
		}
		if !strings.Contains(output, "int64_t wasmify_get_type_name(") {
			t.Error("bridge should declare wasmify_get_type_name as a non-static function")
		}
	})
}

// TestParamVarNameReservedWord tests that paramVarName prefixes reserved names.
func TestParamVarNameReservedWord(t *testing.T) {
	tests := []struct {
		name  string
		param apispec.Param
		idx   int
		want  string
	}{
		{
			name:  "reader is reserved",
			param: apispec.Param{Name: "reader"},
			idx:   0,
			want:  "_param_reader",
		},
		{
			name:  "req is reserved",
			param: apispec.Param{Name: "req"},
			idx:   0,
			want:  "_param_req",
		},
		{
			name:  "method_id is reserved",
			param: apispec.Param{Name: "method_id"},
			idx:   0,
			want:  "_param_method_id",
		},
		{
			name:  "normal name not prefixed",
			param: apispec.Param{Name: "value"},
			idx:   0,
			want:  "value",
		},
		{
			name:  "empty name uses arg index",
			param: apispec.Param{Name: ""},
			idx:   3,
			want:  "arg3",
		},
		{
			name:  "_handle_ptr is reserved",
			param: apispec.Param{Name: "_handle_ptr"},
			idx:   0,
			want:  "_param__handle_ptr",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := paramVarName(tt.param, tt.idx)
			if got != tt.want {
				t.Errorf("paramVarName(%q, %d) = %q, want %q", tt.param.Name, tt.idx, got, tt.want)
			}
		})
	}
}

// TestValueTypeParserSkipsStringPointer guards a generator regression:
// googlesql::ValueEqualityCheckOptions has a `std::string* reason` field.
// The earlier generator emitted `out.reason = reader.read_string();`,
// which tried to assign a std::string to a std::string*. The bridge now
// emits `reader.skip()` for TypeString fields with IsPointer=true.
func TestValueTypeParserSkipsStringPointer(t *testing.T) {
	resetBridgeGenerators()
	src := "test/options.h"
	spec := &apispec.APISpec{
		Namespace: "test",
		Classes: []apispec.Class{
			{
				Name:                 "OutParamBag",
				QualName:             "test::OutParamBag",
				Namespace:            "test",
				IsHandle:             false,
				HasPublicDefaultCtor: true,
				HasPublicDtor:        true,
				Fields: []apispec.Field{
					{Name: "ok", Type: apispec.TypeRef{Name: "bool", Kind: apispec.TypePrimitive}},
					{Name: "reason", Type: apispec.TypeRef{
						Name:      "string",
						Kind:      apispec.TypeString,
						IsPointer: true,
						QualType:  "std::string*",
					}},
				},
				SourceFile: src,
			},
		},
	}
	// Trigger the value-type parser emission.
	recordValueTypeParserNeeded(&spec.Classes[0])
	var b strings.Builder
	writeValueTypeParserDefinitions(&b, spec)
	got := b.String()

	wantSkip := "reader.skip(); // reason: std::string* not bridgeable"
	if !strings.Contains(got, wantSkip) {
		t.Errorf("expected std::string* field to be skipped.\nwant substring: %q\nGot:\n%s", wantSkip, got)
	}
	// Regression: the old buggy assignment must not appear.
	bad := "out.reason = reader.read_string();"
	if strings.Contains(got, bad) {
		t.Errorf("generator still emits invalid assignment for std::string* field:\n%s", got)
	}
}

// resetBridgeGenerators clears the package-level state used by the bridge
// generator so tests that invoke recordValueTypeParserNeeded do not leak
// state into each other.
func resetBridgeGenerators() {
	valueTypeParsers = nil
	valueTypeParsersSeen = map[string]bool{}
}

// TestIsCallbackCandidateForBridge_NonAbstract documents the default
// exclusion of concrete classes — in C++ "concrete + virtuals" is the
// same syntactic shape used both for customisation hooks (subclasses
// expected) and data carriers (visitor pattern), so the generator
// cannot distinguish them structurally. By default a concrete class
// is rejected.
//
// `TestIsCallbackCandidateForBridge_NonAbstractOptIn` covers the
// other half of the contract: a concrete class listed in
// `bridge.CallbackClasses` becomes callback-eligible.
func TestIsCallbackCandidateForBridge_NonAbstract(t *testing.T) {
	prevSrc := classSourceFiles
	prevQual := classQualNames
	prevAbs := classAbstract
	prevNoCtor := classNoDefaultCtor
	prevCfg := bridgeConfig
	classSourceFiles = map[string]string{
		"calc::Counter": "calc/counter.h",
	}
	classQualNames = map[string]string{
		"Counter": "calc::Counter",
	}
	classAbstract = map[string]bool{}
	classNoDefaultCtor = map[string]bool{}
	bridgeConfig = DefaultBridgeConfig()
	defer func() {
		classSourceFiles = prevSrc
		classQualNames = prevQual
		classAbstract = prevAbs
		classNoDefaultCtor = prevNoCtor
		bridgeConfig = prevCfg
	}()

	// Concrete class with a single non-pure virtual. Mirrors the shape
	// of TableValuedFunction.Resolve(): the base class has a usable
	// default implementation, and Go subclasses override it when they
	// need different behaviour.
	c := apispec.Class{
		Name:                 "Counter",
		QualName:             "calc::Counter",
		Namespace:            "calc",
		IsHandle:             true,
		IsAbstract:           false,
		HasPublicDefaultCtor: true,
		HasPublicDtor:        true,
		SourceFile:           "calc/counter.h",
		Methods: []apispec.Function{
			{
				Name:      "next",
				QualName:  "calc::Counter::next",
				IsVirtual: true,
				Access:    "public",
				Params: []apispec.Param{{
					Name: "step",
					Type: apispec.TypeRef{Kind: apispec.TypePrimitive, Name: "int", QualType: "int"},
				}},
				ReturnType: apispec.TypeRef{Kind: apispec.TypePrimitive, Name: "int", QualType: "int"},
			},
		},
	}

	if isCallbackCandidateForBridge(&c) {
		t.Errorf("non-abstract class must NOT be callback-eligible by default; opt-in via wasmify.json:bridge.CallbackClasses is the intended escape hatch")
	}
}

// TestIsCallbackCandidateForBridge_NonAbstractOptIn confirms the
// other half of the contract: when a concrete class is listed in
// `bridge.CallbackClasses`, the predicate accepts it and the
// generator proceeds to emit a callback service. The opt-in does
// not bypass the per-method declarability checks (a class with an
// inherited pure virtual we cannot declare is still rejected
// because the trampoline could not satisfy the vtable).
func TestIsCallbackCandidateForBridge_NonAbstractOptIn(t *testing.T) {
	prevSrc := classSourceFiles
	prevQual := classQualNames
	prevAbs := classAbstract
	prevNoCtor := classNoDefaultCtor
	prevCfg := bridgeConfig
	classSourceFiles = map[string]string{
		"calc::Counter": "calc/counter.h",
	}
	classQualNames = map[string]string{
		"Counter": "calc::Counter",
	}
	classAbstract = map[string]bool{}
	classNoDefaultCtor = map[string]bool{}
	bridgeConfig = DefaultBridgeConfig()
	bridgeConfig.CallbackClasses = []string{"calc::Counter"}
	defer func() {
		classSourceFiles = prevSrc
		classQualNames = prevQual
		classAbstract = prevAbs
		classNoDefaultCtor = prevNoCtor
		bridgeConfig = prevCfg
	}()

	// Same shape as the previous (default-rejected) test, only the
	// CallbackClasses listing differs.
	c := apispec.Class{
		Name:                 "Counter",
		QualName:             "calc::Counter",
		Namespace:            "calc",
		IsHandle:             true,
		IsAbstract:           false,
		HasPublicDefaultCtor: true,
		HasPublicDtor:        true,
		SourceFile:           "calc/counter.h",
		Methods: []apispec.Function{
			{
				Name:      "next",
				QualName:  "calc::Counter::next",
				IsVirtual: true,
				Access:    "public",
				Params: []apispec.Param{{
					Name: "step",
					Type: apispec.TypeRef{Kind: apispec.TypePrimitive, Name: "int", QualType: "int"},
				}},
				ReturnType: apispec.TypeRef{Kind: apispec.TypePrimitive, Name: "int", QualType: "int"},
			},
		},
	}

	if !isCallbackCandidateForBridge(&c) {
		t.Errorf("concrete class listed in CallbackClasses must be callback-eligible")
	}

	// And once the class is removed from the opt-in list it falls back
	// to the default rejection — the listing is the sole gate.
	bridgeConfig.CallbackClasses = nil
	if isCallbackCandidateForBridge(&c) {
		t.Errorf("removing the class from CallbackClasses must restore default rejection")
	}
}

// TestIsCallbackCandidateForBridge_AbstractStillEligible ensures the
// pre-fix behaviour for genuinely abstract classes (one or more pure
// virtuals) keeps working. Without this guard the predicate change
// would risk regressing the existing Catalog / Connection / Logger
// callback surface.
func TestIsCallbackCandidateForBridge_AbstractStillEligible(t *testing.T) {
	prevSrc := classSourceFiles
	prevQual := classQualNames
	prevAbs := classAbstract
	prevNoCtor := classNoDefaultCtor
	prevCfg := bridgeConfig
	classSourceFiles = map[string]string{
		"calc::Logger": "calc/logger.h",
	}
	classQualNames = map[string]string{
		"Logger": "calc::Logger",
	}
	classAbstract = map[string]bool{}
	classNoDefaultCtor = map[string]bool{}
	bridgeConfig = DefaultBridgeConfig()
	defer func() {
		classSourceFiles = prevSrc
		classQualNames = prevQual
		classAbstract = prevAbs
		classNoDefaultCtor = prevNoCtor
		bridgeConfig = prevCfg
	}()

	c := apispec.Class{
		Name:          "Logger",
		QualName:      "calc::Logger",
		Namespace:     "calc",
		IsHandle:      true,
		IsAbstract:    true,
		HasPublicDtor: true,
		SourceFile:    "calc/logger.h",
		Methods: []apispec.Function{
			{
				Name:          "log",
				QualName:      "calc::Logger::log",
				IsVirtual:     true,
				IsPureVirtual: true,
				Access:        "public",
				Params: []apispec.Param{{
					Name: "message",
					Type: apispec.TypeRef{Kind: apispec.TypeString, Name: "string", QualType: "const std::string &"},
				}},
				ReturnType: apispec.TypeRef{Kind: apispec.TypeVoid, Name: "void", QualType: "void"},
			},
		},
	}

	if !isCallbackCandidateForBridge(&c) {
		t.Error("abstract class with a pure-virtual must remain callback-eligible after the predicate change")
	}
}

// TestIsCallbackCandidateForBridge_NoVirtualsRejected confirms that a
// concrete class with no virtual methods at all is still rejected —
// callbacks have no purpose for such classes and emitting one would
// create a dead service in the proto schema.
func TestIsCallbackCandidateForBridge_NoVirtualsRejected(t *testing.T) {
	prevSrc := classSourceFiles
	prevQual := classQualNames
	prevAbs := classAbstract
	prevNoCtor := classNoDefaultCtor
	prevCfg := bridgeConfig
	classSourceFiles = map[string]string{
		"calc::PlainPOD": "calc/pod.h",
	}
	classQualNames = map[string]string{
		"PlainPOD": "calc::PlainPOD",
	}
	classAbstract = map[string]bool{}
	classNoDefaultCtor = map[string]bool{}
	bridgeConfig = DefaultBridgeConfig()
	defer func() {
		classSourceFiles = prevSrc
		classQualNames = prevQual
		classAbstract = prevAbs
		classNoDefaultCtor = prevNoCtor
		bridgeConfig = prevCfg
	}()

	c := apispec.Class{
		Name:                 "PlainPOD",
		QualName:             "calc::PlainPOD",
		Namespace:            "calc",
		IsHandle:             true,
		HasPublicDefaultCtor: true,
		HasPublicDtor:        true,
		SourceFile:           "calc/pod.h",
		Methods: []apispec.Function{
			{
				Name:       "value",
				QualName:   "calc::PlainPOD::value",
				IsVirtual:  false,
				Access:     "public",
				Params:     nil,
				ReturnType: apispec.TypeRef{Kind: apispec.TypePrimitive, Name: "int", QualType: "int"},
			},
		},
	}

	if isCallbackCandidateForBridge(&c) {
		t.Error("class with zero virtuals must not be callback-eligible")
	}
}

func TestGenerateBridgeHeader(t *testing.T) {
	spec := testAPISpec()
	output := GenerateBridgeHeader(spec, "test")

	checks := []struct {
		name string
		want string
	}{
		{"auto-generated comment", "Auto-generated by wasmify gen-proto. DO NOT EDIT."},
		{"header guard ifndef", "#ifndef TEST_API_BRIDGE_H_"},
		{"header guard define", "#define TEST_API_BRIDGE_H_"},
		{"header guard endif", "#endif // TEST_API_BRIDGE_H_"},
		{"include cstdint", "#include <cstdint>"},
		{"wasm_alloc decl", "void* wasm_alloc(int32_t size);"},
		{"wasm_free decl", "void wasm_free(void* ptr);"},
		{"wasm_init decl", "int32_t wasm_init();"},
		{"wasm_shutdown decl", "void wasm_shutdown();"},
		{"extern C", "extern \"C\" {"},
	}

	for _, tc := range checks {
		t.Run(tc.name, func(t *testing.T) {
			if !strings.Contains(output, tc.want) {
				t.Errorf("output missing %q\nGot:\n%s", tc.want, output)
			}
		})
	}
}
