package cache

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

type Phase string

const (
	PhaseAnalyze      Phase = "analyze"
	PhaseClassify     Phase = "classify"
	PhasePrepare      Phase = "prepare"
	PhaseBuild        Phase = "build"
	PhaseOutput       Phase = "output"
	PhaseValidateBuild Phase = "validate-build"
	PhaseWasmBuild     Phase = "wasm-build"
	PhaseParseHeaders  Phase = "parse-headers"
	PhaseGenProto      Phase = "gen-proto"
)

// phaseOrder follows the canonical wasmify flow. wasm-build is deliberately
// last (well, before gen-go) because it depends on both native build
// artefacts AND the Protobuf bridge generated by gen-proto — without the
// bridge a wasm binary is not callable from host code.
var phaseOrder = []Phase{
	PhaseAnalyze,
	PhaseClassify,
	PhasePrepare,
	PhaseBuild,
	PhaseOutput,
	PhaseValidateBuild,
	PhaseParseHeaders,
	PhaseGenProto,
	PhaseWasmBuild,
}

type Cache struct {
	Phase           Phase   `json:"phase"`
	CompletedPhases []Phase `json:"completed_phases"`
	UpdatedAt       string  `json:"updated_at"`
}

func Load(projectDir string) (*Cache, error) {
	path := filepath.Join(projectDir, "cache.json")
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to read cache.json: %w", err)
	}
	var c Cache
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("failed to parse cache.json: %w", err)
	}
	return &c, nil
}

func (c *Cache) Save(projectDir string) error {
	c.UpdatedAt = time.Now().UTC().Format(time.RFC3339)
	path := filepath.Join(projectDir, "cache.json")
	data, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal cache.json: %w", err)
	}
	return os.WriteFile(path, data, 0o644)
}

func (c *Cache) IsCompleted(phase Phase) bool {
	for _, p := range c.CompletedPhases {
		if p == phase {
			return true
		}
	}
	return false
}

func (c *Cache) CompletePhase(phase Phase) {
	if !c.IsCompleted(phase) {
		c.CompletedPhases = append(c.CompletedPhases, phase)
	}
	// Advance to next phase
	for i, p := range phaseOrder {
		if p == phase && i+1 < len(phaseOrder) {
			c.Phase = phaseOrder[i+1]
			return
		}
	}
}

func New() *Cache {
	return &Cache{
		Phase:           PhaseAnalyze,
		CompletedPhases: []Phase{},
		UpdatedAt:       time.Now().UTC().Format(time.RFC3339),
	}
}
