// Code generated by protoc-gen-wasmify-go. DO NOT EDIT.

package simplelib_proto

import (
	_ "embed"

	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unsafe"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

var (
	_ = context.Background
	_ = binary.LittleEndian
	_ = errors.New
	_ = fmt.Errorf
	_ = math.Float32bits
	_ = runtime.SetFinalizer
	_ = sort.Search
	_ = strings.TrimSpace
	_ = strconv.Itoa
	_ = sync.Once{}
	_ = unsafe.Sizeof(byte(0))
	_ = wazero.NewRuntime
	_ = api.ValueType(0)
	_ = wasi_snapshot_preview1.Instantiate
)

// pbAppendVarint appends a varint-encoded uint64.
func pbAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// pbAppendTag appends a field tag.
func pbAppendTag(buf []byte, field, wireType uint32) []byte {
	return pbAppendVarint(buf, uint64(field<<3|wireType))
}

func pbAppendUint64(buf []byte, field uint32, v uint64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, v)
}

func pbAppendInt32(buf []byte, field uint32, v int32) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendInt64(buf []byte, field uint32, v int64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendBool(buf []byte, field uint32, v bool) []byte {
	buf = pbAppendTag(buf, field, 0)
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}

func pbAppendString(buf []byte, field uint32, s string) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(s)))
	return append(buf, s...)
}

func pbAppendBytes(buf []byte, field uint32, data []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(data)))
	return append(buf, data...)
}

func pbAppendFloat(buf []byte, field uint32, v float32) []byte {
	buf = pbAppendTag(buf, field, 5)
	var tmp [4]byte
	binary.LittleEndian.PutUint32(tmp[:], math.Float32bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendDouble(buf []byte, field uint32, v float64) []byte {
	buf = pbAppendTag(buf, field, 1)
	var tmp [8]byte
	binary.LittleEndian.PutUint64(tmp[:], math.Float64bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendSubmessage(buf []byte, field uint32, sub []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(sub)))
	return append(buf, sub...)
}

func pbAppendHandle(buf []byte, field uint32, ptr uint64) []byte {
	sub := pbAppendUint64(nil, 1, ptr)
	return pbAppendSubmessage(buf, field, sub)
}

// pbReader is a streaming protobuf decoder.
type pbReader struct {
	data []byte
	pos  int
}

func (r *pbReader) hasData() bool { return r.pos < len(r.data) }

func (r *pbReader) readVarint() uint64 {
	var v uint64
	var shift uint
	for r.pos < len(r.data) {
		b := r.data[r.pos]
		r.pos++
		v |= uint64(b&0x7f) << shift
		if b < 0x80 {
			return v
		}
		shift += 7
	}
	return v
}

func (r *pbReader) next() (field, wireType uint32, ok bool) {
	if !r.hasData() {
		return 0, 0, false
	}
	tag := r.readVarint()
	return uint32(tag >> 3), uint32(tag & 7), true
}

func (r *pbReader) readString() string {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	s := string(r.data[r.pos : r.pos+n])
	r.pos += n
	return s
}

func (r *pbReader) readBytes() []byte {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	b := make([]byte, n)
	copy(b, r.data[r.pos:r.pos+n])
	r.pos += n
	return b
}

func (r *pbReader) readBool() bool {
	return r.readVarint() != 0
}

func (r *pbReader) readInt32() int32 {
	return int32(r.readVarint())
}

func (r *pbReader) readInt64() int64 {
	return int64(r.readVarint())
}

func (r *pbReader) readUint32() uint32 {
	return uint32(r.readVarint())
}

func (r *pbReader) readUint64() uint64 {
	return r.readVarint()
}

func (r *pbReader) readFloat() float32 {
	if r.pos+4 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint32(r.data[r.pos : r.pos+4])
	r.pos += 4
	return math.Float32frombits(v)
}

func (r *pbReader) readDouble() float64 {
	if r.pos+8 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint64(r.data[r.pos : r.pos+8])
	r.pos += 8
	return math.Float64frombits(v)
}

func (r *pbReader) readSubmessage() *pbReader {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	sub := &pbReader{data: r.data[r.pos : r.pos+n]}
	r.pos += n
	return sub
}

func (r *pbReader) skip(wireType uint32) {
	switch wireType {
	case 0: // varint
		r.readVarint()
	case 1: // 64-bit
		r.pos += 8
	case 2: // length-delimited
		n := int(r.readVarint())
		r.pos += n
	case 5: // 32-bit
		r.pos += 4
	}
	if r.pos > len(r.data) {
		r.pos = len(r.data)
	}
}

// pbExtractError scans a response for field 15 (error string).
func pbExtractError(resp []byte) error {
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 15 {
			return errors.New(r.readString())
		}
		r.skip(w)
	}
	return nil
}

// readHandlePtr reads the ptr from a response. Handles two patterns:
// 1. Direct varint: field 1, wireType 0 → read varint directly
// 2. Submessage: field 1, wireType 2 → read submessage, then field 1 varint inside
func readHandlePtr(data []byte) uint64 {
	r := &pbReader{data: data}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			if w == 0 {
				// Direct varint (constructor pattern)
				return r.readVarint()
			}
			if w == 2 {
				// Submessage (write_handle pattern)
				sub := r.readSubmessage()
				for sf, sw, sok := sub.next(); sok; sf, sw, sok = sub.next() {
					if sf == 1 && sw == 0 {
						return sub.readVarint()
					}
					sub.skip(sw)
				}
			}
			return 0
		}
		r.skip(w)
	}
	return 0
}

// invokeMethod fans the wasm call out into the runtime, then folds in
// the (very common) pbExtractError check on the response. Every per-
// method client wrapper used to repeat the same three lines; this
// helper collapses them to one call.
func invokeMethod(svc, mid int32, req []byte) ([]byte, error) {
	resp, err := module().invoke(svc, mid, req)
	if err != nil {
		return nil, err
	}
	if e := pbExtractError(resp); e != nil {
		return nil, e
	}
	return resp, nil
}

// readPtrAtField returns the handle pointer encoded at response field f.
// f == 1 takes the fast path via readHandlePtr (which already handles
// both the direct-varint constructor shape and the submessage write_handle
// shape); other fields are walked once to find the correct submessage.
// Returns 0 if the field is not present, which is the standard "absent
// handle" sentinel — callers translate that to (nil, nil).
func readPtrAtField(resp []byte, f uint32) uint64 {
	if f == 1 {
		return readHandlePtr(resp)
	}
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			if w == 2 {
				sub := pr.readSubmessage()
				return readHandlePtr(sub.data)
			}
			return 0
		}
		pr.skip(w)
	}
	return 0
}

// decodeChildHandle is the standard accessor-return shape. It reads
// the handle pointer at field f, returns nil for missing/zero, and
// otherwise constructs the child via ctor and pins the parent (owner)
// onto it via setKeepAlive when owner is non-nil. Constructor-style
// callers (free functions) pass owner=nil; accessors pass the
// receiver. The child must already implement the unexported keepAlive
// interface, which every generated handle struct does.
func decodeChildHandle[T any](resp []byte, field uint32, owner any, ctor func(uint64) *T) *T {
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return nil
	}
	child := ctor(ptr)
	if owner != nil {
		if ka, ok := any(child).(interface{ setKeepAlive(any) }); ok {
			ka.setKeepAlive(owner)
		}
	}
	return child
}

// decodeAbstractAs is the abstract-return counterpart of
// decodeChildHandle: read field f, look up the runtime concrete type
// via resolveAbstractHandle, type-assert to I, attach keepAlive when
// owner is non-nil. ifaceName is only used in the error message when
// the runtime type does not satisfy I (which is a real bug, not a
// "missing field" condition).
func decodeAbstractAs[I any](resp []byte, field uint32, owner any, ifaceName string) (I, error) {
	var z I
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return z, nil
	}
	resolved, err := resolveAbstractHandle(ptr)
	if err != nil {
		return z, err
	}
	if v, ok := resolved.(I); ok {
		if owner != nil {
			if ka, okKA := any(v).(interface{ setKeepAlive(any) }); okKA {
				ka.setKeepAlive(owner)
			}
		}
		return v, nil
	}
	return z, fmt.Errorf("resolved type %T does not implement %s", resolved, ifaceName)
}

// readScalarAtField walks resp once for field f and reads the value via
// the read closure. Missing field returns the zero value. The closure is
// always one of (*pbReader).readBool / readInt32 / readInt64 / readUint32
// / readUint64 / readFloat / readDouble / readString / readBytes - small
// values, but they fold the per-method scan-and-read loop into one call
// site.
func readScalarAtField[T any](resp []byte, f uint32, read func(*pbReader) T) T {
	var z T
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			return read(pr)
		}
		pr.skip(w)
	}
	return z
}

// factoryFor curries a typed constructor (newXNoFinalizer) into the
// untyped factory shape stored in cppTypeFactories. Without it the
// generated cppTypeToGoType map had to repeat
//
//	"googlesql::Foo": func(ptr uint64) any { return newFooNoFinalizer(ptr) }
//
// per concrete type — ~1,400 structurally-identical closures.
func factoryFor[T any](ctor func(uint64) *T) func(uint64) any {
	return func(ptr uint64) any { return ctor(ptr) }
}

// enumString backs the per-enum String() methods. Generated code emits
// parallel _vals_<E> []int32 and _names_<E> []string slices keyed in
// canonical order; this helper does a linear scan and falls back to
// the decimal form for values that aren't in the table (forward
// compatibility when new values land before regeneration).
func enumString(v int32, vals []int32, names []string) string {
	for i, x := range vals {
		if x == v {
			return names[i]
		}
	}
	return strconv.Itoa(int(v))
}

var _ = errors.New
var _ = binary.LittleEndian
var _ = fmt.Errorf
var _ = math.Float32bits
var _ = strconv.Itoa

// embeddedWasm is the wasm binary that backs every API call in this
// package. The plugin emits a //go:embed directive whose filename
// matches the Go package name (e.g. `googlesql.wasm` for package
// `googlesql`); ship that file alongside the generated sources so
// `go build` can resolve the embed at compile time.
//
//go:embed simplelib_proto.wasm
var embeddedWasm []byte

// Module wraps a wazero wasm module with auto-generated bridge methods.
//
// The wasm bridge exposes one wasm export per (service, method) pair
// (named `w_<svc>_<mid>`) instead of routing through a single
// `wasm_invoke` dispatcher. exportFns caches the looked-up
// `api.Function` keyed by serviceID<<32 | methodID so the per-call
// overhead is one map read after the first invocation.
type Module struct {
	mu               sync.Mutex
	runtime          wazero.Runtime
	mod              api.Module
	allocFn          api.Function
	freeFn           api.Function
	typeNameFn       api.Function
	exportFns        map[uint64]api.Function
	callbacks        map[int32]CallbackHandler
	nextCBID         int32
	compilationCache wazero.CompilationCache // owned; closed in Close()
}

var (
	globalModule *Module
	initOnce     sync.Once
	initErr      error
)

// Option configures the wasm runtime.
type Option func(*options)
type options struct {
	compilationMode     CompilationMode
	compilationCacheDir string
}

// CompilationMode selects the wazero execution engine.
type CompilationMode int

const (
	// CompilationModeInterpreter uses the wazero interpreter (default).
	CompilationModeInterpreter CompilationMode = iota
	// CompilationModeCompiler uses the wazero compiler for faster execution.
	CompilationModeCompiler
)

// WithCompilationMode sets the wazero compilation mode.
func WithCompilationMode(mode CompilationMode) Option {
	return func(o *options) { o.compilationMode = mode }
}

// WithCompilationCache enables the wazero on-disk compilation cache
// rooted at dir. The first Init() call with a fresh dir pays the
// compile-from-bytes cost; every subsequent process pointed at the
// same dir starts up substantially faster because the precompiled
// module bytes are served straight from disk.
//
// Only honored when CompilationMode is CompilationModeCompiler — the
// interpreter does no AOT compile and so has nothing to cache; the
// option is silently ignored in that case rather than panicking, so
// callers can flip CompilationMode without rewriting their option
// list. The directory is created (mkdir -p) on first use.
//
// The cache's lifecycle is owned internally: Init constructs it,
// Close (or program exit) flushes and closes it. An empty dir is
// treated as "no cache" — the cache directory must be a valid path
// that the process can read and write.
func WithCompilationCache(dir string) Option {
	return func(o *options) { o.compilationCacheDir = dir }
}

// CallbackHandler is implemented by Go types that need to be called from C++.
// The C++ bridge calls wasmify_callback_invoke(callbackID, methodID, reqPtr, reqLen),
// which dispatches to the registered handler.
type CallbackHandler interface {
	HandleCallback(methodID int32, req []byte) ([]byte, error)
}

// RegisterCallback registers a Go callback handler and returns its ID.
// The ID can be passed to C++ as a handle pointer for callback dispatch.
func RegisterCallback(handler CallbackHandler) int32 {
	m := module()
	if m.callbacks == nil {
		m.callbacks = make(map[int32]CallbackHandler)
	}
	m.nextCBID++
	id := m.nextCBID
	m.callbacks[id] = handler
	return id
}

// UnregisterCallback removes a previously registered callback handler.
func UnregisterCallback(id int32) {
	module().callbacks[id] = nil
	delete(module().callbacks, id)
}

func (m *Module) handleCallback(callbackID, methodID, reqPtr, reqLen int32) int64 {
	handler, ok := m.callbacks[callbackID]
	if !ok {
		return 0
	}
	var req []byte
	if reqLen > 0 {
		req, _ = m.mod.Memory().Read(uint32(reqPtr), uint32(reqLen))
		// Copy to avoid referencing wasm memory after return
		buf := make([]byte, len(req))
		copy(buf, req)
		req = buf
	}
	resp, err := handler.HandleCallback(methodID, req)
	if err != nil {
		// Encode error response
		resp = pbAppendString(nil, 15, err.Error())
	}
	if len(resp) == 0 {
		return 0
	}
	// Write response to wasm memory
	ctx := context.Background()
	results, callErr := m.allocFn.Call(ctx, uint64(len(resp)))
	if callErr != nil || len(results) == 0 {
		return 0
	}
	ptr := results[0]
	m.mod.Memory().Write(uint32(ptr), resp)
	return int64(ptr)<<32 | int64(len(resp))
}

// envStub returns a GoModuleFunction for an unresolved env import.
// Most functions return zeros, but some require specific behavior
// for the wasm module to initialize correctly. The patterns below
// handle standard C++ runtime functions (__cxa_*) and common thread
// primitives that any C++ project compiled to wasm may import.
func envStub(m *Module, name string, params, results []api.ValueType) api.GoModuleFunction {
	switch {
	case strings.Contains(name, "SemWait") || strings.Contains(name, "sem_wait"):
		// Thread semaphore wait — return success (1) since wasm is single-threaded.
		return semWaitStub{}
	case strings.Contains(name, "allocate_exception"):
		// C++ exception allocation (__cxa_allocate_exception) — allocate from wasm memory.
		return &cxaAllocExceptionStub{module: m}
	case strings.Contains(name, "__cxa_throw") || strings.HasSuffix(name, "_throw"):
		// C++ throw — abort since we can't unwind in wasm.
		return cxaThrowStub{}
	default:
		return defaultStub{results: results}
	}
}

type defaultStub struct{ results []api.ValueType }

func (s defaultStub) Call(_ context.Context, _ api.Module, stack []uint64) {
	for i := range stack {
		if i < len(s.results) {
			stack[i] = 0
		}
	}
}

type semWaitStub struct{}

func (semWaitStub) Call(_ context.Context, _ api.Module, stack []uint64) {
	// Return true (success) — wasm is single-threaded, no wait needed.
	if len(stack) > 0 {
		stack[0] = 1
	}
}

type cxaAllocExceptionStub struct{ module *Module }

func (s *cxaAllocExceptionStub) Call(ctx context.Context, mod api.Module, stack []uint64) {
	// Allocate exception object in wasm memory.
	size := stack[0]
	if size == 0 {
		size = 64
	}
	if s.module.allocFn != nil {
		results, err := s.module.allocFn.Call(ctx, size)
		if err == nil && len(results) > 0 {
			stack[0] = results[0]
			return
		}
	}
	stack[0] = 0
}

type cxaThrowStub struct{}

func (cxaThrowStub) Call(_ context.Context, _ api.Module, _ []uint64) {
	panic("C++ exception thrown in wasm")
}

// Init initializes the global module from the embedded wasm binary.
// Must be called before any API use. Safe to call multiple times
// (uses sync.Once).
func Init(opts ...Option) error {
	initOnce.Do(func() {
		o := &options{}
		for _, opt := range opts {
			opt(o)
		}
		initErr = initModule(embeddedWasm, o)
	})
	return initErr
}

// Close shuts down the global module. Optional — for clean shutdown.
// Releases the wazero runtime and, if WithCompilationCache was used,
// flushes and closes the underlying on-disk cache so any in-flight
// writes land before the process exits. Both teardown steps always
// run; if either fails, errors.Join surfaces both so the caller can
// see (and react to) all the failures, not just the first.
func Close() error {
	if globalModule == nil {
		return nil
	}
	ctx := context.Background()
	rtErr := globalModule.runtime.Close(ctx)
	var cacheErr error
	if globalModule.compilationCache != nil {
		cacheErr = globalModule.compilationCache.Close(ctx)
		globalModule.compilationCache = nil
	}
	return errors.Join(rtErr, cacheErr)
}

// module returns the initialized global module. Panics if Init was not called.
func module() *Module {
	if globalModule == nil {
		panic("wasmify: Init() must be called before using any API")
	}
	return globalModule
}

func initModule(wasmBytes []byte, o *options) error {
	ctx := context.Background()
	var cfg wazero.RuntimeConfig
	switch o.compilationMode {
	case CompilationModeCompiler:
		cfg = wazero.NewRuntimeConfigCompiler()
	default:
		cfg = wazero.NewRuntimeConfigInterpreter()
	}
	// CompilationCache is a Compiler-only feature; the interpreter
	// never produces machine code and would not consult the cache,
	// so silently dropping the option there avoids wazero panicking
	// on a config it can't honor.
	var compilationCache wazero.CompilationCache
	if o.compilationCacheDir != "" && o.compilationMode == CompilationModeCompiler {
		c, err := wazero.NewCompilationCacheWithDir(o.compilationCacheDir)
		if err != nil {
			return fmt.Errorf("compilation cache %q: %w", o.compilationCacheDir, err)
		}
		compilationCache = c
		cfg = cfg.WithCompilationCache(c)
	}
	r := wazero.NewRuntimeWithConfig(ctx, cfg)
	wasi_snapshot_preview1.MustInstantiate(ctx, r)
	m := &Module{runtime: r, compilationCache: compilationCache}
	// Register the "wasmify" host module with callback_invoke.
	wasmifyMod := r.NewHostModuleBuilder("wasmify")
	wasmifyMod.NewFunctionBuilder().
		WithFunc(func(ctx context.Context, callbackID, methodID int32, reqPtr, reqLen int32) int64 {
			return m.handleCallback(callbackID, methodID, reqPtr, reqLen)
		}).
		Export("callback_invoke")
	if _, err := wasmifyMod.Instantiate(ctx); err != nil {
		r.Close(ctx)
		return fmt.Errorf("wasmify host module: %w", err)
	}
	// Register stub "env" module for unresolved symbols.
	compiled, err := r.CompileModule(ctx, wasmBytes)
	if err != nil {
		r.Close(ctx)
		return fmt.Errorf("wasm compile: %w", err)
	}
	envBuilder := r.NewHostModuleBuilder("env")
	for _, imp := range compiled.ImportedFunctions() {
		modName, fnName, _ := imp.Import()
		if modName != "env" {
			continue
		}
		params := imp.ParamTypes()
		results := imp.ResultTypes()
		envBuilder.NewFunctionBuilder().
			WithGoModuleFunction(envStub(m, fnName, params, results), params, results).
			Export(fnName)
	}
	if _, err := envBuilder.Instantiate(ctx); err != nil {
		r.Close(ctx)
		return fmt.Errorf("env stub module: %w", err)
	}
	// Instantiate as reactor (don't call _start) since the wasm is a library.
	// Mount the root filesystem so wasm can access timezone data, etc.
	modConfig := wazero.NewModuleConfig().
		WithStartFunctions().
		WithFSConfig(wazero.NewFSConfig().WithDirMount("/", "/"))
	mod, err := r.InstantiateWithConfig(ctx, wasmBytes, modConfig)
	if err != nil {
		r.Close(ctx)
		return fmt.Errorf("wasm instantiate: %w", err)
	}
	allocFn := mod.ExportedFunction("wasm_alloc")
	freeFn := mod.ExportedFunction("wasm_free")
	if allocFn == nil || freeFn == nil {
		r.Close(ctx)
		return fmt.Errorf("wasm module missing required exports (wasm_alloc, wasm_free)")
	}
	// Call _initialize (wasi reactor init) to run C++ global constructors.
	if initializeFn := mod.ExportedFunction("_initialize"); initializeFn != nil {
		if _, err := initializeFn.Call(ctx); err != nil {
			r.Close(ctx)
			return fmt.Errorf("_initialize: %w", err)
		}
	}
	if initFn := mod.ExportedFunction("wasm_init"); initFn != nil {
		if _, err := initFn.Call(ctx); err != nil {
			r.Close(ctx)
			return fmt.Errorf("wasm_init: %w", err)
		}
	}
	m.mod = mod
	m.allocFn = allocFn
	m.freeFn = freeFn
	// wasmify_get_type_name is the runtime-typeid helper invoked when
	// abstract returns must be downcast to a concrete Go type. Cache it
	// at startup so dispatch sites don't repeat the lookup.
	m.typeNameFn = mod.ExportedFunction("wasmify_get_type_name")
	m.exportFns = make(map[uint64]api.Function)
	globalModule = m
	return nil
}

// invoke calls the wasm export for (serviceID, methodID), serializing
// req into wasm memory and unpacking the (ptr<<32 | len) response.
// Each (svc, mid) pair has its own export named `w_<svc>_<mid>` and the
// looked-up api.Function is cached after the first call.
func (m *Module) invoke(serviceID, methodID int32, req []byte) ([]byte, error) {
	fn, err := m.exportFor(serviceID, methodID)
	if err != nil {
		return nil, err
	}
	return m.callExport(fn, req)
}

// exportFor returns the cached api.Function for (serviceID, methodID),
// performing a one-time mod.ExportedFunction lookup if absent.
func (m *Module) exportFor(serviceID, methodID int32) (api.Function, error) {
	key := uint64(uint32(serviceID))<<32 | uint64(uint32(methodID))
	m.mu.Lock()
	if fn, ok := m.exportFns[key]; ok {
		m.mu.Unlock()
		return fn, nil
	}
	m.mu.Unlock()
	name := fmt.Sprintf("w_%d_%d", serviceID, methodID)
	fn := m.mod.ExportedFunction(name)
	if fn == nil {
		return nil, fmt.Errorf("wasm export %q not found", name)
	}
	m.mu.Lock()
	m.exportFns[key] = fn
	m.mu.Unlock()
	return fn, nil
}

// callExport copies req into wasm memory, calls fn, and reads back the
// packed response. Holds the runtime lock for the duration of the wasm
// call to keep the underlying memory writes atomic w.r.t. the
// callback invoke path.
func (m *Module) callExport(fn api.Function, req []byte) ([]byte, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	ctx := context.Background()
	var reqPtr, reqLen uint64
	if len(req) > 0 {
		results, err := m.allocFn.Call(ctx, uint64(len(req)))
		if err != nil {
			return nil, fmt.Errorf("wasm_alloc: %w", err)
		}
		reqPtr = results[0]
		reqLen = uint64(len(req))
		if !m.mod.Memory().Write(uint32(reqPtr), req) {
			return nil, fmt.Errorf("failed to write request to wasm memory")
		}
	}
	results, err := fn.Call(ctx, reqPtr, reqLen)
	if err != nil {
		return nil, fmt.Errorf("wasm export call: %w", err)
	}
	packed := results[0]
	respPtr := uint32(packed >> 32)
	respLen := uint32(packed & 0xFFFFFFFF)
	if respLen == 0 {
		return nil, nil
	}
	resp, ok := m.mod.Memory().Read(respPtr, respLen)
	if !ok {
		return nil, fmt.Errorf("failed to read response from wasm memory")
	}
	out := make([]byte, len(resp))
	copy(out, resp)
	m.freeFn.Call(ctx, uint64(respPtr))
	if reqPtr != 0 {
		m.freeFn.Call(ctx, reqPtr)
	}
	return out, nil
}

// resolveTypeName calls the C++ bridge to get the runtime type name
// of an object pointed to by ptr. Returns a fully qualified C++ class name
// like "ns::ASTQueryStatement".
func (m *Module) resolveTypeName(ptr uint64) (string, error) {
	if m.typeNameFn == nil {
		return "", fmt.Errorf("wasm export %q not found", "wasmify_get_type_name")
	}
	buf := pbAppendUint64(nil, 1, ptr)
	resp, err := m.callExport(m.typeNameFn, buf)
	if err != nil {
		return "", err
	}
	if e := pbExtractError(resp); e != nil {
		return "", e
	}
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			return r.readString(), nil
		}
		r.skip(w)
	}
	return "", nil
}

var _ = fmt.Errorf
var _ = strings.HasPrefix
var _ = fmt.Errorf
var _ = sort.Search

// Abstract interface that users can implement from Go. The bridge emits a
// trampoline that dispatches each pure-virtual through the callback wire
// (wasmify_callback_invoke) so a Go type can satisfy the C++ vtable.
type LoggerNode interface {
	rawPtr() uint64
	isLogger()
	Level() (int32, error)
	Log(message string) error
}

// (A) Abstract base for downcast-via-assertion test.
type ShapeNode interface {
	rawPtr() uint64
	isShape()
	Area() (float64, error)
}

// TextNode / HeadingNode regression-test the abstract-handle naming
// rule. TextNode itself ends in "Node", so the generator must emit the
// Go interface as `TextNode` (not the doubled `TextNodeNode`) and
// rename the abstract struct to `TextNodeBase` so it does not collide
// with the interface. HeadingNode is a concrete descendant whose struct
// embeds `*TextNodeBase`.
type TextNode interface {
	rawPtr() uint64
	isTextNode()
	Render() (string, error)
}

// cppTypeNames / cppTypeFactories: parallel sorted slices replacing
// the old cppTypeToGoType map literal. Looked up via sort.Search.
var cppTypeNames = []string{
	"calc::Animal",
	"calc::Calculator",
	"calc::Canine",
	"calc::Circle",
	"calc::Dog",
	"calc::HeadingNode",
	"calc::Mammal",
	"calc::ManagedFactory",
	"calc::ManagedValue",
	"calc::Named",
	"calc::Priced",
	"calc::Product",
	"calc::ScientificCalculator",
	"calc::ShapeBox",
	"calc::Square",
	"calc::StatefulCounter",
}

var cppTypeFactories = []func(uint64) any{
	factoryFor(newAnimalNoFinalizer),
	factoryFor(newCalculatorNoFinalizer),
	factoryFor(newCanineNoFinalizer),
	factoryFor(newCircleNoFinalizer),
	factoryFor(newDogNoFinalizer),
	factoryFor(newHeadingNodeNoFinalizer),
	factoryFor(newMammalNoFinalizer),
	factoryFor(newManagedFactoryNoFinalizer),
	factoryFor(newManagedValueNoFinalizer),
	factoryFor(newNamedNoFinalizer),
	factoryFor(newPricedNoFinalizer),
	factoryFor(newProductNoFinalizer),
	factoryFor(newScientificCalculatorNoFinalizer),
	factoryFor(newShapeBoxNoFinalizer),
	factoryFor(newSquareNoFinalizer),
	factoryFor(newStatefulCounterNoFinalizer),
}

// resolveAbstractHandle queries the C++ runtime for the actual type of the
// object at ptr and returns the appropriate concrete Go handle type.
func resolveAbstractHandle(ptr uint64) (any, error) {
	typeName, err := module().resolveTypeName(ptr)
	if err != nil {
		return nil, fmt.Errorf("resolveTypeName: %w", err)
	}
	i := sort.SearchStrings(cppTypeNames, typeName)
	if i < len(cppTypeNames) && cppTypeNames[i] == typeName {
		return cppTypeFactories[i](ptr), nil
	}
	return nil, fmt.Errorf("unknown C++ type %q for ptr 0x%x", typeName, ptr)
}

type Value int32

const (
	ValueStart Value = 2
	ValueEnd   Value = 3
)

var _vals_Value = []int32{2, 3}
var _names_Value = []string{"ValueStart", "ValueEnd"}

func (e Value) String() string { return enumString(int32(e), _vals_Value, _names_Value) }

type AnchorRaw int32

const (
	AnchorRawAnchorUnspecified AnchorRaw = 1
	AnchorRawStart             AnchorRaw = 2
	AnchorRawEnd               AnchorRaw = 3
)

var _vals_AnchorRaw = []int32{1, 2, 3}
var _names_AnchorRaw = []string{"AnchorRawAnchorUnspecified", "AnchorRawStart", "AnchorRawEnd"}

func (e AnchorRaw) String() string { return enumString(int32(e), _vals_AnchorRaw, _names_AnchorRaw) }

// Implicit enum exercises the auto-increment fallback: clang emits no
// ConstantExpr for `A`, `B`, `C` because there is no `= N` initialiser,
// so the parser must compute prev+1 to recover 0, 1, 2.
type ImplicitColor int32

const (
	ImplicitColorImplicitRed   ImplicitColor = 1
	ImplicitColorImplicitGreen ImplicitColor = 2
	ImplicitColorImplicitBlue  ImplicitColor = 3
)

var _vals_ImplicitColor = []int32{1, 2, 3}
var _names_ImplicitColor = []string{"ImplicitColorImplicitRed", "ImplicitColorImplicitGreen", "ImplicitColorImplicitBlue"}

func (e ImplicitColor) String() string {
	return enumString(int32(e), _vals_ImplicitColor, _names_ImplicitColor)
}

// Simple enum for operations
type Operation int32

const (
	OperationAdd      Operation = 1
	OperationSubtract Operation = 2
	OperationMultiply Operation = 3
	OperationDivide   Operation = 4
)

var _vals_Operation = []int32{1, 2, 3, 4}
var _names_Operation = []string{"OperationAdd", "OperationSubtract", "OperationMultiply", "OperationDivide"}

func (e Operation) String() string { return enumString(int32(e), _vals_Operation, _names_Operation) }

type Result struct {
	ErrorMessage string
	Ok           bool
	Value        float64
}

func (v *Result) marshal() []byte {
	if v == nil {
		return nil
	}
	var buf []byte
	buf = pbAppendString(buf, 1, v.ErrorMessage)
	buf = pbAppendBool(buf, 2, v.Ok)
	buf = pbAppendDouble(buf, 3, v.Value)
	return buf
}

func unmarshalResult(data []byte) *Result {
	v := &Result{}
	pr := &pbReader{data: data}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		switch f {
		case 1:
			v.ErrorMessage = pr.readString()
		case 2:
			v.Ok = pr.readBool()
		case 3:
			v.Value = pr.readDouble()
		default:
			pr.skip(w)
		}
	}
	return v
}

var _ = fmt.Errorf
var _ = runtime.SetFinalizer

type LoggerCallback interface {
	Level() (int32, error)
	Log(message string) error
}

type LoggerCallbackDefaults struct{}

func (LoggerCallbackDefaults) Level() (int32, error)    { return 0, nil }
func (LoggerCallbackDefaults) Log(message string) error { return nil }

type loggerCallbackAdapter struct {
	impl LoggerCallback
}

func (a *loggerCallbackAdapter) HandleCallback(methodID int32, req []byte) ([]byte, error) {
	switch methodID {
	case 0: // Level
		_v, err := a.impl.Level()
		if err != nil {
			return nil, err
		}
		var _out []byte
		_out = pbAppendInt32(_out, 1, _v)
		return _out, nil
	case 1: // Log
		var message string
		_r := &pbReader{data: req}
		for _f, _w, _ok := _r.next(); _ok; _f, _w, _ok = _r.next() {
			switch _f {
			case 1:
				message = _r.readString()
			default:
				_r.skip(_w)
			}
		}
		err := a.impl.Log(message)
		if err != nil {
			return nil, err
		}
		return nil, nil
	}
	return nil, fmt.Errorf("unknown callback method %d", methodID)
}

type ShapeCallback interface {
	Area() (float64, error)
}

type ShapeCallbackDefaults struct{}

func (ShapeCallbackDefaults) Area() (float64, error) { return 0, nil }

type shapeCallbackAdapter struct {
	impl ShapeCallback
}

func (a *shapeCallbackAdapter) HandleCallback(methodID int32, req []byte) ([]byte, error) {
	switch methodID {
	case 0: // Area
		_v, err := a.impl.Area()
		if err != nil {
			return nil, err
		}
		var _out []byte
		_out = pbAppendDouble(_out, 1, _v)
		return _out, nil
	}
	return nil, fmt.Errorf("unknown callback method %d", methodID)
}

type TextNodeCallback interface {
	Render() (string, error)
}

type TextNodeCallbackDefaults struct{}

func (TextNodeCallbackDefaults) Render() (string, error) { return "", nil }

type textNodeCallbackAdapter struct {
	impl TextNodeCallback
}

func (a *textNodeCallbackAdapter) HandleCallback(methodID int32, req []byte) ([]byte, error) {
	switch methodID {
	case 0: // Render
		_v, err := a.impl.Render()
		if err != nil {
			return nil, err
		}
		var _out []byte
		_out = pbAppendString(_out, 1, _v)
		return _out, nil
	}
	return nil, fmt.Errorf("unknown callback method %d", methodID)
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

// (B) Multi-level chain. Every accessor defined at each level must be
// callable directly on the leaf Dog handle.
type Animal struct {
	ptr       uint64
	keepAlive []any
}

func (h *Animal) rawPtr() uint64 { return h.ptr }

func (h *Animal) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newAnimal(ptr uint64) *Animal {
	h := &Animal{ptr: ptr}
	runtime.SetFinalizer(h, (*Animal).free)
	return h
}

func newAnimalNoFinalizer(ptr uint64) *Animal {
	h := &Animal{ptr: ptr}
	return h
}

func (h *Animal) SetSpecies(s string) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendString(buf, 2, s)
	_, err := invokeMethod(1, 0, buf)
	return err
}

func (h *Animal) Species() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(1, 1, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func (h *Animal) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(1, 2, buf)
		h.ptr = 0
	}
}

// Calculator class with methods and inheritance
type Calculator struct {
	ptr       uint64
	keepAlive []any
}

func (h *Calculator) rawPtr() uint64 { return h.ptr }

func (h *Calculator) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newCalculator(ptr uint64) *Calculator {
	h := &Calculator{ptr: ptr}
	runtime.SetFinalizer(h, (*Calculator).free)
	return h
}

func newCalculatorNoFinalizer(ptr uint64) *Calculator {
	h := &Calculator{ptr: ptr}
	return h
}

func NewCalculator() (*Calculator, error) {
	var buf []byte
	resp, err := invokeMethod(2, 0, buf)
	if err != nil {
		return nil, err
	}
	return newCalculator(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

// History
func (h *Calculator) AddToHistory(value float64) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendDouble(buf, 2, value)
	_, err := invokeMethod(2, 1, buf)
	return err
}

func (h *Calculator) ClearHistory() error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	_, err := invokeMethod(2, 2, buf)
	return err
}

// Basic operations
func (h *Calculator) Compute(op Operation, a float64, b float64) (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, int32(op))
	buf = pbAppendDouble(buf, 3, a)
	buf = pbAppendDouble(buf, 4, b)
	resp, err := invokeMethod(2, 3, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Calculator) ComputeSafe(op Operation, a float64, b float64) (*Result, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, int32(op))
	buf = pbAppendDouble(buf, 3, a)
	buf = pbAppendDouble(buf, 4, b)
	resp, err := invokeMethod(2, 4, buf)
	if err != nil {
		return nil, err
	}
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f == 1 {
			sub := pr.readSubmessage()
			return unmarshalResult(sub.data), nil
		} else {
			pr.skip(w)
		}
	}
	return nil, nil
}

func (h *Calculator) GetHistory() ([]float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(2, 5, buf)
	if err != nil {
		return nil, err
	}
	var items []float64
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f != 1 {
			pr.skip(w)
			continue
		}
		if w == 2 {
			sub := pr.readSubmessage()
			for sub.hasData() {
				items = append(items, sub.readDouble())
			}
			continue
		}
		items = append(items, pr.readDouble())
	}
	return items, nil
}

// Name
func (h *Calculator) Name() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(2, 6, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func (h *Calculator) SetName(name string) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendString(buf, 2, name)
	_, err := invokeMethod(2, 7, buf)
	return err
}

func (h *Calculator) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(2, 8, buf)
		h.ptr = 0
	}
}

type Canine struct {
	*Mammal
}

func newCanine(ptr uint64) *Canine {
	h := &Canine{
		Mammal: newMammalNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Canine).free)
	return h
}

func newCanineNoFinalizer(ptr uint64) *Canine {
	h := &Canine{
		Mammal: newMammalNoFinalizer(ptr),
	}
	return h
}

func (h *Canine) Breed() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(3, 0, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func (h *Canine) SetBreed(b string) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendString(buf, 2, b)
	_, err := invokeMethod(3, 1, buf)
	return err
}

func (h *Canine) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(3, 2, buf)
		h.ptr = 0
	}
}

type Circle struct {
	*Shape
}

func newCircle(ptr uint64) *Circle {
	h := &Circle{
		Shape: newShapeNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Circle).free)
	return h
}

func newCircleNoFinalizer(ptr uint64) *Circle {
	h := &Circle{
		Shape: newShapeNoFinalizer(ptr),
	}
	return h
}

func NewCircle(r float64) (*Circle, error) {
	var buf []byte
	buf = pbAppendDouble(buf, 1, r)
	resp, err := invokeMethod(4, 0, buf)
	if err != nil {
		return nil, err
	}
	return newCircle(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *Circle) Area() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(4, 1, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Circle) Radius() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(4, 2, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Circle) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(4, 3, buf)
		h.ptr = 0
	}
}

type Dog struct {
	*Canine
}

func newDog(ptr uint64) *Dog {
	h := &Dog{
		Canine: newCanineNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Dog).free)
	return h
}

func newDogNoFinalizer(ptr uint64) *Dog {
	h := &Dog{
		Canine: newCanineNoFinalizer(ptr),
	}
	return h
}

func NewDog() (*Dog, error) {
	var buf []byte
	resp, err := invokeMethod(5, 0, buf)
	if err != nil {
		return nil, err
	}
	return newDog(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *Dog) BarkVolume() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(5, 1, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *Dog) SetBarkVolume(v int32) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, v)
	_, err := invokeMethod(5, 2, buf)
	return err
}

func (h *Dog) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(5, 3, buf)
		h.ptr = 0
	}
}

type HeadingNode struct {
	*TextNodeBase
}

func newHeadingNode(ptr uint64) *HeadingNode {
	h := &HeadingNode{
		TextNodeBase: newTextNodeBaseNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*HeadingNode).free)
	return h
}

func newHeadingNodeNoFinalizer(ptr uint64) *HeadingNode {
	h := &HeadingNode{
		TextNodeBase: newTextNodeBaseNoFinalizer(ptr),
	}
	return h
}

func NewHeadingNode(level int32, text string) (*HeadingNode, error) {
	var buf []byte
	buf = pbAppendInt32(buf, 1, level)
	buf = pbAppendString(buf, 2, text)
	resp, err := invokeMethod(6, 0, buf)
	if err != nil {
		return nil, err
	}
	return newHeadingNode(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *HeadingNode) Render() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(6, 1, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func (h *HeadingNode) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(6, 2, buf)
		h.ptr = 0
	}
}

// Abstract interface that users can implement from Go. The bridge emits a
// trampoline that dispatches each pure-virtual through the callback wire
// (wasmify_callback_invoke) so a Go type can satisfy the C++ vtable.
type Logger struct {
	ptr       uint64
	keepAlive []any
}

func (h *Logger) rawPtr() uint64 { return h.ptr }

func (h *Logger) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func (*Logger) isLogger() {}

func newLogger(ptr uint64) *Logger {
	h := &Logger{ptr: ptr}
	runtime.SetFinalizer(h, (*Logger).free)
	return h
}

func newLoggerNoFinalizer(ptr uint64) *Logger {
	h := &Logger{ptr: ptr}
	return h
}

func (h *Logger) Level() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(7, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *Logger) Log(message string) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendString(buf, 2, message)
	_, err := invokeMethod(7, 1, buf)
	return err
}

func NewLoggerFromImpl(impl LoggerCallback) (*Logger, error) {
	adapter := &loggerCallbackAdapter{impl: impl}
	id := RegisterCallback(adapter)
	var buf []byte
	buf = pbAppendInt32(buf, 1, id)
	resp, err := invokeMethod(7, 2, buf)
	if err != nil {
		UnregisterCallback(id)
		return nil, err
	}
	h := newLogger(readScalarAtField(resp, 1, (*pbReader).readUint64))
	runtime.SetFinalizer(h, nil)
	runtime.SetFinalizer(h, func(h *Logger) { h.free(); UnregisterCallback(id) })
	return h, nil
}

func (h *Logger) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(7, 3, buf)
		h.ptr = 0
	}
}

type Mammal struct {
	*Animal
}

func newMammal(ptr uint64) *Mammal {
	h := &Mammal{
		Animal: newAnimalNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Mammal).free)
	return h
}

func newMammalNoFinalizer(ptr uint64) *Mammal {
	h := &Mammal{
		Animal: newAnimalNoFinalizer(ptr),
	}
	return h
}

func (h *Mammal) Legs() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(8, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *Mammal) SetLegs(n int32) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, n)
	_, err := invokeMethod(8, 1, buf)
	return err
}

func (h *Mammal) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(8, 2, buf)
		h.ptr = 0
	}
}

// ManagedValue exercises the "concrete class with non-public destructor"
// case that googlesql's type hierarchy uses. Lifetime is owned by
// ManagedFactory (analogous to TypeFactory); user code only ever sees
// raw pointers and must not delete them. The bridge must still emit a
// Service for ManagedValue with all its accessors, but must NOT emit a
// Free RPC (the caller can't safely delete).
type ManagedFactory struct {
	ptr       uint64
	keepAlive []any
}

func (h *ManagedFactory) rawPtr() uint64 { return h.ptr }

func (h *ManagedFactory) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newManagedFactory(ptr uint64) *ManagedFactory {
	h := &ManagedFactory{ptr: ptr}
	runtime.SetFinalizer(h, (*ManagedFactory).free)
	return h
}

func newManagedFactoryNoFinalizer(ptr uint64) *ManagedFactory {
	h := &ManagedFactory{ptr: ptr}
	return h
}

func NewManagedFactory() (*ManagedFactory, error) {
	var buf []byte
	resp, err := invokeMethod(9, 0, buf)
	if err != nil {
		return nil, err
	}
	return newManagedFactory(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

// Creates and owns a new ManagedValue. Caller must not delete.
func (h *ManagedFactory) Make(kind int32, tag string) (*ManagedValue, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, kind)
	buf = pbAppendString(buf, 3, tag)
	resp, err := invokeMethod(9, 1, buf)
	if err != nil {
		return nil, err
	}
	return decodeChildHandle(resp, 1, h, newManagedValueNoFinalizer), nil
}

func (h *ManagedFactory) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(9, 2, buf)
		h.ptr = 0
	}
}

type ManagedValue struct {
	ptr       uint64
	keepAlive []any
}

func (h *ManagedValue) rawPtr() uint64 { return h.ptr }

func (h *ManagedValue) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newManagedValue(ptr uint64) *ManagedValue {
	h := &ManagedValue{ptr: ptr}
	return h
}

func newManagedValueNoFinalizer(ptr uint64) *ManagedValue {
	h := &ManagedValue{ptr: ptr}
	return h
}

// Accessors are public.
func (h *ManagedValue) Kind() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(10, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *ManagedValue) Tag() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(10, 1, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// (C) Multiple inheritance. Product picks up Named and Priced accessors
// side by side. Both sides of the diamond are non-virtual; the Go struct
// must embed both parents so method promotion reaches either tree.
type Named struct {
	ptr       uint64
	keepAlive []any
}

func (h *Named) rawPtr() uint64 { return h.ptr }

func (h *Named) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newNamed(ptr uint64) *Named {
	h := &Named{ptr: ptr}
	runtime.SetFinalizer(h, (*Named).free)
	return h
}

func newNamedNoFinalizer(ptr uint64) *Named {
	h := &Named{ptr: ptr}
	return h
}

func (h *Named) NamedName() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(11, 0, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func (h *Named) SetNamedName(n string) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendString(buf, 2, n)
	_, err := invokeMethod(11, 1, buf)
	return err
}

func (h *Named) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(11, 2, buf)
		h.ptr = 0
	}
}

type Priced struct {
	ptr       uint64
	keepAlive []any
}

func (h *Priced) rawPtr() uint64 { return h.ptr }

func (h *Priced) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newPriced(ptr uint64) *Priced {
	h := &Priced{ptr: ptr}
	runtime.SetFinalizer(h, (*Priced).free)
	return h
}

func newPricedNoFinalizer(ptr uint64) *Priced {
	h := &Priced{ptr: ptr}
	return h
}

func (h *Priced) PricedPrice() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(12, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Priced) SetPricedPrice(p float64) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendDouble(buf, 2, p)
	_, err := invokeMethod(12, 1, buf)
	return err
}

func (h *Priced) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(12, 2, buf)
		h.ptr = 0
	}
}

type Product struct {
	ptr       uint64
	keepAlive []any
	*Named
	*Priced
}

func (h *Product) rawPtr() uint64 { return h.ptr }

func (h *Product) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newProduct(ptr uint64) *Product {
	h := &Product{
		ptr:    ptr,
		Named:  newNamedNoFinalizer(ptr),
		Priced: newPricedNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Product).free)
	return h
}

func newProductNoFinalizer(ptr uint64) *Product {
	h := &Product{
		ptr:    ptr,
		Named:  newNamedNoFinalizer(ptr),
		Priced: newPricedNoFinalizer(ptr),
	}
	return h
}

func NewProduct() (*Product, error) {
	var buf []byte
	resp, err := invokeMethod(13, 0, buf)
	if err != nil {
		return nil, err
	}
	return newProduct(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *Product) SetStock(s int32) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, s)
	_, err := invokeMethod(13, 1, buf)
	return err
}

func (h *Product) Stock() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(13, 2, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *Product) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(13, 3, buf)
		h.ptr = 0
	}
}

// Derived class
type ScientificCalculator struct {
	*Calculator
}

func newScientificCalculator(ptr uint64) *ScientificCalculator {
	h := &ScientificCalculator{
		Calculator: newCalculatorNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*ScientificCalculator).free)
	return h
}

func newScientificCalculatorNoFinalizer(ptr uint64) *ScientificCalculator {
	h := &ScientificCalculator{
		Calculator: newCalculatorNoFinalizer(ptr),
	}
	return h
}

func (h *ScientificCalculator) Power(base float64, exp float64) (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendDouble(buf, 2, base)
	buf = pbAppendDouble(buf, 3, exp)
	resp, err := invokeMethod(14, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *ScientificCalculator) Sqrt(value float64) (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendDouble(buf, 2, value)
	resp, err := invokeMethod(14, 1, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *ScientificCalculator) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(14, 2, buf)
		h.ptr = 0
	}
}

// (A) Abstract base for downcast-via-assertion test.
type Shape struct {
	ptr       uint64
	keepAlive []any
}

func (h *Shape) rawPtr() uint64 { return h.ptr }

func (h *Shape) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func (*Shape) isShape() {}

func newShape(ptr uint64) *Shape {
	h := &Shape{ptr: ptr}
	runtime.SetFinalizer(h, (*Shape).free)
	return h
}

func newShapeNoFinalizer(ptr uint64) *Shape {
	h := &Shape{ptr: ptr}
	return h
}

func (h *Shape) Area() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(15, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func NewShapeFromImpl(impl ShapeCallback) (*Shape, error) {
	adapter := &shapeCallbackAdapter{impl: impl}
	id := RegisterCallback(adapter)
	var buf []byte
	buf = pbAppendInt32(buf, 1, id)
	resp, err := invokeMethod(15, 1, buf)
	if err != nil {
		UnregisterCallback(id)
		return nil, err
	}
	h := newShape(readScalarAtField(resp, 1, (*pbReader).readUint64))
	runtime.SetFinalizer(h, nil)
	runtime.SetFinalizer(h, func(h *Shape) { h.free(); UnregisterCallback(id) })
	return h, nil
}

func (h *Shape) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(15, 2, buf)
		h.ptr = 0
	}
}

type ShapeBox struct {
	ptr       uint64
	keepAlive []any
}

func (h *ShapeBox) rawPtr() uint64 { return h.ptr }

func (h *ShapeBox) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newShapeBox(ptr uint64) *ShapeBox {
	h := &ShapeBox{ptr: ptr}
	runtime.SetFinalizer(h, (*ShapeBox).free)
	return h
}

func newShapeBoxNoFinalizer(ptr uint64) *ShapeBox {
	h := &ShapeBox{ptr: ptr}
	return h
}

func NewShapeBox() (*ShapeBox, error) {
	var buf []byte
	resp, err := invokeMethod(16, 0, buf)
	if err != nil {
		return nil, err
	}
	return newShapeBox(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *ShapeBox) Add(s ShapeNode) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	if s != nil {
		buf = pbAppendHandle(buf, 2, s.rawPtr())
	}
	h.setKeepAlive(s)
	_, err := invokeMethod(16, 1, buf)
	return err
}

func (h *ShapeBox) Get(i int32) (ShapeNode, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, i)
	resp, err := invokeMethod(16, 2, buf)
	if err != nil {
		return nil, err
	}
	return decodeAbstractAs[ShapeNode](resp, 1, h, "ShapeNode")
}

func (h *ShapeBox) Size() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(16, 3, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *ShapeBox) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(16, 4, buf)
		h.ptr = 0
	}
}

type Square struct {
	*Shape
}

func newSquare(ptr uint64) *Square {
	h := &Square{
		Shape: newShapeNoFinalizer(ptr),
	}
	runtime.SetFinalizer(h, (*Square).free)
	return h
}

func newSquareNoFinalizer(ptr uint64) *Square {
	h := &Square{
		Shape: newShapeNoFinalizer(ptr),
	}
	return h
}

func NewSquare(s float64) (*Square, error) {
	var buf []byte
	buf = pbAppendDouble(buf, 1, s)
	resp, err := invokeMethod(17, 0, buf)
	if err != nil {
		return nil, err
	}
	return newSquare(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *Square) Area() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(17, 1, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Square) Side() (float64, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(17, 2, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func (h *Square) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(17, 3, buf)
		h.ptr = 0
	}
}

// StatefulCounter: a class with MIXED public and private state used to
// regression-test handle-based state preservation across the bridge.
//
//   - `label` is a public field (visible via the direct accessor below)
//   - `sum_` and `call_count_` are private state that can only be observed
//     through the public methods `total()` and `call_count()`.
//   - No virtual methods, so the existing handle-promotion rules based on
//     virtual dispatch do NOT apply; this class exercises the code path
//     that reclassifies mixed-field classes via HasPrivateFields.
//
// If the bridge treated this as a value type, each `add()` call would run
// against a freshly-constructed temporary and `sum_` would reset between
// calls. The test `TestStatefulCounterStatePreservation` verifies that
// does not happen.
type StatefulCounter struct {
	ptr       uint64
	keepAlive []any
}

func (h *StatefulCounter) rawPtr() uint64 { return h.ptr }

func (h *StatefulCounter) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func newStatefulCounter(ptr uint64) *StatefulCounter {
	h := &StatefulCounter{ptr: ptr}
	runtime.SetFinalizer(h, (*StatefulCounter).free)
	return h
}

func newStatefulCounterNoFinalizer(ptr uint64) *StatefulCounter {
	h := &StatefulCounter{ptr: ptr}
	return h
}

func NewStatefulCounter() (*StatefulCounter, error) {
	var buf []byte
	resp, err := invokeMethod(18, 0, buf)
	if err != nil {
		return nil, err
	}
	return newStatefulCounter(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func NewStatefulCounter2(initialId int32) (*StatefulCounter, error) {
	var buf []byte
	buf = pbAppendInt32(buf, 1, initialId)
	resp, err := invokeMethod(18, 1, buf)
	if err != nil {
		return nil, err
	}
	return newStatefulCounter(readScalarAtField(resp, 1, (*pbReader).readUint64)), nil
}

func (h *StatefulCounter) Add(delta int32) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, delta)
	_, err := invokeMethod(18, 2, buf)
	return err
}

func (h *StatefulCounter) CallCount() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(18, 3, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *StatefulCounter) Id() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(18, 4, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *StatefulCounter) Reset() error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	_, err := invokeMethod(18, 5, buf)
	return err
}

func (h *StatefulCounter) SetLabel(newLabel int32) error {
	buf := pbAppendHandle(nil, 1, h.ptr)
	buf = pbAppendInt32(buf, 2, newLabel)
	_, err := invokeMethod(18, 6, buf)
	return err
}

func (h *StatefulCounter) Total() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(18, 7, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

// public field: intentionally exposed
func (h *StatefulCounter) GetLabel() (int32, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(18, 8, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func (h *StatefulCounter) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(18, 9, buf)
		h.ptr = 0
	}
}

// TextNode / HeadingNode regression-test the abstract-handle naming
// rule. TextNode itself ends in "Node", so the generator must emit the
// Go interface as `TextNode` (not the doubled `TextNodeNode`) and
// rename the abstract struct to `TextNodeBase` so it does not collide
// with the interface. HeadingNode is a concrete descendant whose struct
// embeds `*TextNodeBase`.
type TextNodeBase struct {
	ptr       uint64
	keepAlive []any
}

func (h *TextNodeBase) rawPtr() uint64 { return h.ptr }

func (h *TextNodeBase) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func (*TextNodeBase) isTextNode() {}

func newTextNodeBase(ptr uint64) *TextNodeBase {
	h := &TextNodeBase{ptr: ptr}
	runtime.SetFinalizer(h, (*TextNodeBase).free)
	return h
}

func newTextNodeBaseNoFinalizer(ptr uint64) *TextNodeBase {
	h := &TextNodeBase{ptr: ptr}
	return h
}

func (h *TextNodeBase) Render() (string, error) {
	buf := pbAppendHandle(nil, 1, h.ptr)
	resp, err := invokeMethod(19, 0, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func NewTextNodeFromImpl(impl TextNodeCallback) (*TextNodeBase, error) {
	adapter := &textNodeCallbackAdapter{impl: impl}
	id := RegisterCallback(adapter)
	var buf []byte
	buf = pbAppendInt32(buf, 1, id)
	resp, err := invokeMethod(19, 1, buf)
	if err != nil {
		UnregisterCallback(id)
		return nil, err
	}
	h := newTextNodeBase(readScalarAtField(resp, 1, (*pbReader).readUint64))
	runtime.SetFinalizer(h, nil)
	runtime.SetFinalizer(h, func(h *TextNodeBase) { h.free(); UnregisterCallback(id) })
	return h, nil
}

func (h *TextNodeBase) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(nil, 1, h.ptr)
		module().invoke(19, 2, buf)
		h.ptr = 0
	}
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

// Free functions
func Add(a float64, b float64) (float64, error) {
	var buf []byte
	buf = pbAppendDouble(buf, 1, a)
	buf = pbAppendDouble(buf, 2, b)
	resp, err := invokeMethod(0, 0, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readDouble), nil
}

func AggregateResults(values []float64) ([]*Result, error) {
	var buf []byte
	for _, item := range values {
		buf = pbAppendDouble(buf, 1, item)
	}
	resp, err := invokeMethod(0, 1, buf)
	if err != nil {
		return nil, err
	}
	var items []*Result
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f == 1 {
			sub := pr.readSubmessage()
			items = append(items, unmarshalResult(sub.data))
		} else {
			pr.skip(w)
		}
	}
	return items, nil
}

func FormatResult(r *Result) (string, error) {
	var buf []byte
	if r != nil {
		buf = pbAppendSubmessage(buf, 1, r.marshal())
	}
	resp, err := invokeMethod(0, 2, buf)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Exercises the Logger callback end-to-end: invokes both virtuals on the
// supplied logger and returns the level it reported.
func RunWithLogger(logger LoggerNode, message string) (int32, error) {
	var buf []byte
	if logger != nil {
		buf = pbAppendHandle(buf, 1, logger.rawPtr())
	}
	buf = pbAppendString(buf, 2, message)
	resp, err := invokeMethod(0, 3, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}

func Version() (int32, error) {
	var buf []byte
	resp, err := invokeMethod(0, 4, buf)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readInt32), nil
}
